cmake_minimum_required(VERSION 3.20)
project(bug-clone-affinity-inherit C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS ON)
add_executable(bug-clone-affinity-inherit src/main.c)
target_compile_options(bug-clone-affinity-inherit PRIVATE -Wall -Wextra -Werror)
find_package(Threads REQUIRED)
target_link_libraries(bug-clone-affinity-inherit PRIVATE Threads::Threads)
install(TARGETS bug-clone-affinity-inherit RUNTIME DESTINATION usr/bin/starry-test-suit)
