cmake_minimum_required(VERSION 3.20)
project(syscall-test-sched-attr C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
add_executable(syscall-test-sched-attr src/main.c)
target_include_directories(syscall-test-sched-attr PRIVATE src)
target_compile_options(syscall-test-sched-attr PRIVATE -Wall -Wextra -Werror)
install(TARGETS syscall-test-sched-attr RUNTIME DESTINATION usr/bin/starry-test-suit)
