#!/usr/bin/env python3
"""Host-side golden generator for the cpu-model-test carpet.

Two jobs:
 1. Emit the small self-contained DERIVED assets the parser/slicer/pointcloud
    cells need (a KNOWN unit cube in OBJ/STL-ascii/PLY-ascii/PLY-binary so
    OBJ==STL and PLY-ascii==PLY-binary geometry can be cross-asserted; a
    synthetic sphere-sampled point cloud whose centroid is the origin and whose
    every point is at distance r - the closed-form pointcloud leg).
 2. Compute the goldens for the SHIPPED real assets (bunny.ply vertex count /
    bbox / centroid / spatial-hash signature) using the SAME geometry the C
    cells implement, and print them as JSON so the report + C constants agree.

Reproducible, no external mesh library. Slice goldens come from the existing
render-assets/golden/slice_golden.json (generated by slice_golden.py with
identical raw-segment shoelace semantics the C slicer mirrors).

Usage: gen_goldens.py <assets_out_dir> <bunny.ply> [bunny_scan.ply]
"""
import struct, sys, math, json, hashlib

# ---- KNOWN unit cube: 8 verts / 12 tris ---------------------------------
CUBE_V = [(0,0,0),(1,0,0),(1,1,0),(0,1,0),(0,0,1),(1,0,1),(1,1,1),(0,1,1)]
CUBE_F = [(0,1,2),(0,2,3),(4,6,5),(4,7,6),(0,4,5),(0,5,1),
          (1,5,6),(1,6,2),(2,6,7),(2,7,3),(3,7,4),(3,4,0)]

def write_cube_stl_ascii(path):
    with open(path, "w") as f:
        f.write("solid cube\n")
        for a,b,c in CUBE_F:
            f.write("  facet normal 0 0 0\n    outer loop\n")
            for idx in (a,b,c):
                f.write("      vertex %g %g %g\n" % CUBE_V[idx])
            f.write("    endloop\n  endfacet\n")
        f.write("endsolid cube\n")

def write_cube_stl_binary(path):
    with open(path, "wb") as f:
        f.write(b"\0"*80); f.write(struct.pack("<I", len(CUBE_F)))
        for a,b,c in CUBE_F:
            f.write(struct.pack("<3f", 0,0,0))
            for idx in (a,b,c): f.write(struct.pack("<3f", *CUBE_V[idx]))
            f.write(struct.pack("<H", 0))

def write_cube_obj(path):
    with open(path, "w") as f:
        f.write("# unit cube 8v/12f\n")
        for v in CUBE_V: f.write("v %g %g %g\n" % v)
        for a,b,c in CUBE_F: f.write("f %d %d %d\n" % (a+1,b+1,c+1))

def write_cube_ply_ascii(path):
    with open(path, "w") as f:
        f.write("ply\nformat ascii 1.0\n")
        f.write("element vertex 8\nproperty float x\nproperty float y\nproperty float z\n")
        f.write("element face 12\nproperty list uchar int vertex_indices\nend_header\n")
        for v in CUBE_V: f.write("%g %g %g\n" % v)
        for a,b,c in CUBE_F: f.write("3 %d %d %d\n" % (a,b,c))

def write_cube_ply_binary(path):
    with open(path, "wb") as f:
        f.write(("ply\nformat binary_little_endian 1.0\n"
                 "element vertex 8\nproperty float x\nproperty float y\nproperty float z\n"
                 "element face 12\nproperty list uchar int vertex_indices\nend_header\n").encode())
        for v in CUBE_V: f.write(struct.pack("<3f", *v))
        for a,b,c in CUBE_F: f.write(struct.pack("<B",3)); f.write(struct.pack("<3i",a,b,c))

# ---- synthetic sphere point cloud (closed-form) -------------------------
SPHERE_N = 4000
SPHERE_R = 2.5

def sphere_points(n, r):
    pts = []
    ga = math.pi * (3.0 - math.sqrt(5.0))
    for i in range(n):
        z = 1.0 - (2.0*i + 1.0)/n
        rho = math.sqrt(max(0.0, 1.0 - z*z))
        theta = ga * i
        pts.append((r*math.cos(theta)*rho, r*math.sin(theta)*rho, r*z))
    return pts

def write_sphere_ply(path, pts):
    with open(path, "w") as f:
        f.write("ply\nformat ascii 1.0\nelement vertex %d\n" % len(pts))
        f.write("property float x\nproperty float y\nproperty float z\nend_header\n")
        for x,y,z in pts: f.write("%.9g %.9g %.9g\n" % (x,y,z))

# ---- PLY reader for bunny goldens ---------------------------------------
def read_ply_vertices(path):
    with open(path, "rb") as f: data = f.read()
    nl = data.index(b"end_header\n") + len(b"end_header\n")
    header = data[:nl].decode("ascii","replace"); body = data[nl:]
    fmt=None; n_vert=0; vprops=[]; cur=None
    for line in header.splitlines():
        p = line.split()
        if not p: continue
        if p[0]=="format": fmt=p[1]
        elif p[0]=="element":
            cur=p[1]
            if cur=="vertex": n_vert=int(p[2])
        elif p[0]=="property" and cur=="vertex": vprops.append(p[-1])
    verts=[]
    if fmt=="ascii":
        toks=body.split(); stride=len(vprops)
        for i in range(n_vert):
            b=i*stride
            verts.append((float(toks[b]),float(toks[b+1]),float(toks[b+2])))
    else:
        stride=len(vprops)*4
        for i in range(n_vert):
            x,y,z=struct.unpack_from("<3f", body, i*stride); verts.append((x,y,z))
    return n_vert, verts

def bbox(pts):
    xs=[p[0] for p in pts]; ys=[p[1] for p in pts]; zs=[p[2] for p in pts]
    return (min(xs),min(ys),min(zs)),(max(xs),max(ys),max(zs))

def centroid(pts):
    n=len(pts); sx=sum(p[0] for p in pts); sy=sum(p[1] for p in pts); sz=sum(p[2] for p in pts)
    return (sx/n, sy/n, sz/n)

def spatial_hash_sig(verts, bbmin, bbmax, grid=16):
    span=[(bbmax[i]-bbmin[i]) if bbmax[i]>bbmin[i] else 1.0 for i in range(3)]
    counts=[0]*(grid*grid*grid)
    for (x,y,z) in verts:
        ix=min(max(int((x-bbmin[0])/span[0]*grid),0),grid-1)
        iy=min(max(int((y-bbmin[1])/span[1]*grid),0),grid-1)
        iz=min(max(int((z-bbmin[2])/span[2]*grid),0),grid-1)
        counts[(ix*grid+iy)*grid+iz]+=1
    b=bytearray()
    for c in counts: b+=struct.pack("<I", c & 0xffffffff)
    return hashlib.sha256(bytes(b)).hexdigest()

def main():
    out_dir = sys.argv[1]
    bunny = sys.argv[2] if len(sys.argv) > 2 else None
    import os; os.makedirs(out_dir, exist_ok=True)

    write_cube_obj(os.path.join(out_dir,"cube.obj"))
    write_cube_stl_ascii(os.path.join(out_dir,"cube_ascii.stl"))
    write_cube_stl_binary(os.path.join(out_dir,"cube.stl"))
    write_cube_ply_ascii(os.path.join(out_dir,"cube.ply"))
    write_cube_ply_binary(os.path.join(out_dir,"cube_bin.ply"))
    sp = sphere_points(SPHERE_N, SPHERE_R)
    write_sphere_ply(os.path.join(out_dir,"sphere_pc.ply"), sp)

    result = {"sphere_pc": {"n": SPHERE_N, "r": SPHERE_R,
              "centroid_tol": 1e-3, "radius_tol": 1e-4}}

    if bunny:
        n, verts = read_ply_vertices(bunny)
        bmin, bmax = bbox(verts)
        cen = centroid(verts)
        sig = spatial_hash_sig(verts, bmin, bmax, 16)
        result["bunny"] = {"n": n, "bbmin": bmin, "bbmax": bmax,
                           "centroid": cen, "sig16": sig}
    print(json.dumps(result, indent=2))

if __name__ == "__main__":
    main()
