#!/bin/sh
set -eu
echo "PREBUILD_START"
echo "STARRY_STAGING_ROOT=$STARRY_STAGING_ROOT"
echo "STARRY_CASE_OVERLAY_DIR=$STARRY_CASE_OVERLAY_DIR"
echo "STARRY_CASE_DIR=$STARRY_CASE_DIR"
echo "STARRY_ROOTFS=${STARRY_ROOTFS:-unset}"
echo "STARRY_BASE_ROOTFS=${STARRY_BASE_ROOTFS:-unset}"
echo "PREBUILD_END"
