[package]
name = "ax-cpu"
version = "0.9.1"
repository = "https://github.com/rcore-os/tgoskits"
edition.workspace = true
authors.workspace = true
description = "Privileged instruction and structure abstractions for various CPU architectures"
keywords = ["arceos", "cpu", "architecture", "hal"]
categories = ["embedded", "no-std", "hardware-support", "os"]
license = "Apache-2.0 AND MPL-2.0"

[lib]
test = false
doctest = false
bench = false

[features]
default = []
context = []
virtualization = ["context", "fp-simd", "exception-table", "dep:thiserror", "dep:tock-registers"]
exception-table = []
pmu = ["dep:thiserror"]
fp-simd = ["context"]
tls = ["context"]
uspace = ["context", "exception-table", "dep:bytemuck"]
riscv-thead-mae = []
riscv-sstc = []

[dependencies]
thiserror = { workspace = true, optional = true }
bytemuck = { version = "1.24", optional = true }
trait-ffi = { workspace = true }
log = "0.4"
ax-memory-addr = { workspace = true }
bitflags.workspace = true
page-table-generic.workspace = true
[target.'cfg(target_arch = "x86_64")'.dependencies]
tock-registers = { version = "0.10", optional = true }
ax-lazyinit = { workspace = true }
x86 = "0.52"
x86_64 = { version = "0.15", default-features = false, features = [
    "instructions",
] }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "11.0"
tock-registers = "0.10"

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv.workspace = true

[target.'cfg(target_arch = "loongarch64")'.dependencies]
loongArch64 = "0.2"


[lints.clippy]
new_without_default = "allow"

[package.metadata.docs.rs]
features = ["context", "fp-simd", "uspace", "pmu"]
targets = [
    "x86_64-unknown-none",
    "aarch64-unknown-none-softfloat",
    "riscv64gc-unknown-none-elf",
    "loongarch64-unknown-none-softfloat",
]
