cmake_minimum_required(VERSION 3.20)
project(bug-write-bad-buffer-efault C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS ON)
add_executable(bug-write-bad-buffer-efault src/main.c)
target_compile_options(bug-write-bad-buffer-efault PRIVATE -Wall -Wextra -Werror)
install(TARGETS bug-write-bad-buffer-efault RUNTIME DESTINATION usr/bin/starry-test-suit)
