features = [
  "ax-driver/rk3588-pcie",
  "ax-driver/realtek-rtl8125",
  "ax-driver/rockchip-sdhci",
  "ax-driver/rockchip-dwmmc",
  "browser-console",
  "fs",
]
log = "Error"
target = "aarch64-unknown-none-softfloat"
vm_configs = [
  "test-suit/axvisor/normal/board-orangepi-5-plus/dual-linux-zephyr/linux-smp1-sd.toml",
  "test-suit/axvisor/normal/board-orangepi-5-plus/dual-starry-zephyr/zephyr-smp1.toml",
]

[env]
AXVM_HTTP_BIND = "0.0.0.0:8080"
