[package]
name = "axvisor"
authors = ["Keyang Hu <keyang.hu@qq.com>", "周睿 <zrufo747@outlook.com>"]
edition.workspace = true
version = "0.5.23"
description = "A lightweight type-1 hypervisor based on ArceOS"
repository = "https://github.com/arceos-hypervisor/axvisor"
homepage = "https://github.com/arceos-hypervisor/axvisor"
documentation = "https://docs.rs/axvisor"
readme = "README.md"
keywords = ["hypervisor", "virtualization", "arceos", "type-1"]
categories = ["os", "no-std", "embedded"]
license = "Apache-2.0"
include = [
    ".cargo/config.toml",
    "src/**",
    "build.rs",
    "configs/**",
    "xtask/src/**",
    "README.md",
    "LICENSE*",
]

[[bin]]
name = "axvisor"
path = "src/main.rs"

[[bin]]
name = "xtask"
path = "xtask/src/main.rs"
test = false
required-features = ["host-xtask"]

[[test]]
name = "axtest"
path = "tests/axtest.rs"
harness = false
required-features = ["axtest", "fs"]

[features]
default = []
host-xtask = []
axtest = []
fs = ["ax-std/ext4fs", "ax-std/fatfs", "axvm/host-fs"]
sstc = ["axvm/sstc"]
stack-protector = ["ax-std/stack-protector"]
backtrace = ["ax-std/backtrace", "dep:axbacktrace"]
test-backtrace-panic = ["backtrace"]
test-panic-no-backtrace = ["dep:axbacktrace"]

[dependencies]
shlex.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(axtest)', 'cfg(feature, values("ax-std"))'] }

[target.'cfg(any(not(any(windows, unix)), target_env = "musl"))'.dependencies]
anyhow.workspace = true
log = "0.4"

# System dependent modules provided by ArceOS.
ax-std = { workspace = true, default-features = false, features = [
  "alloc",
  "fd",
  "ext-ld",
  "paging",
  "irq",
  "multitask",
  "task-ext",
  "smp",
  "hv",
  "tls",
  "std-compat",
] }
# System dependent modules provided by ArceOS-Hypervisor (bare-metal only)
# ax-runtime = { version = "=0.3.0-preview.1", features = ["alloc", "irq", "paging", "smp", "multitask"] }
axvm = { workspace = true, default-features = false, features = ["tls"] }
axvmconfig = { workspace = true, default-features = false }
ax-driver = { workspace = true, optional = true }
axbacktrace = { workspace = true, optional = true }

[dev-dependencies]
axtest.workspace = true
ax-hal = { workspace = true, features = ["paging", "irq", "smp", "hv"] }
ax-task = { workspace = true, features = ["axtest"] }

# xtask dependencies (only used on host platforms)
[target.'cfg(any(windows, all(unix, not(target_env = "musl"))))'.dependencies]
anyhow.workspace = true
axbuild = { workspace = true }
clap = { version = "4.6", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

[build-dependencies]
anyhow = { workspace = true, features = ["std"] }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
toml = { workspace = true, features = ["std", "serde", "parse", "display"] }
