cmake_minimum_required(VERSION 3.20)
project(syscall-test-small-family C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
add_executable(syscall-test-small-family src/main.c)
target_include_directories(syscall-test-small-family PRIVATE src)
target_compile_options(syscall-test-small-family PRIVATE -Wall -Wextra -Werror)
install(TARGETS syscall-test-small-family RUNTIME DESTINATION usr/bin/starry-test-suit)
