args = [
  "-nographic",
  "-cpu",
  "cortex-a72",
  "-machine",
  "virt,virtualization=on,gic-version=3",
  "-smp",
  "4",
  "-m",
  "8g",
]
fail_regex = [
  "(?i)\\bpanic(?:ked)?\\b",
  "(?i)kernel panic",
  "ARCEOS_TEST_FAIL",
]
success_regex = ["VM\\[2\\] boot success"]
to_bin = true
uefi = false
timeout = 180
