board_type = "OrangePi-5-Plus"
fail_regex = [
    "(?i)\\bpanic(?:ked)?\\b",
    "(?i)segmentation fault",
    "(?i)SIGSEGV",
    "exit with code: 139",
]
timeout = 300

[[shell_check_steps]]
success_regex = ["(?m)^Hello, world!\\s*$"]
