// @generated by competition/ivc/model/export_thermal_onnx.py; do not edit.
pub const MODEL_ID: &str = "thermal-4x6x1-v1";
pub const MODEL_SOURCE_SHA256: &str =
    "10e22ea81ee5dbfae0e1459646e55963f14d6f2149e2bab83e4fc75fbf586029";
pub(crate) const INPUTS: usize = 4;
pub(crate) const HIDDEN: usize = 6;
#[rustfmt::skip]
pub(crate) const HIDDEN_WEIGHTS: [[f32; INPUTS]; HIDDEN] = [
    [f32::from_bits(0x3f800000), f32::from_bits(0x00000000), f32::from_bits(0x00000000), f32::from_bits(0x00000000)],
    [f32::from_bits(0xbf800000), f32::from_bits(0x00000000), f32::from_bits(0x00000000), f32::from_bits(0x00000000)],
    [f32::from_bits(0x00000000), f32::from_bits(0x3f800000), f32::from_bits(0x00000000), f32::from_bits(0x00000000)],
    [f32::from_bits(0x00000000), f32::from_bits(0x00000000), f32::from_bits(0x3f800000), f32::from_bits(0x00000000)],
    [f32::from_bits(0x00000000), f32::from_bits(0x00000000), f32::from_bits(0xbf800000), f32::from_bits(0x00000000)],
    [f32::from_bits(0x00000000), f32::from_bits(0x00000000), f32::from_bits(0x00000000), f32::from_bits(0x3f800000)],
];
#[rustfmt::skip]
pub(crate) const HIDDEN_BIASES: [f32; HIDDEN] = [f32::from_bits(0x00000000), f32::from_bits(0x00000000), f32::from_bits(0x00000000), f32::from_bits(0x00000000), f32::from_bits(0x00000000), f32::from_bits(0x00000000)];
#[rustfmt::skip]
pub(crate) const OUTPUT_WEIGHTS: [f32; HIDDEN] = [f32::from_bits(0x3fa66666), f32::from_bits(0xbf000000), f32::from_bits(0x3f666666), f32::from_bits(0xbe3851ec), f32::from_bits(0x3e3851ec), f32::from_bits(0x3dcccccd)];
pub(crate) const OUTPUT_BIAS: f32 = f32::from_bits(0x3ca3d70a);
pub(crate) const OUTPUT_MIN: f32 = f32::from_bits(0x00000000);
pub(crate) const OUTPUT_MAX: f32 = f32::from_bits(0x3f800000);
pub(crate) const ERROR_SCALE: f32 = f32::from_bits(0x47435000);
pub(crate) const SETPOINT_OFFSET_MILLI_C: i32 = 20000;
pub(crate) const SETPOINT_SCALE: f32 = f32::from_bits(0x479c4000);
pub(crate) const RATE_SCALE: f32 = f32::from_bits(0x461c4000);
pub(crate) const ACTUATOR_INPUT_SCALE: f32 = f32::from_bits(0x447a0000);
pub(crate) const ACTUATOR_OUTPUT_SCALE: f32 = f32::from_bits(0x447a0000);
pub(crate) const ACTUATOR_ROUNDING_HALF: f32 = f32::from_bits(0x3f000000);

#[cfg(test)]
#[rustfmt::skip]
pub(crate) const GOLDEN_CASES: [([u32; INPUTS], u32, u16); 32] = [
    ([0x3e99999a, 0x3ee00000, 0x3dcccccd, 0x3ecccccd], 0x3f53645b, 826),
    ([0x00000000, 0x00000000, 0x00000000, 0x00000000], 0x3ca3d70a, 20),
    ([0x3f99999a, 0x00000000, 0x00000000, 0x00000000], 0x3f800000, 1000),
    ([0xc0266666, 0x00000000, 0x00000000, 0x00000000], 0x00000000, 0),
    ([0xbf99999a, 0xbf400000, 0x00000000, 0x00000000], 0x00000000, 0),
    ([0x40266666, 0x3fd00000, 0x00000000, 0x00000000], 0x3f800000, 1000),
    ([0x00000000, 0x00000000, 0xc1200000, 0x00000000], 0x3f800000, 1000),
    ([0x00000000, 0x00000000, 0x41200000, 0x00000000], 0x00000000, 0),
    ([0x00000000, 0x00000000, 0x00000000, 0x3f800000], 0x3df5c290, 120),
    ([0x3f333333, 0x3f000000, 0x3e800000, 0x3e800000], 0x3f800000, 1000),
    ([0xbf000000, 0x3ea00000, 0xbe800000, 0x3f400000], 0x3e2f5c29, 171),
    ([0xc0733333, 0xbf400000, 0x41200000, 0x00000000], 0x00000000, 0),
    ([0x40733333, 0x3fd00000, 0xc1200000, 0x3f800000], 0x3f800000, 1000),
    ([0xbe99999a, 0x3ec00000, 0xbf9e0419, 0x3f266666], 0x3efd4aa0, 495),
    ([0x3f19999a, 0x3f100000, 0x3f9e0419, 0x3eb33333], 0x3f800000, 1000),
    ([0x37a7c5ac, 0x3ec00000, 0x38d1b717, 0x3f000000], 0x3ed0a4e3, 408),
    ([0x3fa03127, 0x3f55999a, 0x40b276c9, 0x3f666666], 0x3f800000, 1000),
    ([0xbf231e3a, 0x3f99b98c, 0x3eef7660, 0x3e3c6a7f], 0x3f376ca4, 717),
    ([0xc0120371, 0xbdf55326, 0xc0e79ce0, 0x3ebf7cee], 0x3e60c280, 219),
    ([0x3fa93f29, 0x3fceb22d, 0x40ff5cfb, 0x3f43126f], 0x3f800000, 1000),
    ([0xbfe716b1, 0xbc9a6b51, 0xc0c4bc6a, 0x3f353f7d], 0x3e96e978, 295),
    ([0xc0049b52, 0x3d76872b, 0x41065dcc, 0x3e96872b], 0x00000000, 0),
    ([0xbfadba0a, 0x3eeaf007, 0xc0e17a78, 0x3eee978d], 0x3f800000, 1000),
    ([0x3f78a32f, 0x3ed88312, 0x40c2978d, 0x3ed70a3d], 0x3f1c518d, 611),
    ([0xc0138961, 0xbeecc7e3, 0xc0a12bd4, 0x3f589375], 0x00000000, 0),
    ([0x3f0d68c7, 0x3f8518fc, 0xc09f93de, 0x3ed78d50], 0x3f800000, 1000),
    ([0x3fa3b795, 0x3ea18106, 0x3f96cbfb, 0x3f2b020c], 0x3f800000, 1000),
    ([0xc0028eb4, 0xbe8dcfab, 0x40f620c5, 0x3f178d50], 0x00000000, 0),
    ([0x3f8aa1b6, 0x3f3ff7cf, 0x409260aa, 0x3e75c28f], 0x3f800000, 1000),
    ([0x3f8b8716, 0x3f998ce7, 0xc04068dc, 0x3f5c28f6], 0x3f800000, 1000),
    ([0xc0343e96, 0xbf3d3f7d, 0x3fb42268, 0x3e72b021], 0x00000000, 0),
    ([0xbff94e3c, 0xbeceb852, 0x41024ea5, 0x3f71a9fc], 0x00000000, 0),
];
