env = {AX_IP = "10.0.2.15", AX_GW = "10.0.2.2"}
features = [
  "ax-hal/riscv64-qemu-virt",
  "qemu",
  "ax-drivers/pci",
  "ax-drivers/virtio-blk",
  "ax-drivers/virtio-net",
  "ax-drivers/virtio-gpu",
  "ax-drivers/virtio-input",
  "ax-drivers/virtio-socket",
]
max_cpu_num = 4
log = "Warn"
plat_dyn = false
target = "riscv64gc-unknown-none-elf"
