features = [
    "ax-driver/virtio-blk",
    "fs",
]
log = "Info"
target = "aarch64-unknown-none-softfloat"
vm_configs = ["os/axvisor/configs/vms/qemu/aarch64/linux-hardware-forwarded-gicv3-smp1.toml"]
