#!/usr/bin/env python3
"""Opt-in profile-use (PGO) image builder for issue #2308 on OrangePi-5-Plus.

The archived five-feature profile is not certified for the current ten-feature
board release. Until a new candidate passes the board tail-latency guardrail,
the profile/feature gate deliberately rejects this entry before compilation.

Public entry:

    python3 scripts/perf/wakeup-pgo/build.py --output-dir <out>

The script re-hosts the verified profile (`profile-use.profdata.zst`),
writes a StarryOS build config that injects `-Cprofile-use=<absolute profile>` and a
`RUSTC_WRAPPER` into the bare aarch64 target through axbuild's `[env]` table, and then
runs `cargo xtask starry build -c <config>`.  The ordinary release build is untouched:
PGO only happens when this script is invoked, and the build uses its own
`CARGO_TARGET_DIR` inside the output directory.

The shipped profile was trained at `PROFILE_TRAINING_COMMIT`; the identity references
below describe only that historical five-feature benchmark. The source and lock gates
pin the latest reviewed checkout independently. Passing those gates does not certify
an old profile for a changed release feature set.

Every gate fails closed.  Source drift, toolchain drift, `Cargo.lock` drift, a profile
archive or profile hash mismatch, a foreign profile path in the rustc wrapper log, a
CFG/hash mismatch warning, an unexpected warning, an image that still carries LLVM
profile counter sections, machine code that differs from the board-tested candidate, or a
flashable `.bin` whose bytes outside `.kallsyms` differ from the board-tested image all
stop the run.  A run that does not pass every gate never prints `WAKEUP_PGO_IMAGE_READY`.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import struct
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

PACKAGE_DIR = Path(__file__).resolve().parent
REPO_ROOT = PACKAGE_DIR.parents[2]

# Reviewed dev base. Cargo.lock is pinned separately because this PR upgrades it.
BASELINE_COMMIT = "7fb26597a8ff77e6bff315705520695d8b57a3bc"
# Commit the shipped profile was trained at.  The profile may be carried onto newer dev
# only while the image identity gates below reproduce the board-measured candidate.
PROFILE_TRAINING_COMMIT = "d051d572b76c9675b60b0c9442dd87c5fa1af8ba"
# Frozen facts of the audited build: toolchain, lockfile and feature set are pinned to the
# same values the profile and the board evidence were produced with.
CARGO_LOCK_SHA256 = "d199b6e7acb7435157be1d7fd927d823d8c163783131542914fc41f4ab7c9f5b"
RUST_CHANNEL = "nightly-2026-09-04"
RUSTC_COMMIT_HASH = "a69a63265cfd9e006d43137f98301b8d274ad4c9"
RUSTC_LLVM_VERSION = "23.1.1"
PROFILE_SHA256 = "f08464508b9dc02911e9660ccfa0216795cc4b89e07f6723b147d8de6ea8d49f"
PROFILE_ARCHIVE = PACKAGE_DIR / "profile-use.profdata.zst"
# Pins the shipped archive bytes; regenerating the archive requires updating this value.
PROFILE_ARCHIVE_SHA256 = "817ea24326ada0f29a3166c4d377c8b047e34a2f1c2875c6de45b7d2c0a6d3ae"

PROFILE_NAME = "profile-use.profdata"
WRAPPER_TEMPLATE = PACKAGE_DIR / "stdlib-wrapper.py.in"
WRAPPER_NAME = "stdlib-wrapper.py"
WRAPPER_LOG_NAME = "stdlib-wrapper.jsonl"
CONFIG_NAME = "build-config.toml"
BUILD_LOG_NAME = "build.log"
RESULT_NAME = "build-result.json"
TARGET_DIR_NAME = "target"

# The target, features, log and CPU count match the ordinary OrangePi board release.
TARGET = "aarch64-unknown-none-softfloat"
RUSTFLAGS_ENV = "CARGO_TARGET_AARCH64_UNKNOWN_NONE_SOFTFLOAT_RUSTFLAGS"
LOG_LEVEL = "Info"
MAX_CPU_NUM = 8
FEATURES = (
    "ax-driver/list-pci-devices",
    "ax-driver/rk3588-pcie",
    "ax-driver/realtek-rtl8125",
    "ax-driver/rockchip-soc",
    "ax-driver/rockchip-dwc-xhci",
    "ax-driver/rockchip-ehci",
    "ax-driver/rockchip-sdhci",
    "ax-driver/rockchip-dwmmc",
    "ax-driver/rk3588-cpufreq",
    "rknpu",
)
# The archived profile and its image identity references cover only this older
# benchmark configuration. Do not repin them to a failed full-board candidate.
PROFILE_FEATURES = (
    "ax-driver/rk3588-pcie",
    "ax-driver/realtek-rtl8125",
    "ax-driver/rockchip-soc",
    "ax-driver/rockchip-sdhci",
    "ax-driver/rockchip-dwmmc",
)
PGO_LLVM_ARGS = ("-Cllvm-args=-disable-vp", "-Cllvm-args=-pgo-warn-missing-function")
ROOT_CRATE = "starryos"

# Audit baseline of the board-measured profile-use build (`resume649`, trained at
# PROFILE_TRAINING_COMMIT).  A rebuild reproduces the same code and data, so the untrained
# function set must reproduce as well; a different count means this checkout no longer
# rebuilds that image, so re-audit it or retrain the profile.
REFERENCE_MISSING_WARNINGS = 6087
REFERENCE_MISSING_UNIQUE = 5933
REFERENCE_PROFILE_RECORDS = 27146
# Kernel machine code of the board-tested candidate (`resume649-profile-use.elf`, whose
# OrangePi A-B-B-A evidence is archived under `evidence/`).  Only `.kallsyms` is
# regenerated by axbuild, so this pair is what a rebuild has to reproduce to stay covered
# by that evidence.
REFERENCE_TEXT_BYTES = 6799040
REFERENCE_TEXT_SHA256 = "38c0dcdb4ce8a9f0c96aa5643c4932c009621f0779295e98406520341a279a59"
# Whole-image identity of the same board-tested candidate: the flashable `.bin` length,
# the `.kallsyms` placement inside it (image base 0xffffffff80000000) and the sha256 of
# every other byte.  `.kallsyms` is regenerated per build, so it is the only slice excluded.
REFERENCE_IMAGE_BASE = 0xFFFFFFFF80000000
REFERENCE_KALLSYMS_ADDRESS = 0xFFFFFFFF80774000
REFERENCE_KALLSYMS_SIZE = 8388608
REFERENCE_BIN_BYTES = 16609280
REFERENCE_BIN_SHA256_EXCLUDING_KALLSYMS = (
    "f81c220cafc659cf050873f37cf35135a1c3a2e938bc62a5115e88be99ba583c"
)

EXCLUDED_PREFIXES = ("docs/", "scripts/perf/wakeup-pgo/")

MISSING_RE = re.compile(r"no profile data available for function (\S+) Hash = (\d+)")
CFG_MISMATCH_RE = re.compile(r"function control flow change detected \(hash mismatch\)")
GENERATED_SUMMARY_RE = re.compile(r"^warning: `.*`.*generated \d+ warning")
BENIGN_WARNING_PATTERNS = (
    re.compile(r"partially ignored, possibly due to the lack of a return path\."),
    re.compile(r"^warning: the following packages contain code that will be rejected by a future"),
)
ELF_ARTIFACT_RE = re.compile(r"^\[axbuild\] starry artifact elf=(.+)$", re.M)
# Everything after this marker is the kernel build itself; the part before it is the host
# side (building the xtask driver), whose warnings say nothing about the profile.
STAGE_MARKER = "[axbuild] starry build package="


class GateError(Exception):
    """A fail-closed gate stopped the run."""


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def git(*args: str, allow_failure: bool = False) -> str:
    proc = subprocess.run(
        ["git", *args], cwd=REPO_ROOT, text=True, capture_output=True
    )
    if proc.returncode != 0:
        if allow_failure:
            return ""
        raise GateError(
            f"git {' '.join(args)} failed: {proc.stderr.strip() or proc.stdout.strip()}"
        )
    return proc.stdout.strip()


def is_git_ignored(relative: str) -> bool:
    proc = subprocess.run(
        ["git", "check-ignore", "--quiet", relative],
        cwd=REPO_ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    return proc.returncode == 0


def is_excluded(path: str) -> bool:
    # The exact lockfile bytes are checked by cargo_lock_gate() below.
    return path in ("docs", "scripts/perf/wakeup-pgo", "Cargo.lock") or path.startswith(EXCLUDED_PREFIXES)


def resolve_output_dir(raw: str) -> Path:
    candidate = Path(raw).expanduser()
    if not candidate.is_absolute():
        candidate = Path.cwd() / candidate
    out = candidate.resolve()
    if out == REPO_ROOT or REPO_ROOT in out.parents:
        relative = out.relative_to(REPO_ROOT)
        if not is_git_ignored(str(relative)):
            raise GateError(
                f"output dir {out} lives inside the managed source tree and is not "
                "gitignored; use a path outside the repository or an ignored path such as "
                "tmp/wakeup-pgo-out, otherwise the build outputs would be mistaken for "
                "source drift"
            )
    return out


def source_gate() -> dict:
    """Reject drift outside docs/, this package and the separately pinned lockfile."""
    if not git("rev-parse", "--verify", f"{BASELINE_COMMIT}^{{commit}}", allow_failure=True):
        raise GateError(
            f"baseline commit {BASELINE_COMMIT} is not a valid commit in this repository; "
            "the image cannot be proven to match the board-measured candidate, so re-audit "
            "the checkout or retrain the profile"
        )
    head = git("rev-parse", "HEAD")
    committed_or_worktree = [
        path
        for path in git("diff", "--name-only", BASELINE_COMMIT).splitlines()
        if path and not is_excluded(path)
    ]
    staged_or_untracked: list[str] = []
    for line in git("status", "--porcelain", "--untracked-files=all").splitlines():
        for path in (part.strip() for part in line[3:].split(" -> ")):
            if path and not is_excluded(path):
                staged_or_untracked.append(path)
    drift = sorted(set(committed_or_worktree) | set(staged_or_untracked))
    if drift:
        sample = ", ".join(drift[:10])
        raise GateError(
            f"source drift against the pinned dev baseline {BASELINE_COMMIT}: {len(drift)} "
            f"path(s) differ outside docs/, scripts/perf/wakeup-pgo and Cargo.lock "
            f"({sample}); the "
            f"shipped profile was trained at {PROFILE_TRAINING_COMMIT} and is reusable only "
            "while this checkout rebuilds the board-measured image, so re-audit the new "
            "commit and retrain the profile if code or data changed"
        )
    return {
        "baseline_commit": BASELINE_COMMIT,
        "profile_training_commit": PROFILE_TRAINING_COMMIT,
        "head": head,
        "head_equals_baseline": head == BASELINE_COMMIT,
        "diff_vs_baseline_paths": sorted(set(committed_or_worktree)),
        "staged_or_untracked_paths": sorted(set(staged_or_untracked)),
        "excluded_prefixes": list(EXCLUDED_PREFIXES),
        "clean": True,
    }


def toolchain_gate() -> dict:
    toolchain_file = REPO_ROOT / "rust-toolchain.toml"
    content = toolchain_file.read_text()
    match = re.search(r'^\s*channel\s*=\s*"([^"]+)"', content, re.M)
    if match is None or match.group(1) != RUST_CHANNEL:
        raise GateError(
            f"rust-toolchain.toml channel is "
            f"{match.group(1) if match else 'missing'}, expected {RUST_CHANNEL}; the profile "
            "was trained with that toolchain, retrain or restore the pinned toolchain"
        )
    proc = subprocess.run(
        ["rustc", "-vV"], cwd=REPO_ROOT, text=True, capture_output=True
    )
    if proc.returncode != 0:
        raise GateError(f"rustc -vV failed: {proc.stderr.strip() or proc.stdout.strip()}")
    version = proc.stdout
    commit = re.search(r"^commit-hash: ([0-9a-f]+)$", version, re.M)
    llvm = re.search(r"^LLVM version: (\S+)$", version, re.M)
    if commit is None or commit.group(1) != RUSTC_COMMIT_HASH:
        raise GateError(
            f"rustc commit-hash is {commit.group(1) if commit else 'missing'}, expected "
            f"{RUSTC_COMMIT_HASH} ({RUST_CHANNEL}); the profile is toolchain specific"
        )
    if llvm is None or llvm.group(1) != RUSTC_LLVM_VERSION:
        raise GateError(
            f"rustc LLVM version is {llvm.group(1) if llvm else 'missing'}, expected "
            f"{RUSTC_LLVM_VERSION}; the profile format and hash scheme are LLVM specific"
        )
    return {
        "channel": RUST_CHANNEL,
        "commit_hash": commit.group(1),
        "llvm_version": llvm.group(1),
        "rustc_version": version,
    }


def cargo_lock_gate() -> dict:
    digest = sha256_file(REPO_ROOT / "Cargo.lock")
    if digest != CARGO_LOCK_SHA256:
        raise GateError(
            f"Cargo.lock sha256 is {digest}, expected {CARGO_LOCK_SHA256}; the profile was "
            "built from that lockfile, retrain before reusing it"
        )
    return {"Cargo.lock_sha256": digest}


def profile_feature_gate() -> dict:
    if FEATURES != PROFILE_FEATURES:
        raise GateError(
            "the packaged profile was trained with five benchmark features, but the "
            "ordinary OrangePi release has ten; the full-feature candidate measured "
            "on the updated dev failed the FIFO absolute-timer p999 guardrail. "
            "Retrain and remeasure before enabling a release profile"
        )
    return {"features_match_trained_profile": True}


def unpack_profile(out: Path) -> Path:
    if not PROFILE_ARCHIVE.exists():
        raise GateError(f"packaged profile archive is missing: {PROFILE_ARCHIVE}")
    archive_digest = sha256_file(PROFILE_ARCHIVE)
    if archive_digest != PROFILE_ARCHIVE_SHA256:
        raise GateError(
            f"packaged profile archive sha256 is {archive_digest}, expected "
            f"{PROFILE_ARCHIVE_SHA256}; update PROFILE_ARCHIVE_SHA256 only after verifying "
            "the decompressed profile sha256"
        )
    profile = out / PROFILE_NAME
    partial = out / f"{PROFILE_NAME}.partial"
    partial.unlink(missing_ok=True)
    try:
        with partial.open("wb") as handle:
            proc = subprocess.run(
                ["zstd", "--decompress", "--stdout", "--quiet", str(PROFILE_ARCHIVE)],
                stdout=handle,
                stderr=subprocess.PIPE,
                text=False,
            )
    except FileNotFoundError as error:
        raise GateError(f"host must provide `zstd` to unpack the profile: {error}") from error
    if proc.returncode != 0:
        partial.unlink(missing_ok=True)
        detail = proc.stderr.decode("utf-8", "replace").strip()
        raise GateError(f"zstd failed to decompress {PROFILE_ARCHIVE.name}: {detail}")
    digest = sha256_file(partial)
    if digest != PROFILE_SHA256:
        partial.unlink(missing_ok=True)
        raise GateError(
            f"decompressed profile sha256 is {digest}, expected {PROFILE_SHA256}; refuse to "
            "build with an unverified profile, retrain it"
        )
    partial.replace(profile)
    return profile


def write_config(out: Path, profile: Path, wrapper: Path) -> Path:
    rustflags = " ".join((f"-Cprofile-use={profile}", *PGO_LLVM_ARGS))
    features = "\n".join(f'  "{feature}",' for feature in FEATURES)
    config = (
        "# Generated by scripts/perf/wakeup-pgo/build.py for issue #2308; do not edit.\n"
        "# Same target/log/max_cpu_num/features as the ordinary OrangePi release;\n"
        "# the profile and wrapper paths are dynamic absolute paths.\n"
        f'target = "{TARGET}"\n'
        f'log = "{LOG_LEVEL}"\n'
        f"max_cpu_num = {MAX_CPU_NUM}\n"
        "features = [\n"
        f"{features}\n"
        "]\n"
        "\n"
        "[env]\n"
        f'{RUSTFLAGS_ENV} = "{rustflags}"\n'
        f'RUSTC_WRAPPER = "{wrapper}"\n'
    )
    path = out / CONFIG_NAME
    path.write_text(config)
    return path


def install_wrapper(out: Path) -> Path:
    if not WRAPPER_TEMPLATE.exists():
        raise GateError(f"rustc wrapper template is missing: {WRAPPER_TEMPLATE}")
    wrapper = out / WRAPPER_NAME
    shutil.copyfile(WRAPPER_TEMPLATE, wrapper)
    wrapper.chmod(0o755)
    return wrapper


def run_build(out: Path, config: Path) -> int:
    target_dir = out / TARGET_DIR_NAME
    if target_dir.exists():
        raise GateError(
            f"{target_dir} already exists; a profile-use audit needs a full recompile of "
            "every aarch64 crate, so use a fresh --output-dir (or delete that directory)"
        )
    wrapper_log = out / WRAPPER_LOG_NAME
    wrapper_log.unlink(missing_ok=True)
    env = dict(os.environ)
    env["CARGO_TARGET_DIR"] = str(target_dir)
    command = ["cargo", "xtask", "starry", "build", "-c", str(config)]
    log_path = out / BUILD_LOG_NAME
    proc = subprocess.Popen(
        command,
        cwd=REPO_ROOT,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    with log_path.open("w") as handle:
        for line in proc.stdout:
            handle.write(line)
            # The per-function profile warnings dominate the log, and rustc follows each of
            # them with a blank line; keep the console to real progress, warnings and errors.
            # `build.log` still receives every line of the build.
            if line.strip() and not MISSING_RE.search(line):
                sys.stdout.write(line)
    code = proc.wait()
    if code != 0:
        raise GateError(f"cargo xtask starry build failed with exit code {code}; see {log_path}")
    return code


def elf64_sections(path: Path) -> list[dict]:
    data = path.read_bytes()
    if data[:4] != b"\x7fELF" or data[4] != 2 or data[5] != 1:
        raise GateError(f"{path} is not a little-endian ELF64 file")
    shoff = struct.unpack_from("<Q", data, 0x28)[0]
    shentsize = struct.unpack_from("<H", data, 0x3A)[0]
    shnum = struct.unpack_from("<H", data, 0x3C)[0]
    shstrndx = struct.unpack_from("<H", data, 0x3E)[0]
    if shoff == 0 or shnum == 0 or shstrndx >= shnum:
        raise GateError(f"{path} has no usable section header table")
    sections = []
    for index in range(shnum):
        base = shoff + index * shentsize
        name_offset = struct.unpack_from("<I", data, base)[0]
        _, address, offset, size = struct.unpack_from("<QQQQ", data, base + 8)
        sections.append(
            {
                "name_offset": name_offset,
                "address": address,
                "offset": offset,
                "size": size,
            }
        )
    strtab_section = sections[shstrndx]
    strtab = data[strtab_section["offset"] : strtab_section["offset"] + strtab_section["size"]]
    for section in sections:
        start = section["name_offset"]
        end = strtab.find(b"\0", start)
        section["name"] = strtab[start:end].decode("utf-8", "replace") if end >= 0 else ""
    return sections


def elf_identity(path: Path) -> dict:
    data = path.read_bytes()
    sections = elf64_sections(path)
    counters = sorted(
        section["name"] for section in sections if section["name"].startswith("__llvm_prf")
    )
    if counters:
        raise GateError(
            f"{path.name} still carries LLVM profile sections {counters}; the profile-use "
            "flags did not reach the final image"
        )
    text = next((section for section in sections if section["name"] == ".text"), None)
    if text is None:
        raise GateError(f"{path.name} has no .text section")
    kallsyms = next((section for section in sections if section["name"] == ".kallsyms"), None)
    text_bytes = data[text["offset"] : text["offset"] + text["size"]]
    text_sha256 = sha256_bytes(text_bytes)
    return {
        "path": str(path),
        "file": path.name,
        "size": len(data),
        "sha256": sha256_bytes(data),
        "text_address": hex(text["address"]),
        "text_size": text["size"],
        "text_sha256": text_sha256,
        "profile_sections_present": counters,
        "reference_text_size": REFERENCE_TEXT_BYTES,
        "reference_text_sha256": REFERENCE_TEXT_SHA256,
        "text_matches_board_candidate": (
            text["size"] == REFERENCE_TEXT_BYTES and text_sha256 == REFERENCE_TEXT_SHA256
        ),
        "kallsyms_address": None if kallsyms is None else kallsyms["address"],
        "kallsyms_address_hex": None if kallsyms is None else hex(kallsyms["address"]),
        "kallsyms_size": None if kallsyms is None else kallsyms["size"],
    }


def require_board_text_identity(identity: dict) -> None:
    """Fail closed unless the kernel machine code matches the board-tested candidate."""
    if identity["text_matches_board_candidate"]:
        return
    raise GateError(
        "kernel machine code differs from the board-tested candidate: .text size/sha256 is "
        f"{identity['text_size']} / {identity['text_sha256']}, expected "
        f"{REFERENCE_TEXT_BYTES} / {REFERENCE_TEXT_SHA256}; the archived OrangePi A-B-B-A "
        "evidence only covers the board-tested image, so re-measure on the board before "
        "treating this image as measured"
    )


def require_board_bin_identity(identity: dict, binary: Path | None) -> dict:
    """Fail closed unless the flashable `.bin` matches the board-tested image.

    `.kallsyms` is regenerated by every build, so the identity is the length of the image,
    the placement of that one section, and the sha256 over all remaining bytes.
    """
    if binary is None or not binary.is_file():
        raise GateError(
            "the flashable .bin is missing, so the board-tested image identity cannot be "
            "verified; refusing to report a measured image"
        )
    if identity["kallsyms_size"] is None:
        raise GateError(
            "the kernel ELF has no .kallsyms section, so the board-tested image identity "
            "cannot be verified; refusing to report a measured image"
        )
    if (
        identity["kallsyms_address"] != REFERENCE_KALLSYMS_ADDRESS
        or identity["kallsyms_size"] != REFERENCE_KALLSYMS_SIZE
    ):
        raise GateError(
            f".kallsyms is at {identity['kallsyms_address_hex']} with size "
            f"{identity['kallsyms_size']}, expected {hex(REFERENCE_KALLSYMS_ADDRESS)} with "
            f"size {REFERENCE_KALLSYMS_SIZE}; the archived OrangePi evidence does not cover "
            "this image layout, so re-measure on the board"
        )
    data = binary.read_bytes()
    if len(data) != REFERENCE_BIN_BYTES:
        raise GateError(
            f"{binary.name} is {len(data)} bytes, expected {REFERENCE_BIN_BYTES}; the "
            "archived OrangePi evidence does not cover this image, so re-measure on the board"
        )
    offset = REFERENCE_KALLSYMS_ADDRESS - REFERENCE_IMAGE_BASE
    end = offset + REFERENCE_KALLSYMS_SIZE
    if offset < 0 or end > len(data):
        raise GateError(
            f".kallsyms covers {hex(offset)}..{hex(end)} outside {binary.name} "
            f"({len(data)} bytes); the board-tested image identity cannot be verified"
        )
    digest = hashlib.sha256(data[:offset] + data[end:]).hexdigest()
    if digest != REFERENCE_BIN_SHA256_EXCLUDING_KALLSYMS:
        raise GateError(
            f"{binary.name} bytes outside .kallsyms hash to {digest}, expected "
            f"{REFERENCE_BIN_SHA256_EXCLUDING_KALLSYMS}; code or data differ from the "
            "board-tested image, so re-measure on the board before claiming readiness"
        )
    return {
        "path": str(binary),
        "size": len(data),
        "reference_size": REFERENCE_BIN_BYTES,
        "image_base": hex(REFERENCE_IMAGE_BASE),
        "kallsyms_offset": offset,
        "kallsyms_offset_hex": hex(offset),
        "kallsyms_size": REFERENCE_KALLSYMS_SIZE,
        "sha256_excluding_kallsyms": digest,
        "reference_sha256_excluding_kallsyms": REFERENCE_BIN_SHA256_EXCLUDING_KALLSYMS,
        "matches_board_candidate": True,
    }


def binary_identity(elf: Path) -> dict | None:
    binary = elf.with_suffix(".bin")
    if not binary.is_file():
        return None
    return {
        "path": str(binary),
        "file": binary.name,
        "size": binary.stat().st_size,
        "sha256": sha256_file(binary),
    }


def ensure_binary(elf: Path) -> Path:
    """Derive the flashable `.bin` when cargo did not refresh one (fresh target dir)."""
    binary = elf.with_suffix(".bin")
    if binary.is_file():
        return binary
    try:
        proc = subprocess.run(
            ["rust-objcopy", "--strip-all", "-O", "binary", str(elf), str(binary)],
            cwd=REPO_ROOT,
            text=True,
            capture_output=True,
        )
    except FileNotFoundError as error:
        raise GateError(f"`rust-objcopy` is required to derive {binary.name}: {error}") from error
    if proc.returncode != 0:
        raise GateError(
            f"rust-objcopy failed to derive {binary.name}: "
            f"{proc.stderr.strip() or proc.stdout.strip()}"
        )
    return binary


def check_wrapper_log(out: Path, profile: Path) -> dict:
    log = out / WRAPPER_LOG_NAME
    if not log.exists():
        raise GateError(
            f"{WRAPPER_LOG_NAME} is missing: the rustc wrapper never ran, so there is no "
            "evidence that the starryos root crate used the profile"
        )
    records = [json.loads(line) for line in log.read_text().splitlines() if line.strip()]
    if not records:
        raise GateError(
            f"{WRAPPER_LOG_NAME} is empty: no aarch64 crate was recompiled and the profile "
            "injection cannot be audited; use a fresh --output-dir"
        )
    expected = f"-Cprofile-use={profile}"
    foreign = sorted(
        {
            argument
            for record in records
            for argument in record["args"]
            if argument.startswith("-Cprofile-use=") and argument != expected
        }
    )
    if foreign:
        raise GateError(f"rustc wrapper saw profile paths other than {expected}: {foreign}")
    roots = [record for record in records if record.get("crate") == ROOT_CRATE]
    if not any(expected in record["args"] for record in roots):
        raise GateError(
            f"no {ROOT_CRATE} rustc invocation carried {expected}; the root crate did not "
            "receive the profile"
        )
    return {
        "target_invocations": len(records),
        "root_invocations": len(roots),
        "expected_profile_arg": expected,
        "root_profile_use_verified": True,
        "foreign_profile_use_args": foreign,
    }


def audit_warnings(log_text: str) -> dict:
    """Audit the kernel build section of the log; the caller slices it with split_build_log."""
    lines = log_text.splitlines()
    missing = [(name, int(value)) for name, value in MISSING_RE.findall(log_text)]
    missing_unique = sorted(set(missing))
    cfg_mismatch = [line for line in lines if CFG_MISMATCH_RE.search(line)]
    other = [
        line
        for line in lines
        if line.startswith("warning: ")
        and not MISSING_RE.search(line)
        and not GENERATED_SUMMARY_RE.match(line)
    ]
    unexpected = [
        line
        for line in other
        if not any(pattern.search(line) for pattern in BENIGN_WARNING_PATTERNS)
    ]
    audit = {
        "missing_warnings": len(missing),
        "missing_unique": len(missing_unique),
        "reference_missing_warnings": REFERENCE_MISSING_WARNINGS,
        "reference_missing_unique": REFERENCE_MISSING_UNIQUE,
        "reference_profile_records": REFERENCE_PROFILE_RECORDS,
        "cfg_mismatch_lines": cfg_mismatch,
        "cfg_mismatch_count": len(cfg_mismatch),
        "other_warning_lines": other,
        "unexpected_warning_lines": unexpected,
    }
    if cfg_mismatch:
        raise GateError(
            f"{len(cfg_mismatch)} CFG/hash mismatch warning(s): the profile does not match "
            f"this source, retrain it (first: {cfg_mismatch[0]})"
        )
    if unexpected:
        raise GateError(
            f"{len(unexpected)} unexpected warning line(s) in the build log: "
            f"{unexpected[:3]}"
        )
    if (
        len(missing) != REFERENCE_MISSING_WARNINGS
        or len(missing_unique) != REFERENCE_MISSING_UNIQUE
    ):
        raise GateError(
            "missing-function warning counts differ from the board-measured baseline "
            f"({len(missing)}/{len(missing_unique)} vs "
            f"{REFERENCE_MISSING_WARNINGS}/{REFERENCE_MISSING_UNIQUE}); untrained functions "
            "are expected, but a different count means source, toolchain, features or the "
            "profile drifted, so retrain the profile"
        )
    return audit


def split_build_log(log_text: str) -> tuple[str, str]:
    """Split the log into the kernel build and the host-side driver build."""
    index = log_text.find(STAGE_MARKER)
    if index < 0:
        return log_text, ""
    return log_text[index:], log_text[:index]


def warning_summary(log_text: str) -> dict:
    lines = [line for line in log_text.splitlines() if line.startswith("warning: ")]
    return {"count": len(lines), "sample": lines[:10]}


def environment_passthrough() -> dict:
    """Record inherited variables that could still change the compiler invocation."""
    names = ("RUSTFLAGS", "CARGO_ENCODED_RUSTFLAGS", "CARGO_BUILD_RUSTFLAGS", "RUSTC_WRAPPER")
    return {name: os.environ[name] for name in names if name in os.environ}


def env_injection_evidence(log_text: str, profile: Path, wrapper: Path) -> dict:
    return {
        "rustflags_env_seen": f"{RUSTFLAGS_ENV}=-Cprofile-use={profile}" in log_text,
        "rustc_wrapper_seen": f"RUSTC_WRAPPER={wrapper}" in log_text,
    }


def write_result(out: Path, report: dict) -> None:
    path = out / RESULT_NAME
    path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")


def prepare_only_summary(config: Path, profile: Path, wrapper: Path, out: Path) -> None:
    print("wakeup-pgo: prepare-only finished, nothing was compiled")
    print(f"wakeup-pgo: profile  {profile}")
    print(f"wakeup-pgo: config   {config}")
    print(f"wakeup-pgo: wrapper  {wrapper}")
    print(f"wakeup-pgo: result   {out / RESULT_NAME}")
    print(
        "wakeup-pgo: build with `cargo xtask starry build -c "
        f"{config}` (build.py sets CARGO_TARGET_DIR={out / TARGET_DIR_NAME})"
    )


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build the opt-in profile-use (PGO) StarryOS image for issue #2308."
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="absolute or relative directory that receives the profile, config, logs and image",
    )
    parser.add_argument(
        "--prepare-only",
        action="store_true",
        help="verify the artifacts and write the config without compiling anything",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    try:
        out = resolve_output_dir(args.output_dir)
    except GateError as error:
        print(f"WAKEUP_PGO_BUILD_NOT_READY: {error}", file=sys.stderr)
        return 1

    report = {
        "tool": "scripts/perf/wakeup-pgo/build.py",
        "issue": 2308,
        "board": "OrangePi-5-Plus-1",
        "baseline_commit": BASELINE_COMMIT,
        "profile_training_commit": PROFILE_TRAINING_COMMIT,
        "repo_root": str(REPO_ROOT),
        "output_dir": str(out),
        "prepare_only": args.prepare_only,
        "generated_at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "pgo": {
            "target": TARGET,
            "features": list(FEATURES),
            "packaged_profile_features": list(PROFILE_FEATURES),
            "log": LOG_LEVEL,
            "max_cpu_num": MAX_CPU_NUM,
            "llvm_args": list(PGO_LLVM_ARGS),
            "profile_sha256": PROFILE_SHA256,
            "profile_archive": str(PROFILE_ARCHIVE),
            "profile_archive_sha256": PROFILE_ARCHIVE_SHA256,
        },
        "environment_passthrough": environment_passthrough(),
        "ready": False,
    }
    try:
        report["source_gate"] = source_gate()
        report["toolchain_gate"] = toolchain_gate()
        report["cargo_lock_gate"] = cargo_lock_gate()
        report["profile_feature_gate"] = profile_feature_gate()
        out.mkdir(parents=True, exist_ok=True)
        profile = unpack_profile(out)
        wrapper = install_wrapper(out)
        config = write_config(out, profile, wrapper)
        report["profile"] = {
            "path": str(profile),
            "sha256": sha256_file(profile),
            "size": profile.stat().st_size,
        }
        report["config"] = {"path": str(config), "sha256": sha256_file(config)}
        report["wrapper"] = {"path": str(wrapper), "sha256": sha256_file(wrapper)}
        if args.prepare_only:
            report["status"] = "prepared_only"
            write_result(out, report)
            prepare_only_summary(config, profile, wrapper, out)
            return 0
        report["status"] = "building"
        report["build"] = {
            "command": ["cargo", "xtask", "starry", "build", "-c", str(config)],
            "cargo_target_dir": str(out / TARGET_DIR_NAME),
            "log": str(out / BUILD_LOG_NAME),
        }
        report["build"]["exit_code"] = run_build(out, config)
        log_text = (out / BUILD_LOG_NAME).read_text(errors="replace")
        kernel_log, host_log = split_build_log(log_text)
        report["build"]["env_injection"] = env_injection_evidence(log_text, profile, wrapper)
        report["build"]["host_build_warnings"] = warning_summary(host_log)
        report["wrapper_log"] = check_wrapper_log(out, profile)
        report["warning_audit"] = audit_warnings(kernel_log)
        match = ELF_ARTIFACT_RE.search(log_text)
        if match is None:
            raise GateError(
                f"build log does not report an artifact line `[axbuild] starry artifact elf=`; "
                f"cannot locate the ELF to audit ({out / BUILD_LOG_NAME})"
            )
        elf = Path(match.group(1).strip())
        if not elf.is_file():
            raise GateError(f"reported artifact {elf} does not exist")
        ensure_binary(elf)
        identity = elf_identity(elf)
        binary = binary_identity(elf)
        report["image"] = {"elf": identity, "bin": binary}
        require_board_text_identity(identity)
        report["image"]["bin_without_kallsyms"] = require_board_bin_identity(
            identity, Path(binary["path"]) if binary else None
        )
        report["status"] = "profile_use_image_ready"
        report["ready"] = True
        write_result(out, report)
        image = report["image"]["elf"]
        print("WAKEUP_PGO_IMAGE_READY")
        print(f"wakeup-pgo: elf   {image['path']} sha256={image['sha256']}")
        print(
            f"wakeup-pgo: .text size={image['text_size']} sha256={image['text_sha256']} "
            "matches board-tested candidate"
        )
        board_bin = report["image"]["bin_without_kallsyms"]
        print(
            f"wakeup-pgo: bin   {board_bin['path']} size={board_bin['size']} "
            f"sha256={report['image']['bin']['sha256']}"
        )
        print(
            f"wakeup-pgo: bin minus .kallsyms sha256={board_bin['sha256_excluding_kallsyms']} "
            "matches board-tested candidate"
        )
        audit = report["warning_audit"]
        print(
            "wakeup-pgo: audit cfg_mismatch=%d missing_warnings=%d missing_unique=%d "
            "unexpected=%d"
            % (
                audit["cfg_mismatch_count"],
                audit["missing_warnings"],
                audit["missing_unique"],
                len(audit["unexpected_warning_lines"]),
            )
        )
        print(f"wakeup-pgo: result {out / RESULT_NAME}")
        return 0
    except GateError as error:
        report["status"] = "not_ready"
        report["failure"] = str(error)
        try:
            out.mkdir(parents=True, exist_ok=True)
            write_result(out, report)
        except OSError:
            pass
        print(f"WAKEUP_PGO_BUILD_NOT_READY: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
