//! Runtime loading of a device tree finalized by `VmMachinePlanner`.

use axvmconfig::{AxVMCrateConfig, VMBootProtocol};

use crate::{
    AxVmResult, ax_err_type,
    boot::{BootImageProvider, fdt::GuestDtbImage},
    config::AxVMConfig,
};

pub(crate) mod create;
mod host;
mod policy;
pub(crate) mod tree;

#[cfg(test)]
mod tree_tests;

pub use create::{patch_guest_fdt_for_runtime, update_fdt};
pub use host::{require_host_fdt, try_get_host_fdt};
pub use policy::GuestFdtPolicy;

/// Returns the plan-generated DTB selected for this boot attempt.
pub fn prepare_dtb_guest(
    vm_config: &mut AxVMConfig,
    vm_create_config: &mut AxVMCrateConfig,
    _provider: &dyn BootImageProvider,
) -> AxVmResult<Option<GuestDtbImage>> {
    if vm_create_config.kernel.effective_boot_protocol() == VMBootProtocol::Uefi {
        skip_guest_dtb(vm_config, vm_create_config);
        return Ok(None);
    }

    let bytes = vm_config
        .machine_plan()
        .device_tree_firmware()
        .ok_or_else(|| {
            ax_err_type!(
                InvalidInput,
                "non-UEFI guest has no device tree finalized by its machine plan"
            )
        })?;
    info!(
        "VM[{}] uses the firmware generated by its immutable machine plan",
        vm_config.id()
    );
    Ok(Some(GuestDtbImage::new(bytes.to_vec())))
}

pub(crate) fn selected_guest_fdt_policy() -> GuestFdtPolicy {
    super::guest_fdt_policy()
}

fn skip_guest_dtb(vm_config: &mut AxVMConfig, vm_create_config: &mut AxVMCrateConfig) {
    info!(
        "VM[{}] uses UEFI boot protocol, skipping guest DTB handling",
        vm_config.id()
    );
    vm_config.update_dtb_load_gpa(None);
    vm_create_config.kernel.dtb_load_addr = None;
}
