[machine]
mode = "virtual"
firmware = "auto"

[base]
id = 1
name = "GuestVM-aarch64"
cpu_num = 1
phys_cpu_sets = [1]

[kernel]
entry_point = 0x4008_0000
kernel_path = "arceos-aarch64.bin"
kernel_load_addr = 0x4008_0000
image_location = "fs"

[[memory.regions]]
guest_base = 0x4000_0000
size = 0x4000_0000
permissions = "rwx"
backing = { kind = "allocate" }

[devices]
disable_defaults = []
deny = []
