[base]
id = 1
name = "GuestVM-riscv64"
guest_type = "passthrough"
cpu_num = 1
phys_cpu_sets = [1]

[kernel]
entry_point = 0x8020_0000
kernel_path = "arceos-riscv64.bin"
kernel_load_addr = 0x8020_0000
image_location = "fs"
memory_regions = [
    [0x8000_0000, 0x100_0000, 0x7, 1],
]

# NS16550 and vPLIC are supplied by the RISC-V machine profile.
[devices]
passthrough = []
disabled = []
