args = ["-cpu", "rv64,h=false", "-m", "1G", "-smp", "1", "-display", "none", "-serial", "mon:stdio"]
timeout = 60
uefi = false
to_bin = true
fail_regex = ["(?i)\\bpanic(?:ked)?\\b"]

[[shell_check_steps]]
success_regex = ["CPU_HYPERVISOR_PROBE_OK"]
