cmake_minimum_required(VERSION 3.20)
project(bug-cow-refcount-overflow C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS ON)
add_executable(bug-cow-refcount-overflow src/main.c)
target_compile_options(bug-cow-refcount-overflow PRIVATE -Wall -Wextra -Werror)
install(TARGETS bug-cow-refcount-overflow RUNTIME DESTINATION usr/bin/starry-test-suit)
