[package]
name = "starry-process"
version = "0.4.15"
edition.workspace = true
authors = ["朝倉水希 <asakuramizu111@gmail.com>"]
description = "Process management for Starry OS"
keywords = ["starry-os"]
repository = "https://github.com/Starry-OS/starry-process"
license = "Apache-2.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(axtest)'] }

[features]
multitask = ["dep:ax-sync"]

[dependencies]
ax-kspin = { workspace = true, features = ["smp"] }
ax-lazyinit = { workspace = true }
ax-sync = { workspace = true, features = ["multitask"], optional = true }

[dev-dependencies]
ctor = "0.4.1"
ax-kspin = { workspace = true, features = ["host-test", "smp"] }
