//! Task-3 1D temporal CNN forward inference (frozen architecture, M0).
//!
//! The model is a pure-Rust, allocation-free implementation of:
//!
//! ```text
//! input:  64 samples x 4 features [state, target, error, prev_output]
//! Conv1D  4 -> 32, kernel 5, same padding, ReLU
//! Conv1D 32 -> 64, kernel 5, same padding, ReLU
//! Global average pooling
//! Dense 64 -> 32, ReLU
//! Dense 32 -> 1
//! ```
//!
//! Weights are generated by `scripts/task3/train_model.py` /
//! `scripts/task3/dagger_train.py` and embedded as a little-endian f64 blob in
//! `model/weights.bin` (structure and hash recorded in `model/model.json`).
//! The layer order is the lexicographic order of the exporter's state dict
//! keys: `conv1.bias`, `conv1.weight`, `conv2.bias`, `conv2.weight`,
//! `fc1.bias`, `fc1.weight`, `fc2.bias`, `fc2.weight`.
//!
//! Numerics deliberately mirror the Python reference (torch float64): f64
//! accumulation with same-padding convolution, so the golden-vector tests in
//! `model/golden_vectors.rs` hold to tight tolerances.

#![no_std]

pub mod perception;
pub mod video_safety;

/// History window length consumed by the model input.
pub const WINDOW: usize = 64;
/// Input feature count: state, target, error, previous output.
pub const FEATURES: usize = 4;

const CONV1_OUT: usize = 32;
const CONV2_OUT: usize = 64;
const KERNEL: usize = 5;
const PAD: usize = KERNEL / 2;
const FC1_OUT: usize = 32;

const WEIGHTS: &[u8] = include_bytes!("../model/weights.bin");

// Element offsets into the flattened weight blob (lexicographic state-dict
// order, all f64):
//   conv1.bias 0..32, conv1.weight 32..672, conv2.bias 672..736,
//   conv2.weight 736..10976, fc1.bias 10976..11008, fc1.weight 11008..13056,
//   fc2.bias 13056..13057, fc2.weight 13057..13089.
const CONV1_BIAS: usize = 0;
const CONV1_WEIGHT: usize = 32;
const CONV2_BIAS: usize = 672;
const CONV2_WEIGHT: usize = 736;
const FC1_BIAS: usize = 10976;
const FC1_WEIGHT: usize = 11008;
const FC2_BIAS: usize = 13056;
const FC2_WEIGHT: usize = 13057;

#[inline]
fn weight_at(element: usize) -> f64 {
    f64::from_le_bytes(
        WEIGHTS[element * 8..element * 8 + 8]
            .try_into()
            .expect("weight blob bounds"),
    )
}

/// Raw model output for the given history window.
///
/// Inputs are pre-normalised by the caller (each channel divided by 1000).
/// The returned value is in the same scale as the training labels (0..1000
/// before the caller's clamp).
pub fn forward(history: &[[f64; FEATURES]; WINDOW]) -> f64 {
    let mut conv1 = [0.0f64; CONV1_OUT * WINDOW];
    let mut conv2 = [0.0f64; CONV2_OUT * WINDOW];

    for out in 0..CONV1_OUT {
        for t in 0..WINDOW {
            let mut acc = weight_at(CONV1_BIAS + out);
            for k in 0..KERNEL {
                let t_padded = (t + k).wrapping_sub(PAD);
                if t_padded < WINDOW {
                    for (ch, value) in history[t_padded].iter().enumerate() {
                        let w = weight_at(CONV1_WEIGHT + (out * FEATURES + ch) * KERNEL + k);
                        acc += w * value;
                    }
                }
            }
            conv1[out * WINDOW + t] = relu(acc);
        }
    }

    for out in 0..CONV2_OUT {
        for t in 0..WINDOW {
            let mut acc = weight_at(CONV2_BIAS + out);
            for k in 0..KERNEL {
                let t_padded = (t + k).wrapping_sub(PAD);
                if t_padded < WINDOW {
                    for (ch, row) in conv1.as_chunks::<WINDOW>().0.iter().enumerate() {
                        let w = weight_at(CONV2_WEIGHT + (out * CONV1_OUT + ch) * KERNEL + k);
                        acc += w * row[t_padded];
                    }
                }
            }
            conv2[out * WINDOW + t] = relu(acc);
        }
    }

    let mut pooled = [0.0f64; CONV2_OUT];
    for (ch, value) in pooled.iter_mut().enumerate() {
        let mut acc = 0.0;
        for t in 0..WINDOW {
            acc += conv2[ch * WINDOW + t];
        }
        *value = acc / WINDOW as f64;
    }
    let mut hidden = [0.0f64; FC1_OUT];
    for (out, hidden_value) in hidden.iter_mut().enumerate() {
        let mut acc = weight_at(FC1_BIAS + out);
        for (ch, value) in pooled.iter().enumerate() {
            acc += weight_at(FC1_WEIGHT + out * CONV2_OUT + ch) * value;
        }
        *hidden_value = relu(acc);
    }
    let mut output = weight_at(FC2_BIAS);
    for (ch, value) in hidden.iter().enumerate() {
        output += weight_at(FC2_WEIGHT + ch) * value;
    }
    output
}

#[inline]
fn relu(value: f64) -> f64 {
    if value > 0.0 { value } else { 0.0 }
}

/// Build the normalized model input window from raw control-loop history.
///
/// Mirrors `scripts/task3/features.py::build_window` exactly (the single
/// source of truth for the frozen feature contract):
///
/// - `state_history` / `output_history` are chronological with the most recent
///   sample last; windows shorter than `WINDOW` are padded at the front with
///   the first available value (`fallback_state` / `fallback_output` when the
///   history is empty);
/// - channel 0: state / 1000;
/// - channel 1: current target / 1000, constant across the window;
/// - channel 2: (target - state) / 1000 per sample point;
/// - channel 3: applied output per sample point / 1000.
///
/// The golden-window test vectors in `model/golden_vectors.rs` pin this
/// function to the Python reference.
pub fn build_features(
    state_history: &[i32],
    output_history: &[i32],
    target: i32,
    fallback_state: i32,
    fallback_output: i32,
) -> [[f64; FEATURES]; WINDOW] {
    let states = padded_window(state_history, fallback_state);
    let outputs = padded_window(output_history, fallback_output);
    let mut window = [[0.0f64; FEATURES]; WINDOW];
    for index in 0..WINDOW {
        let state = states[index] as f64;
        let target_f = target as f64;
        window[index][0] = state / 1000.0;
        window[index][1] = target_f / 1000.0;
        window[index][2] = (target_f - state) / 1000.0;
        window[index][3] = outputs[index] as f64 / 1000.0;
    }
    window
}

fn padded_window(history: &[i32], fallback: i32) -> [i32; WINDOW] {
    let mut values = [fallback; WINDOW];
    let available = history.len().min(WINDOW);
    if available > 0 {
        let start = history.len().saturating_sub(WINDOW);
        let pad = history[start];
        for value in values.iter_mut() {
            *value = pad;
        }
        for offset in 0..available {
            values[WINDOW - available + offset] = history[start + offset];
        }
    }
    values
}

#[cfg(test)]
#[path = "../model/golden_vectors.rs"]
mod golden_vectors;
