cmake_minimum_required(VERSION 3.20)
project(perf-event-group C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
add_executable(perf-event-group src/perf_event_group.c)
target_compile_options(perf-event-group PRIVATE -Wall -Wextra -Werror -O2)
install(TARGETS perf-event-group RUNTIME DESTINATION usr/bin/starry-test-suit)
