args = ["-cpu", "la464", "-m", "2G", "-no-reboot", "-smp", "1", "-display", "none", "-serial", "mon:stdio"]
timeout = 60
uefi = true
to_bin = true
fail_regex = ["(?i)\\bpanic(?:ked)?\\b"]

[[shell_check_steps]]
success_regex = ["CPU_GUEST_ENTRY_OK"]
