args = ["-m", "1G", "-smp", "1", "-display", "none", "-serial", "mon:stdio", "-accel", "kvm", "-cpu", "host,+vmx,-la57"]
timeout = 60
uefi = true
to_bin = true
fail_regex = ["(?i)\\bpanic(?:ked)?\\b"]

[[shell_check_steps]]
success_regex = ["CPU_GUEST_ENTRY_OK"]
