cmake_minimum_required(VERSION 3.20)
project(bugfix-tty-pgrp-namespace C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
add_executable(bugfix-tty-pgrp-namespace src/main.c)
target_include_directories(bugfix-tty-pgrp-namespace PRIVATE src ${CMAKE_CURRENT_SOURCE_DIR}/../common)
target_compile_options(bugfix-tty-pgrp-namespace PRIVATE -Wall -Wextra -Werror)
install(TARGETS bugfix-tty-pgrp-namespace RUNTIME DESTINATION usr/bin/starry-test-suit)
