cmake_minimum_required(VERSION 3.20)
project(test-archprctl-tls C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
add_executable(test-archprctl-tls src/main.c)
target_include_directories(test-archprctl-tls PRIVATE src)
target_compile_options(test-archprctl-tls PRIVATE -Wall -Wextra -Werror)
install(TARGETS test-archprctl-tls RUNTIME DESTINATION usr/bin/starry-test-suit)
