features = [
    "ax-driver/nvme",
    "fs",
]
log = "Info"
target = "aarch64-unknown-none-softfloat"
vm_configs = [
    "test-suit/axvisor/normal/qemu/ivshmem/configs/linux-ivshmem-peer0.toml",
    "test-suit/axvisor/normal/qemu/ivshmem/configs/zephyr-ivshmem-peer1.toml",
]
