features = [
    "ax-driver/virtio-blk",
    "fs",
]
log = "Info"
target = "aarch64-unknown-none-softfloat"
vm_configs = [
    "test-suit/axvisor/normal/qemu/ivc/configs/arceos-ivc-publisher.toml",
    "test-suit/axvisor/normal/qemu/ivc/configs/linux-ivc-subscriber.toml",
]
