//! Emits the linker-script argument for the final ArceBoot image.
//!
//! The script chain (`axplat.x` -> somehal `link.x` -> someboot
//! `someboot.x`) is generated by the axplat-dyn/somehal/someboot build
//! scripts into their `OUT_DIR`s, which are on the linker search path via
//! `cargo:rustc-link-search`. This mirrors how `axtask` wires up the
//! `linker.x` produced by `axruntime`.

fn main() {
    println!("cargo:rustc-link-arg=-Taxplat.x");
}
