# AxVM machine policy.
[machine]
mode = "passthrough"
firmware = "auto"
interrupts_passthrough = true

[base]
id = 1
name = "zephyr-qemu"
cpu_num = 1
phys_cpu_ids = [0x0]

[kernel]
entry_point = 0x400010b4
image_location = "memory"
kernel_path = "/path/to/zephyr.bin"
kernel_load_addr = 0x40000000
dtb_load_addr = 0x47e00000

[[memory.regions]]
guest_base = 0x40000000
size = 0x8000000
permissions = "rwx"
backing = { kind = "allocate" }

[devices]
disable_defaults = []
deny = []
