# AxVM machine policy.
[machine]
mode = "passthrough"
firmware = "auto"
interrupts_passthrough = false

[base]
id = 1
name = "arceos-qemu-uefi"
cpu_num = 1
phys_cpu_sets = [0x1]

[kernel]
entry_point = 0xfffffff0
image_location = "fs"
kernel_path = "/guest/arceos/arceos-x86_64-uefi.bin"
kernel_load_addr = 0x200000
enable_bios = true
boot_protocol = "uefi"
uefi_firmware_path = "/guest/arceos/OVMF_CODE.fd"
bios_load_addr = 0xffc00000

[[memory.regions]]
guest_base = 0x0
size = 0x1000000
permissions = "rwx"
backing = { kind = "allocate" }

[[memory.regions]]
guest_base = 0xffc00000
size = 0x400000
permissions = "rwx"
backing = { kind = "allocate" }

[devices]
disable_defaults = []
deny = []
