# AxVM machine policy.
[machine]
mode = "passthrough"
firmware = "auto"
interrupts_passthrough = false

[base]
id = 1
name = "linux-x86_64-qemu-svm"
cpu_num = 1
phys_cpu_sets = [0x1]

[kernel]
entry_point = 0x8000
image_location = "fs"
kernel_path = "/guest/linux/linux-qemu"
kernel_load_addr = 0x200000
enable_bios = false
cmdline = "console=ttyS0 root=/dev/vda ro rootwait rootflags=noload devtmpfs.mount=1 init=/sbin/getty acpi=off pci=conf1 pci=nomsi irqpoll no_timer_check initcall_blacklist=ahci_pci_driver_init,i8042_init -- -n -l /bin/sh -L 115200 ttyS0 dumb"

[[memory.regions]]
guest_base = 0x0
size = 0x8000000
permissions = "rwx"
backing = { kind = "identity-allocate" }

[[memory.regions]]
guest_base = 0x0
size = 0x100000
permissions = "rwx"
backing = { kind = "allocate" }

[devices]
disable_defaults = []
deny = []

[[devices.virtual]]
id = "x86-com1"
model = "x86-com1"
source = { kind = "auto" }
backend = { kind = "host-console", rx = "exclusive", tx = "shared" }
