# AxVM machine policy.
[machine]
mode = "passthrough"
firmware = "auto"
interrupts_passthrough = false

[base]
id = 1
name = "nimbos"
cpu_num = 1
phys_cpu_sets = [0x1]

[kernel]
entry_point = 0x8000
image_location = "fs"
kernel_path = "/guest/nimbos/nimbos-qemu"
kernel_load_addr = 0x200000
enable_bios = true
boot_protocol = "multiboot"

[[memory.regions]]
guest_base = 0x0
size = 0x1000000
permissions = "rwx"
backing = { kind = "allocate" }

[devices]
disable_defaults = []
deny = []
