[package]
name = "arceos-virtio-blk-test"
version = "0.1.0"
edition.workspace = true
publish = false

[features]
default = ["arceos"]
arceos = ["dep:ax-hal", "dep:ax-std", "ax-std/arceos"]

[dependencies]
ax-driver = { workspace = true, features = ["virtio-core"] }
ax-hal = { workspace = true, optional = true }
ax-std = { workspace = true, optional = true, features = ["default"] }
virtio-drivers.workspace = true
