# Vm base info configs
#
[base]
# Guest vm id.
id = 1
# Guest vm name.
name = "linux"
# Virtualization type.
guest_type = "passthrough"
# The number of virtual CPUs.
cpu_num = 2
# The physical CPU ids.
phys_cpu_ids = [0x200, 0x00]

#
# Vm kernel configs
#
[kernel]
# The entry point of the kernel image.
entry_point = 0x20_4008_0000
# The location of image: "memory" | "fs".
# Load from file system.
image_location = "fs"
# The load address of the kernel image.
kernel_load_addr = 0x20_4008_0000
# The file path of the kernel image.
kernel_path = "/guest/linux/phytiumpi"
# The file path of the device tree blob (DTB).
dtb_load_addr = 0x20_4000_0000
# dtb_path = "/path/to/axvisor/configs/vms/phytiumpi/linux-smp2.dtb"
# Memory regions with format (`base_paddr`, `size`, `flags`, `map_type`).
# For `map_type`, 0 means `MAP_ALLOC`, 1 means `MAP_IDENTICAL`, 2 means `MAP_RESERVED`.
memory_regions = [
  [0x20_4000_0000, 0x4000_0000, 0x7, 1], # System RAM MAP_IDENTICAL
  # [0xa000_0000, 0x2000_0000, 0x7, 1], # System RAM 1G MAP_IDENTICAL
]

#
# Device specifications
#

# Physical-device selection. Virtual platform devices are machine-owned.
[devices]
passthrough = []
disabled = []
