# AxVM machine policy.
[machine]
mode = "passthrough"
firmware = "auto"
interrupts_passthrough = true

[base]
id = 1
name = "rtthread"
cpu_num = 1
phys_cpu_ids = [0x100]

[kernel]
entry_point = 0x80080000
image_location = "fs"
kernel_load_addr = 0x80080000
kernel_path = "/guest/rtthread/phytiumpi"

[[memory.regions]]
guest_base = 0x80000000
size = 0x10000000
permissions = "rwx"
backing = { kind = "allocate" }

[devices]
disable_defaults = []
deny = []
