# AxVM machine policy.
[machine]
mode = "passthrough"
firmware = "auto"
interrupts_passthrough = true

[base]
id = 1
name = "zephyr-phytiumpi"
cpu_num = 1
phys_cpu_ids = [0x0]

[kernel]
entry_point = 0x2020007d6c
image_location = "memory"
kernel_load_addr = 0x2020000000
kernel_path = "/path/to/zephyr-phytiumpi.bin"
dtb_load_addr = 0x2020000000

[[memory.regions]]
guest_base = 0x2020000000
size = 0x20000000
permissions = "rwx"
backing = { kind = "reserved" }

[devices]
disable_defaults = []
deny = []
