#!/usr/bin/env bash
# Collect bare-metal vs AxVisor-guest RT latency samples and emit a comparison report.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPORT_DIR="${ROOT}/plans/task1-reports"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BARE_LOG="${REPORT_DIR}/bare-${STAMP}.log"
GUEST_LOG="${REPORT_DIR}/guest-${STAMP}.log"
REPORT_MD="${REPORT_DIR}/compare-${STAMP}.md"

mkdir -p "${REPORT_DIR}"

info() { echo "[task1] $*"; }

parse_rt_latency_lines() {
  local log_file="$1"
  grep -E 'RT_LATENCY mode=' "${log_file}" | sed 's/^.*\(RT_LATENCY mode=\)/\1/' || true
}

emit_report_table() {
  local label="$1"
  local log_file="$2"
  echo "### ${label}"
  echo
  echo '```'
  parse_rt_latency_lines "${log_file}"
  echo '```'
  echo
}

info "Collecting bare-metal baseline..."
(
  cd "${ROOT}"
  ./scripts/task1/run-rt-baseline.sh
) 2>&1 | tee "${BARE_LOG}"

info "Collecting AxVisor guest baseline..."
(
  cd "${ROOT}"
  ./scripts/task1/run-rt-guest-baseline.sh
) 2>&1 | tee "${GUEST_LOG}"

{
  echo "# Task 1 RT Latency Comparison (${STAMP})"
  echo
  echo "Generated by \`scripts/task1/collect-rt-latency-report.sh\`."
  echo
  emit_report_table "Bare-metal ArceOS (mode=bare)" "${BARE_LOG}"
  emit_report_table "AxVisor guest ArceOS idle post-opt (mode=guest)" "${GUEST_LOG}"
  echo "## Notes"
  echo
  echo "- Guest run uses \`arceos-rt-smp1.toml\` (pCPU3, vcpu_priorities = [-20]) via \`arceos-rt-latency-guest\`."
  echo "- Full matrix (pre/post + stress reference): \`scripts/task1/collect-task1-matrix-report.sh\`."
  echo "- For 30-minute stability, rebuild guest with \`rt-latency-long\` and rerun \`mixed-rt-stress-round1\`."
} > "${REPORT_MD}"

info "Wrote ${REPORT_MD}"
