#!/usr/bin/env bash
# Collect Task 1 scenario matrix samples and emit a submission-oriented comparison report.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPORT_DIR="${ROOT}/plans/task1-reports"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BARE_LOG="${REPORT_DIR}/matrix-bare-idle-${STAMP}.log"
GUEST_POST_LOG="${REPORT_DIR}/matrix-guest-idle-post-${STAMP}.log"
GUEST_PRE_LOG="${REPORT_DIR}/matrix-guest-idle-pre-${STAMP}.log"
STRESS_REF="${REPORT_DIR}/mixed-stress-round1-20260710T091425Z.md"
REPORT_MD="${REPORT_DIR}/matrix-${STAMP}.md"

mkdir -p "${REPORT_DIR}"

info() { echo "[task1] $*"; }

parse_rt_latency_lines() {
  local log_file="$1"
  grep -E 'RT_LATENCY mode=' "${log_file}" | sed 's/^.*\(RT_LATENCY mode=\)/\1/' || true
}

emit_block() {
  local label="$1"
  local log_file="$2"
  echo "### ${label}"
  echo
  echo '```'
  parse_rt_latency_lines "${log_file}"
  echo '```'
  echo
}

metric_field() {
  local log_file="$1"
  local period_ms="$2"
  local field="$3"
  parse_rt_latency_lines "${log_file}" \
    | awk -v period="${period_ms}" -v key="${field}" '
      $0 ~ ("period_ms=" period " ") {
        for (i = 1; i <= NF; i++) {
          split($i, kv, "=")
          if (kv[1] == key) {
            print kv[2]
            exit
          }
        }
      }'
}

pct_improve() {
  local before="$1"
  local after="$2"
  awk -v b="${before}" -v a="${after}" 'BEGIN {
    if (b == "" || a == "" || b == 0) {
      print "n/a"
    } else {
      printf "%.1f%%", (b - a) * 100.0 / b
    }
  }'
}

info "=== Task 1 matrix collection (${STAMP}) ==="

info "1/3 bare-metal idle..."
(
  cd "${ROOT}"
  ./scripts/task1/run-rt-baseline.sh
) 2>&1 | tee "${BARE_LOG}"

info "2/3 guest idle (post-opt, vcpu_priorities=[-20])..."
(
  cd "${ROOT}"
  ./scripts/task1/run-rt-guest-baseline.sh
) 2>&1 | tee "${GUEST_POST_LOG}"

info "3/3 guest idle (pre-opt, no vcpu_priorities)..."
(
  cd "${ROOT}"
  RT_LATENCY_FEATURES=rt-latency,rt-latency-guest \
    "${ROOT}/os/axvisor/scripts/task1/build-arceos-rt-guest.sh"
  cargo xtask axvisor test qemu --arch aarch64 -c arceos-rt-latency-guest-pre-opt
) 2>&1 | tee "${GUEST_PRE_LOG}"

{
  echo "# Task 1 Scenario Matrix Report (${STAMP})"
  echo
  echo "Generated by \`scripts/task1/collect-task1-matrix-report.sh\`."
  echo
  echo "## Scenario matrix"
  echo
  echo "| Profile | Load | RTOS placement | Status |"
  echo "|---|---|---|---|"
  echo "| bare idle | none | bare ArceOS QEMU | collected |"
  echo "| guest idle (pre-opt) | none | AxVisor VM pCPU3, no vcpu_priorities | collected |"
  echo "| guest idle (post-opt) | none | AxVisor VM pCPU3, vcpu_priorities=[-20] | collected |"
  echo "| guest + stress (post-opt) | Linux CPU stress | mixed partition | see prior long-run |"
  echo
  emit_block "Bare-metal idle (mode=bare)" "${BARE_LOG}"
  emit_block "Guest idle pre-opt (mode=guest, no vcpu_priorities)" "${GUEST_PRE_LOG}"
  emit_block "Guest idle post-opt (mode=guest, vcpu_priorities=[-20])" "${GUEST_POST_LOG}"
  echo "## Pre vs post (guest idle, P99 jitter)"
  echo
  echo "| period_ms | pre-opt P99 (ns) | post-opt P99 (ns) | improvement |"
  echo "|---:|---:|---:|---:|"
  for period in 1 10; do
    pre_p99="$(metric_field "${GUEST_PRE_LOG}" "${period}" "p99_jitter_ns")"
    post_p99="$(metric_field "${GUEST_POST_LOG}" "${period}" "p99_jitter_ns")"
    improve="$(pct_improve "${pre_p99}" "${post_p99}")"
    echo "| ${period} | ${pre_p99:-n/a} | ${post_p99:-n/a} | ${improve} |"
  done
  echo
  echo "## Notes"
  echo
  echo "- **pre-opt profile** disables only \`vcpu_priorities\`; timer passthrough / GIC / sched-cfs remain enabled."
  echo "- **stress long-run (post-opt)** reference: \`$(basename "${STRESS_REF}")\`."
  if [[ -f "${STRESS_REF}" ]]; then
    echo "- stress @ 1ms P99: 258320 ns; stress @ 10ms P99: 309648 ns (180k samples)."
  fi
  echo "- IRQ latency benchmark remains planned (§5.2 in task1-realtime.md)."
  echo
  echo "## Raw logs"
  echo
  echo "- [\`$(basename "${BARE_LOG}")\`](./$(basename "${BARE_LOG}"))"
  echo "- [\`$(basename "${GUEST_PRE_LOG}")\`](./$(basename "${GUEST_PRE_LOG}"))"
  echo "- [\`$(basename "${GUEST_POST_LOG}")\`](./$(basename "${GUEST_POST_LOG}"))"
} > "${REPORT_MD}"

info "Wrote ${REPORT_MD}"
