#!/usr/bin/env bash
# Task 1 board mixed stress: baseline vs optimized on OrangePi-5-Plus.
#
# Prerequisites:
#   1. RT guest on board: ./scripts/task1/deploy-board-rt-guest.sh <board-ip>
#   2. Linux guest + initramfs on board SD (/guest/linux/*) — existing axvisor board image
#   3. Self-hosted runner or local board lease (cargo xtask board connect)
#
# Usage:
#   CARGO_TARGET_DIR=$PWD/target ./scripts/task1/run-board-stress-baseline-vs-opt.sh
#   BOARD_IP=192.168.x.x ./scripts/task1/deploy-board-rt-guest.sh   # deploy first
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPORT_DIR="${ROOT}/plans/task1-reports"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BASELINE_CASE="board-orangepi-5-plus-mixed-rt-stress-baseline-short"
OPT_CASE="board-orangepi-5-plus-mixed-rt-stress-round1-opt-short"
BASELINE_LOG="${REPORT_DIR}/${BASELINE_CASE}-${STAMP}.log"
OPT_LOG="${REPORT_DIR}/${OPT_CASE}-${STAMP}.log"
REPORT_MD="${REPORT_DIR}/stress-board-${BASELINE_CASE}-vs-${OPT_CASE}-${STAMP}.md"

info() { echo "[task1-board] $*"; }

parse_rt_latency_lines() {
  local log_file="$1"
  grep -E 'RT_LATENCY mode=' "${log_file}" | sed 's/^.*\(RT_LATENCY mode=\)/\1/' || true
}

metric_field() {
  local log_file="$1"
  local period_ms="$2"
  local field="$3"
  parse_rt_latency_lines "${log_file}" \
    | awk -v period="${period_ms}" -v key="${field}" '
      $0 ~ ("period_ms=" period " ") {
        for (i = 1; i <= NF; i++) {
          split($i, kv, "=")
          if (kv[1] == key) {
            print kv[2]
            exit
          }
        }
      }'
}

pct_improve() {
  local before="$1"
  local after="$2"
  awk -v b="${before}" -v a="${after}" 'BEGIN {
    if (b == "" || a == "" || b == 0) {
      print "n/a"
    } else {
      printf "%.1f%%", (b - a) * 100.0 / b
    }
  }'
}

mkdir -p "${REPORT_DIR}"

info "Building board RT guest (stress-short, 18000 samples/period)..."
RT_LATENCY_FEATURES="rt-latency,rt-latency-guest,rt-latency-stress-short" \
  "${ROOT}/os/axvisor/scripts/task1/build-arceos-rt-guest-board.sh"

if [[ -z "${SKIP_DEPLOY:-}" ]]; then
  if [[ -n "${BOARD_IP:-}" ]]; then
    info "Deploying RT guest to ${BOARD_IP}..."
    "${ROOT}/scripts/task1/deploy-board-rt-guest.sh" "${BOARD_IP}"
  else
    info "BOARD_IP unset — skip deploy (set SKIP_DEPLOY=1 to silence; image must already be on board)"
  fi
fi

info "Step 1/2: board baseline (${BASELINE_CASE})..."
(
  cd "${ROOT}"
  CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-${ROOT}/target}" \
    cargo xtask axvisor test board --board orangepi-5-plus-linux -g stress -c "${BASELINE_CASE}"
) 2>&1 | tee "${BASELINE_LOG}"

if ! grep -q 'RT_LATENCY_PASS' "${BASELINE_LOG}"; then
  echo "board baseline did not report RT_LATENCY_PASS; see ${BASELINE_LOG}" >&2
  exit 1
fi

info "Step 2/2: board optimized (${OPT_CASE})..."
(
  cd "${ROOT}"
  CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-${ROOT}/target}" \
    cargo xtask axvisor test board --board orangepi-5-plus-linux -g stress -c "${OPT_CASE}"
) 2>&1 | tee "${OPT_LOG}"

if ! grep -q 'RT_LATENCY_PASS' "${OPT_LOG}"; then
  echo "board optimized did not report RT_LATENCY_PASS; see ${OPT_LOG}" >&2
  exit 1
fi

{
  echo "# Task 1 Board Stress Baseline vs Optimized (${STAMP})"
  echo
  echo "Generated by \`scripts/task1/run-board-stress-baseline-vs-opt.sh\`."
  echo
  echo "## Profiles"
  echo
  echo "| Profile | Case | VM configs |"
  echo "|---|---|---|"
  echo "| baseline | \`${BASELINE_CASE}\` | linux-smp2 + arceos-rt-smp1-baseline (emulated timer) |"
  echo "| optimized | \`${OPT_CASE}\` | linux-smp2 + arceos-rt-smp1 (timer PT, task1-rt-opt) |"
  echo
  echo "Guest: \`rt-latency-stress-short\` (18000 samples/period)."
  echo
  echo "## Baseline"
  echo
  echo '```'
  parse_rt_latency_lines "${BASELINE_LOG}"
  echo '```'
  echo
  echo "## Optimized"
  echo
  echo '```'
  parse_rt_latency_lines "${OPT_LOG}"
  echo '```'
  echo
  echo "## P99 jitter improvement (baseline → optimized)"
  echo
  echo "| period_ms | baseline P99 (ns) | optimized P99 (ns) | improvement | ≥50% |"
  echo "|---:|---:|---:|---:|:---:|"
  for period in 1 10; do
    base_p99="$(metric_field "${BASELINE_LOG}" "${period}" "p99_jitter_ns")"
    opt_p99="$(metric_field "${OPT_LOG}" "${period}" "p99_jitter_ns")"
    improve="$(pct_improve "${base_p99}" "${opt_p99}")"
    ge50="$(awk -v b="${base_p99}" -v a="${opt_p99}" 'BEGIN {
      if (b == "" || a == "" || b == 0) print "n/a";
      else if ((b - a) * 100.0 / b >= 50.0) print "✅";
      else print "❌";
    }')"
    echo "| ${period} | ${base_p99:-n/a} | ${opt_p99:-n/a} | ${improve} | ${ge50} |"
  done
  echo
  echo "## Raw logs"
  echo
  echo "- baseline: [\`$(basename "${BASELINE_LOG}")\`](./$(basename "${BASELINE_LOG}"))"
  echo "- optimized: [\`$(basename "${OPT_LOG}")\`](./$(basename "${OPT_LOG}"))"
} > "${REPORT_MD}"

info "Wrote ${REPORT_MD}"
info "=== Board stress comparison complete ==="
