#!/usr/bin/env bash
# Task 1 strong baseline long stress (180k): colocated + emulated timer vs full opt.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPORT_DIR="${ROOT}/plans/task1-reports"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
BASELINE_LOG="${REPORT_DIR}/mixed-stress-baseline-strong-long-${STAMP}.log"
OPT_LOG="${REPORT_DIR}/mixed-stress-round1-opt-long-${STAMP}.log"
REPORT_MD="${REPORT_DIR}/stress-strong-baseline-vs-opt-long-${STAMP}.md"
GUEST_FEATURES="rt-latency,rt-latency-guest,rt-latency-long"

info() { echo "[task1] $*"; }

parse_rt_latency_lines() {
  local log_file="$1"
  grep -E 'RT_LATENCY mode=' "${log_file}" | sed 's/^.*\(RT_LATENCY mode=\)/\1/' || true
}

metric_field() {
  local log_file="$1"
  local period_ms="$2"
  local field="$3"
  parse_rt_latency_lines "${log_file}" \
    | awk -v period="${period_ms}" -v key="${field}" '
      $0 ~ ("period_ms=" period " ") {
        for (i = 1; i <= NF; i++) {
          split($i, kv, "=")
          if (kv[1] == key) {
            print kv[2]
            exit
          }
        }
      }'
}

pct_improve() {
  local before="$1"
  local after="$2"
  awk -v b="${before}" -v a="${after}" 'BEGIN {
    if (b == "" || a == "" || b == 0) {
      print "n/a"
    } else {
      printf "%.1f%%", (b - a) * 100.0 / b
    }
  }'
}

mkdir -p "${REPORT_DIR}"

info "=== Task 1 strong baseline long vs opt (${STAMP}, ~70min) ==="
RT_LATENCY_FEATURES="${GUEST_FEATURES}" \
  "${ROOT}/os/axvisor/scripts/task1/build-arceos-rt-guest.sh"

info "Step 1/2: strong baseline long..."
(
  cd "${ROOT}"
  CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-${ROOT}/target}" \
    cargo xtask axvisor test qemu --arch aarch64 -g stress -c mixed-rt-stress-baseline-strong-long
) 2>&1 | tee "${BASELINE_LOG}"

if ! grep -q 'RT_LATENCY_PASS' "${BASELINE_LOG}"; then
  echo "strong baseline long did not report RT_LATENCY_PASS; see ${BASELINE_LOG}" >&2
  exit 1
fi

info "Step 2/2: optimized long..."
(
  cd "${ROOT}"
  CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-${ROOT}/target}" \
    cargo xtask axvisor test qemu --arch aarch64 -g stress -c mixed-rt-stress-round1-opt-long
) 2>&1 | tee "${OPT_LOG}"

if ! grep -q 'RT_LATENCY_PASS' "${OPT_LOG}"; then
  echo "optimized long did not report RT_LATENCY_PASS; see ${OPT_LOG}" >&2
  exit 1
fi

{
  echo "# Task 1 Strong Baseline vs Optimized — Long Run (${STAMP})"
  echo
  echo "Generated by \`scripts/task1/run-stress-strong-baseline-vs-opt-long.sh\`."
  echo
  echo "## Profiles"
  echo
  echo "| Profile | RT VM | Host | Stress |"
  echo "|---|---|---|---|"
  echo "| strong baseline | pCPU2, emulated timer, nice=19 | no sched-cfs | 8× spin |"
  echo "| optimized | pCPU3, timer PT, nice=-20 | sched-cfs + task1-rt-opt | 4× spin |"
  echo
  echo "Guest: \`${GUEST_FEATURES}\` (180000 samples / period)."
  echo
  echo "## Strong baseline"
  echo
  echo '```'
  parse_rt_latency_lines "${BASELINE_LOG}"
  echo '```'
  echo
  echo "## Optimized"
  echo
  echo '```'
  parse_rt_latency_lines "${OPT_LOG}"
  echo '```'
  echo
  echo "## P99 jitter improvement"
  echo
  echo "| period_ms | baseline P99 (ns) | optimized P99 (ns) | improvement | ≥50% |"
  echo "|---:|---:|---:|---:|:---:|"
  for period in 1 10; do
    base_p99="$(metric_field "${BASELINE_LOG}" "${period}" "p99_jitter_ns")"
    opt_p99="$(metric_field "${OPT_LOG}" "${period}" "p99_jitter_ns")"
    improve="$(pct_improve "${base_p99}" "${opt_p99}")"
    ge50="$(awk -v b="${base_p99}" -v a="${opt_p99}" 'BEGIN {
      if (b == "" || a == "" || b == 0) print "n/a";
      else if ((b - a) * 100.0 / b >= 50.0) print "✅";
      else print "❌";
    }')"
    echo "| ${period} | ${base_p99:-n/a} | ${opt_p99:-n/a} | ${improve} | ${ge50} |"
  done
  echo
  echo "## Raw logs"
  echo
  echo "- baseline: [\`$(basename "${BASELINE_LOG}")\`](./$(basename "${BASELINE_LOG}"))"
  echo "- optimized: [\`$(basename "${OPT_LOG}")\`](./$(basename "${OPT_LOG}"))"
} > "${REPORT_MD}"

info "Wrote ${REPORT_MD}"
info "=== Strong baseline long comparison complete ==="
