#!/usr/bin/env bash
# Task 1 round-1 long-run: mixed Linux+RT partition under CPU stress, archive report.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
AXVISOR_ROOT="${ROOT}/os/axvisor"
REPORT_DIR="${ROOT}/plans/task1-reports"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
STRESS_LOG="${REPORT_DIR}/mixed-stress-round1-${STAMP}.log"
REPORT_MD="${REPORT_DIR}/mixed-stress-round1-${STAMP}.md"
IDLE_COMPARE=""

info() { echo "[task1] $*"; }

parse_rt_latency_lines() {
  local log_file="$1"
  grep -E 'RT_LATENCY mode=' "${log_file}" | sed 's/^.*\(RT_LATENCY mode=\)/\1/' || true
}

mkdir -p "${REPORT_DIR}"

info "=== Task 1 round-1: idle baseline + mixed stress long-run ==="

info "Step 1/4: collect bare-metal vs guest idle comparison..."
(
  cd "${ROOT}"
  ./scripts/task1/collect-rt-latency-report.sh
) 2>&1 | tee "${REPORT_DIR}/idle-collect-${STAMP}.log"
IDLE_COMPARE="$(ls -1t "${REPORT_DIR}"/compare-*.md 2>/dev/null | head -1 || true)"

info "Step 2/4: build rt-latency-long guest image..."
RT_LATENCY_FEATURES=rt-latency,rt-latency-guest,rt-latency-long \
  "${AXVISOR_ROOT}/scripts/task1/build-arceos-rt-guest.sh"

info "Step 3/4: mixed partition stress long-run (~35 min, timeout 2400s)..."
(
  cd "${ROOT}"
  cargo xtask axvisor test qemu \
    --arch aarch64 \
    --test-group stress \
    -c mixed-rt-stress-round1
) 2>&1 | tee "${STRESS_LOG}"

info "Step 4/4: write report ${REPORT_MD}"
{
  echo "# Task 1 Mixed Stress Round 1 (${STAMP})"
  echo
  echo "Generated by \`scripts/task1/run-mixed-stress-round1.sh\`."
  echo
  echo "## Topology"
  echo
  echo "- pCPU0: AxVisor host"
  echo "- pCPU1-2: Linux 2vCPU (\`linux-smp2.toml\`, nice=10)"
  echo "- pCPU3: RT ArceOS (\`arceos-rt-smp1.toml\`, nice=-20, \`rt-latency-long\`)"
  echo
  echo "## Linux stress"
  echo
  echo "4 CPU-bound background loops (Alpine rootfs has no \`stress-ng\`; equivalent to \`stress-ng --cpu 2 --fork 4\`)."
  echo
  if [[ -n "${IDLE_COMPARE}" && -f "${IDLE_COMPARE}" ]]; then
    echo "## Idle baseline (short samples)"
    echo
    echo "See [\`$(basename "${IDLE_COMPARE}")\`](./$(basename "${IDLE_COMPARE}"))."
    echo
  fi
  echo "## Mixed stress RT latency (long samples)"
  echo
  echo '```'
  parse_rt_latency_lines "${STRESS_LOG}"
  echo '```'
  echo
  if grep -q 'RT_LATENCY_PASS' "${STRESS_LOG}"; then
    echo "**Result**: PASS (\`RT_LATENCY_PASS\` observed)"
  else
    echo "**Result**: FAIL (no \`RT_LATENCY_PASS\` in log)"
  fi
  echo
  echo "## Raw log"
  echo
  echo "- [\`$(basename "${STRESS_LOG}")\`](./$(basename "${STRESS_LOG}"))"
} > "${REPORT_MD}"

info "Wrote ${REPORT_MD}"
info "=== Round 1 complete ==="
