#!/usr/bin/env bash
# Pre-opt mixed stress long-run (~35min) + pre/post stress comparison report.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPORT_DIR="${ROOT}/plans/task1-reports"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
STRESS_PRE_LOG="${REPORT_DIR}/mixed-stress-pre-opt-${STAMP}.log"
STRESS_POST_REF="${REPORT_DIR}/mixed-stress-round1-20260710T091425Z.md"
REPORT_MD="${REPORT_DIR}/stress-pre-post-${STAMP}.md"

mkdir -p "${REPORT_DIR}"

info() { echo "[task1] $*"; }

parse_rt_latency_lines() {
  local log_file="$1"
  grep -E 'RT_LATENCY mode=' "${log_file}" | sed 's/^.*\(RT_LATENCY mode=\)/\1/' || true
}

metric_field() {
  local log_file="$1"
  local period_ms="$2"
  local field="$3"
  parse_rt_latency_lines "${log_file}" \
    | awk -v period="${period_ms}" -v key="${field}" '
      $0 ~ ("period_ms=" period " ") {
        for (i = 1; i <= NF; i++) {
          split($i, kv, "=")
          if (kv[1] == key) {
            print kv[2]
            exit
          }
        }
      }'
}

pct_improve() {
  local before="$1"
  local after="$2"
  awk -v b="${before}" -v a="${after}" 'BEGIN {
    if (b == "" || a == "" || b == 0) {
      print "n/a"
    } else {
      printf "%.1f%%", (b - a) * 100.0 / b
    }
  }'
}

info "=== Task 1 pre-opt mixed stress long-run (${STAMP}) ==="
info "Building rt-latency-long guest..."
RT_LATENCY_FEATURES=rt-latency,rt-latency-guest,rt-latency-long \
  "${ROOT}/os/axvisor/scripts/task1/build-arceos-rt-guest.sh"

info "Running mixed stress (pre-opt RT VM, timeout 2400s, ~35min)..."
(
  cd "${ROOT}"
  cargo xtask axvisor test qemu --arch aarch64 -g stress -c mixed-rt-stress-round1-pre-opt
) 2>&1 | tee "${STRESS_PRE_LOG}"

if ! grep -q 'RT_LATENCY_PASS' "${STRESS_PRE_LOG}"; then
  echo "pre-opt stress run did not report RT_LATENCY_PASS; see ${STRESS_PRE_LOG}" >&2
  exit 1
fi

POST_LOG="${REPORT_DIR}/mixed-stress-round1-20260710T091425Z.log"
if [[ ! -f "${POST_LOG}" ]]; then
  echo "post-opt stress log missing: ${POST_LOG}" >&2
  exit 1
fi

{
  echo "# Task 1 Stress Pre vs Post Comparison (${STAMP})"
  echo
  echo "Generated by \`scripts/task1/run-mixed-stress-pre-opt-round1.sh\`."
  echo
  echo "## Topology"
  echo
  echo "| Profile | Linux | RT guest |"
  echo "|---|---|---|"
  echo "| pre-opt | linux-smp2 (nice=10) | arceos-rt-smp1-pre-opt (no vcpu_priorities) |"
  echo "| post-opt | linux-smp2 (nice=10) | arceos-rt-smp1 (vcpu_priorities=[-20]) |"
  echo
  echo "## Stress RT latency (180000 samples / period)"
  echo
  echo "### pre-opt (this run)"
  echo
  echo '```'
  parse_rt_latency_lines "${STRESS_PRE_LOG}"
  echo '```'
  echo
  echo "### post-opt (reference: mixed-stress-round1-20260710T091425Z)"
  echo
  echo '```'
  parse_rt_latency_lines "${POST_LOG}"
  echo '```'
  echo
  echo "## P99 jitter improvement (pre → post, lower is better)"
  echo
  echo "| period_ms | pre-opt P99 (ns) | post-opt P99 (ns) | improvement |"
  echo "|---:|---:|---:|---:|"
  for period in 1 10; do
    pre_p99="$(metric_field "${STRESS_PRE_LOG}" "${period}" "p99_jitter_ns")"
    post_p99="$(metric_field "${POST_LOG}" "${period}" "p99_jitter_ns")"
    improve="$(pct_improve "${pre_p99}" "${post_p99}")"
    echo "| ${period} | ${pre_p99:-n/a} | ${post_p99:-n/a} | ${improve} |"
  done
  echo
  echo "## P999 jitter improvement"
  echo
  echo "| period_ms | pre-opt P999 (ns) | post-opt P999 (ns) | improvement |"
  echo "|---:|---:|---:|---:|"
  for period in 1 10; do
    pre_p999="$(metric_field "${STRESS_PRE_LOG}" "${period}" "p999_jitter_ns")"
    post_p999="$(metric_field "${POST_LOG}" "${period}" "p999_jitter_ns")"
    improve="$(pct_improve "${pre_p999}" "${post_p999}")"
    echo "| ${period} | ${pre_p999:-n/a} | ${post_p999:-n/a} | ${improve} |"
  done
  echo
  echo "## Raw logs"
  echo
  echo "- pre-opt: [\`$(basename "${STRESS_PRE_LOG}")\`](./$(basename "${STRESS_PRE_LOG}"))"
  echo "- post-opt: [\`$(basename "${POST_LOG}")\`](./$(basename "${POST_LOG}"))"
} > "${REPORT_MD}"

info "Wrote ${REPORT_MD}"
