cmake_minimum_required(VERSION 3.20)
project(test-mm-lifecycle C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
add_executable(test-mm-lifecycle src/main.c)
target_compile_options(test-mm-lifecycle PRIVATE -Wall -Wextra -Werror)
install(TARGETS test-mm-lifecycle RUNTIME DESTINATION usr/bin/starry-test-suit)
