/* Generated by materialize_syscall_batch.py */
#define _GNU_SOURCE
#include <errno.h>
#include <stdio.h>
#include <fcntl.h>

int main(void)
{
	errno = 0;
	int r = fallocate(-1, 0, 0, 0);
	int e = errno;
	dprintf(1, "CASE fallocate.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

