/* Generated by materialize_syscall_batch.py */
#define _GNU_SOURCE
#include <errno.h>
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>

int main(void)
{
	errno = 0;
	ssize_t r = splice(0, NULL, -1, NULL, 1, 0);
	int e = errno;
	dprintf(1, "CASE splice.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

