// infer_llamacpp - deterministic greedy-decode correctness carpet for the llama.cpp
// (ggml) CPU inference stack on StarryOS. For each committed prompt it greedy-decodes
// its model (temperature=0, pure argmax sampler, n_gpu_layers=0) and asserts the generated
// token IDs equal a committed golden reference token-by-token. Greedy decode is fully
// deterministic for a fixed build, so the golden is reproducible; any divergence means a ggml
// CPU kernel produced a different argmax, i.e. a numerical bug in the inference stack.
//
// The golden is per-arch: argmax ties break differently across ISAs (x86_64 SSE2 / aarch64
// NEON+FMA / riscv64+loongarch64 scalar round FMA differently), so each arch has its own golden,
// generated by this exact build via `-e` emit mode (below) and byte-reproducible on-target.
//
// Three-gate: for every prompt, the first-token argmax must match, every generated token
// ID must match, and the generated count must equal the golden count. "INFER_LLAMACPP OK
// <n>" (n = total tokens verified across all prompts) is printed only when every gate of
// every prompt passes; otherwise the mismatch is reported and the process exits non-zero.
//
// This is NOT a smoke test: "model loaded" alone fails the gate. Correctness is decided by
// exact token-ID equality against the golden, not by any load/print side effect.
#include "llama.h"
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <string>
#include <vector>

namespace {

struct Golden {
    std::string prompt;
    int n_predict = 0;
    int argmax0 = 0;                 // first generated token (greedy argmax of the prompt)
    std::vector<int> tokens;         // full generated sequence (length == n_predict unless EOG)
    bool eog = false;                // golden ended on end-of-generation before n_predict
};

// Golden file grammar (one prompt per file), lines:
//   PROMPT <text...>            (rest of line, verbatim, is the prompt)
//   NPREDICT <int>
//   ARGMAX0 <int>
//   GEN <int> <int> ...         (space separated generated token IDs; may span; here single line)
//   EOG                         (optional: golden stopped on end-of-generation)
bool load_golden(const char * path, Golden & g) {
    FILE * f = std::fopen(path, "r");
    if (!f) { std::fprintf(stderr, "golden: cannot open %s\n", path); return false; }
    char * line = nullptr; size_t cap = 0; ssize_t n;
    while ((n = getline(&line, &cap, f)) != -1) {
        while (n > 0 && (line[n-1] == '\n' || line[n-1] == '\r')) line[--n] = '\0';
        if (!std::strncmp(line, "PROMPT ", 7))        g.prompt = line + 7;
        else if (!std::strncmp(line, "NPREDICT ", 9)) g.n_predict = std::atoi(line + 9);
        else if (!std::strncmp(line, "ARGMAX0 ", 8))  g.argmax0 = std::atoi(line + 8);
        else if (!std::strncmp(line, "EOG", 3))       g.eog = true;
        else if (!std::strncmp(line, "GEN ", 4)) {
            char * p = line + 4;
            while (*p) {
                while (*p == ' ') p++;
                if (!*p) break;
                g.tokens.push_back((int) std::strtol(p, &p, 10));
            }
        }
    }
    std::free(line);
    std::fclose(f);
    if (g.prompt.empty() || g.n_predict <= 0 || g.tokens.empty()) {
        std::fprintf(stderr, "golden: %s incomplete (prompt/n_predict/tokens)\n", path);
        return false;
    }
    return true;
}

// Greedy-decode `g.prompt` for g.n_predict tokens on pure CPU, filling `out` with the
// generated token IDs and `argmax0` with the first one. Returns false on any llama.cpp
// failure. Deterministic: greedy sampler, n_gpu_layers=0, single thread.
bool greedy_decode(llama_model * model, const Golden & g,
                   std::vector<int> & out, int & argmax0, bool & eog) {
    const llama_vocab * vocab = llama_model_get_vocab(model);
    const int n_prompt = -llama_tokenize(vocab, g.prompt.c_str(), (int) g.prompt.size(),
                                         nullptr, 0, true, true);
    if (n_prompt <= 0) { std::fprintf(stderr, "decode: tokenize count failed\n"); return false; }
    std::vector<llama_token> ptoks(n_prompt);
    if (llama_tokenize(vocab, g.prompt.c_str(), (int) g.prompt.size(),
                       ptoks.data(), (int) ptoks.size(), true, true) < 0) {
        std::fprintf(stderr, "decode: tokenize failed\n"); return false;
    }

    llama_context_params cp = llama_context_default_params();
    cp.n_ctx           = n_prompt + g.n_predict;
    cp.n_batch         = n_prompt + g.n_predict;
    cp.n_threads       = 1;
    cp.n_threads_batch = 1;
    cp.no_perf         = true;
    llama_context * ctx = llama_init_from_model(model, cp);
    if (!ctx) { std::fprintf(stderr, "decode: ctx init failed\n"); return false; }

    auto sp = llama_sampler_chain_default_params();
    sp.no_perf = true;
    llama_sampler * smpl = llama_sampler_chain_init(sp);
    llama_sampler_chain_add(smpl, llama_sampler_init_greedy());

    out.clear();
    eog = false;
    argmax0 = -1;
    llama_batch batch = llama_batch_get_one(ptoks.data(), (int) ptoks.size());
    bool ok = true;
    for (int n_pos = 0; n_pos + batch.n_tokens < n_prompt + g.n_predict; ) {
        if (llama_decode(ctx, batch)) { std::fprintf(stderr, "decode: llama_decode failed\n"); ok = false; break; }
        n_pos += batch.n_tokens;
        llama_token id = llama_sampler_sample(smpl, ctx, -1);
        if (argmax0 < 0) argmax0 = id;
        if (llama_vocab_is_eog(vocab, id)) { eog = true; break; }
        out.push_back(id);
        batch = llama_batch_get_one(&id, 1);
    }

    llama_sampler_free(smpl);
    llama_free(ctx);
    return ok;
}

} // namespace

int main(int argc, char ** argv) {
    std::string model_path;
    std::vector<std::string> goldens;
    bool emit = false; // -e: (re)generate mode - print this build's golden + decoded text instead of gating
    for (int i = 1; i < argc; i++) {
        if (!std::strcmp(argv[i], "-m") && i + 1 < argc) model_path = argv[++i];
        else if (!std::strcmp(argv[i], "-g") && i + 1 < argc) goldens.emplace_back(argv[++i]);
        else if (!std::strcmp(argv[i], "-e")) emit = true;
    }
    if (model_path.empty() || goldens.empty()) {
        std::fprintf(stderr, "usage: %s -m model.gguf -g golden1 [-g golden2 ...]\n", argv[0]);
        return 2;
    }

    ggml_backend_load_all();
    llama_model_params mp = llama_model_default_params();
    mp.n_gpu_layers = 0; // pure CPU: ggml CPU kernels only
    llama_model * model = llama_model_load_from_file(model_path.c_str(), mp);
    if (!model) { std::fprintf(stderr, "INFER_LLAMACPP FAIL: cannot load model %s\n", model_path.c_str()); return 1; }

    int total_verified = 0;
    bool all_ok = true;
    for (const auto & gp : goldens) {
        Golden g;
        if (!load_golden(gp.c_str(), g)) { all_ok = false; break; }

        std::vector<int> got; int argmax0 = -1; bool eog = false;
        if (!greedy_decode(model, g, got, argmax0, eog)) {
            std::fprintf(stderr, "INFER_LLAMACPP FAIL: decode error on %s\n", gp.c_str());
            all_ok = false; break;
        }

        if (emit) {
            // Regeneration mode: emit this build/arch's golden (same prompt + n_predict, this build's
            // generated token IDs) on stdout, and the decoded text on stderr so the tokens can be
            // cross-checked for coherence (does this arch produce the same answer text?) before commit.
            const llama_vocab * vocab = llama_model_get_vocab(model);
            std::printf("PROMPT %s\nNPREDICT %d\nARGMAX0 %d\nGEN", g.prompt.c_str(), g.n_predict, argmax0);
            for (int id : got) std::printf(" %d", id);
            std::printf("\n");
            if (eog) std::printf("EOG\n");
            std::string text;
            for (int id : got) {
                char buf[256];
                int n = llama_token_to_piece(vocab, id, buf, (int) sizeof buf, 0, true);
                if (n > 0) text.append(buf, (size_t) n);
            }
            std::fprintf(stderr, "EMIT-TEXT[%s]: %s\n", gp.c_str(), text.c_str());
            continue;
        }
        // gate 1: first-token argmax
        if (argmax0 != g.argmax0) {
            std::fprintf(stderr, "INFER_LLAMACPP FAIL[%s]: argmax0 got %d want %d\n",
                         gp.c_str(), argmax0, g.argmax0);
            all_ok = false; break;
        }
        // gate 2: count equals golden count (and golden EOG state matches)
        if ((int) got.size() != (int) g.tokens.size() || eog != g.eog) {
            std::fprintf(stderr, "INFER_LLAMACPP FAIL[%s]: count got %d(eog=%d) want %d(eog=%d)\n",
                         gp.c_str(), (int) got.size(), (int) eog,
                         (int) g.tokens.size(), (int) g.eog);
            all_ok = false; break;
        }
        // gate 3: every token ID matches
        for (size_t i = 0; i < got.size(); i++) {
            if (got[i] != g.tokens[i]) {
                std::fprintf(stderr, "INFER_LLAMACPP FAIL[%s]: token[%zu] got %d want %d\n",
                             gp.c_str(), i, got[i], g.tokens[i]);
                all_ok = false; break;
            }
        }
        if (!all_ok) break;

        std::printf("INFER_LLAMACPP prompt=\"%s\" argmax0=%d tokens=%d MATCH\n",
                    g.prompt.c_str(), argmax0, (int) got.size());
        total_verified += (int) got.size();
    }

    llama_model_free(model);

    if (emit) return all_ok ? 0 : 1; // regeneration mode: no gate, success == decoded every prompt
    if (all_ok && total_verified > 0) {
        std::printf("INFER_LLAMACPP OK %d\n", total_verified);
        return 0;
    }
    std::printf("INFER_LLAMACPP FAILED\n");
    return 1;
}
