target = "aarch64-unknown-none-softfloat"
log = "Info"
max_cpu_num = 4
features = [
  "ax-runtime/display",
  "ax-runtime/rtc",
  "ax-driver/serial",
  "ax-driver/nvme",
  "ax-driver/virtio-net",
  "ax-driver/virtio-gpu",
  "ax-driver/virtio-input",
  "ax-driver/virtio-socket",
  "starry-kernel/input",
  "starry-kernel/vsock",
]
