board_type = "OrangePi-5-Plus"
fail_regex = [
  "(?i)\\bpanic(?:ked)?\\b",
  "Failed to initialize guest VM",
]
shell_init_cmd = "pwd && echo 'starry host amp test pass'"
shell_prefix = "root@starry:/root #"
success_regex = [
  "(?m)^starry host amp test pass\\s*$",
]
timeout = 600
