[package]
name = "axvm"
authors = ["aarkegz <aarkegz@gmail.com>"]
version = "0.5.25"
edition.workspace = true
categories = ["virtualization"]
description = "Virtual Machine resource management crate for ArceOS's hypervisor variant."
repository = "https://github.com/arceos-hypervisor/axvm"
keywords = ["vm", "hypervisor", "arceos"]
license = "Apache-2.0"

[features]
fs = ["ax-std/fs"]
host-fs = ["ax-std/fs", "dep:ax-driver"]
host-test = [
    "ax-std/host-test",
    "axdevice/host-test",
]
sstc = ["riscv_vcpu/sstc"]
tls = ["ax-std/tls", "cpu-local/tls"]

[dependencies]
log = "0.4"
extern-trait = { workspace = true }
bit_field = "0.10"
bitflags = "2.9"
byte-unit = { version = "5", default-features = false, features = ["byte"] }
numeric-enum-macro = "0.2"
thiserror = { workspace = true }
acpi_tables = { workspace = true }
serde = { version = "1.0.204", default-features = false, features = ["derive"] }

# System independent crates provided by ArceOS.
ax-cpumask = { workspace = true }
ax-crate-interface = { workspace = true }
ax-memory-addr = { workspace = true }
ax-memory-set = { workspace = true }
cpu-local.workspace = true
page-table-generic = { workspace = true }
ax-std = { workspace = true, default-features = false, features = [
    "paging",
    "irq",
    "multitask",
    "task-ext",
    "smp",
    "hv",
    "ipi",
] }
ax-timer-list = { workspace = true }
irq-framework = { workspace = true }
# System dependent modules provided by ArceOS-Hypervisor.
axaddrspace = { workspace = true }
axvm-types = { workspace = true }
axhvc = { workspace = true }
axdevice = { workspace = true }
axdevice_base = { workspace = true }
axvmconfig = { workspace = true, default-features = false }
fdt-edit = { workspace = true }
fdt-raw = { workspace = true }
[target.'cfg(target_arch = "x86_64")'.dependencies]
ax-driver = { workspace = true, optional = true, features = ["pci"] }
x86 = "0.52"
x86_vcpu = { workspace = true }
x86_vlapic = { workspace = true }
[target.'cfg(target_arch = "riscv64")'.dependencies]
ax-plat = { workspace = true }
riscv_vcpu = { workspace = true }
riscv_vplic = { workspace = true }
[target.'cfg(target_arch = "loongarch64")'.dependencies]
ax-plat = { workspace = true }
loongarch_vcpu = { workspace = true }
[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu-ext = "0.1"
arm_vcpu = { workspace = true }
arm_vgic = { workspace = true }
arm-gic-driver = { workspace = true, features = ["rdif"] }
axklib.workspace = true
mmio-api.workspace = true
rdif-intc.workspace = true
rdrive.workspace = true
rdif-clk.workspace = true

[dev-dependencies]
rdif-clk.workspace = true
