# AxVM machine policy.
[machine]
mode = "passthrough"
firmware = "auto"
interrupts_passthrough = true

[base]
id = 1
name = "arceos-qemu"
cpu_num = 1
phys_cpu_ids = [0x0]

[kernel]
entry_point = 0x200040
image_location = "memory"
kernel_path = "/path/to/arceos-helloworld.bin"
kernel_load_addr = 0x200000

[[memory.regions]]
guest_base = 0x0
size = 0x2000000
permissions = "rwx"
backing = { kind = "allocate" }

[devices]
disable_defaults = []
deny = []
