[package]
name = "ax-display"
version = "0.7.0"
repository = "https://github.com/rcore-os/tgoskits"
edition.workspace = true
authors = ["Shiping Yuan <robert_yuan@pku.edu.com>"]
description = "ArceOS screen output access"
license.workspace = true

[features]
host-test = ["ax-gpu/host-test"]

[dependencies]
ax-gpu.workspace = true
