# AxVM machine policy.
[machine]
mode = "passthrough"
firmware = "auto"
interrupts_passthrough = true

[base]
id = 1
name = "arceos"
cpu_num = 1
phys_cpu_ids = [0x0]

[kernel]
entry_point = 0x2030080000
image_location = "memory"
kernel_load_addr = 0x2030080000
kernel_path = "path/rdk-s100/Image"
dtb_load_addr = 0x2030000000

[[memory.regions]]
guest_base = 0x2030000000
size = 0x10000000
permissions = "rwx"
backing = { kind = "host", host_base = 0x2030000000 }

[devices]
disable_defaults = []
deny = []
