args = [
    "-machine",
    "q35",
    "-nographic",
    "-m",
    "8192",
    "-device",
    "virtio-blk-pci,drive=disk0",
    "-drive",
    "id=disk0,if=none,format=raw,file=${workspace}/tmp/axbuild/rootfs/rootfs-x86_64-alpine.img",
    "-device",
    "virtio-net-pci,netdev=net0",
    "-netdev",
    "user,id=net0",
]
uefi = false
to_bin = false
shell_prefix = "root@starry:"
shell_init_cmd = "/usr/bin/starry-test-suit/strace-nixpkgs.sh"
success_regex = [
    "(?m)^NIX_STRACE_PASSED\\s*$",
]
fail_regex = [
    '(?i)\bpanic(?:ked)?\b',
    '(?i)\bfatal\b',
    "(?m)^NIX_STRACE_ERROR:",
]
timeout = 1800
