args = [
  "-machine", "virt",
  "-cpu", "la464",
  "-m", "2G",
  "-smp", "1",
  "-nographic",
  "-device", "nvme,drive=disk0,serial=tgoskits,max_ioqpairs=64,msix_qsize=65",
  "-drive", "id=disk0,if=none,format=raw,file=${workspace}/tmp/axbuild/rootfs/arceos-loongarch64-fat32.img",
  "-device", "virtio-net-pci,netdev=net0",
  "-netdev", "user,id=net0",
  "-serial", "mon:stdio",
]
uefi = true
to_bin = true
success_regex = []
fail_regex = ["(?i)\\bpanic(?:ked)?\\b"]
