# Build-time config template for StarryOS on Orange Pi 5 Plus.
target = "aarch64-unknown-none-softfloat"
# Runtime U-Boot settings live in `orangepi-5-plus-uboot.toml`.
env = {}
features = [
  "ax-hal/plat-dyn",
  "starry-kernel/plat-dyn",
  "ax-drivers/pci-list-devices",
  "ax-drivers/realtek-rtl8125",
  "ax-drivers/rockchip-soc",
  "ax-drivers/rockchip-dwc-xhci",
  "ax-drivers/rockchip-sdhci",
  "ax-drivers/rockchip-dwmmc",
  "rknpu",
]
log = "Info"
max_cpu_num = 8
plat_dyn = true
