[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "axloader"
publish = false
repository.workspace = true
version = "0.1.0"

[[bin]]
name = "axloader"
path = "src/main.rs"

[dependencies]
httpboot-protocol = { workspace = true }
sha2 = { version = "0.10", default-features = false }

[target.'cfg(any(windows, unix))'.dependencies]
anyhow = { workspace = true }
object = "0.38"

[target.'cfg(target_os = "uefi")'.dependencies]
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
uefi = { workspace = true, features = ["alloc", "global_allocator"] }
uefi-raw = "0.14.0"
