#!/usr/bin/env bash
set -euo pipefail

# Build the network-free Zephyr periodic latency sampler at the RT partition's
# identity-mapped guest address and stage a raw image plus reproducibility data.

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
zephyr_base="${ZEPHYR_BASE:-/tmp/zephyrproject}"
cross_prefix="${CROSS_COMPILE:-$HOME/.local/toolchains/aarch64-linux-musl-cross/bin/aarch64-linux-musl-}"
app_dir="${repo_root}/scripts/test/zephyr-periodic"
out_dir="${OUT_DIR:-${repo_root}/tmp/rt-partition}"
build_dir="${BUILD_DIR:-${out_dir}/zephyr-periodic-build}"
memory_base="${ZEPHYR_MEMORY_BASE:-0xA0000000}"
memory_size="${ZEPHYR_MEMORY_SIZE:-0x08000000}"
start_gated="${ZEPHYR_START_GATED:-1}"
dump_gated="${ZEPHYR_DUMP_GATED:-0}"
start_delay_ms="${ZEPHYR_START_DELAY_MS:-0}"
sample_count="${ZEPHYR_SAMPLE_COUNT:-300}"
extra_overlay="${ZEPHYR_EXTRA_OVERLAY:-}"
out_dir="$(realpath -m "$out_dir")"
build_dir="$(realpath -m "$build_dir")"

for path in "$zephyr_base" "$app_dir" "${cross_prefix}gcc"; do
    [[ -e "$path" ]] || { printf 'error: missing Zephyr build input: %s\n' "$path" >&2; exit 1; }
done
[[ "$memory_base" =~ ^0x[0-9a-fA-F]+$ && "$memory_size" =~ ^0x[0-9a-fA-F]+$ ]] || {
    printf 'error: Zephyr memory base and size must be hexadecimal\n' >&2
    exit 2
}
[[ "$start_gated" == "0" || "$start_gated" == "1" ]] || {
    printf 'error: ZEPHYR_START_GATED must be 0 or 1\n' >&2
    exit 2
}
[[ "$dump_gated" == "0" || "$dump_gated" == "1" ]] || {
    printf 'error: ZEPHYR_DUMP_GATED must be 0 or 1\n' >&2
    exit 2
}
[[ "$dump_gated" == "0" || "$start_gated" == "1" ]] || {
    printf 'error: ZEPHYR_DUMP_GATED=1 requires ZEPHYR_START_GATED=1\n' >&2
    exit 2
}
[[ "$start_delay_ms" =~ ^[0-9]+$ ]] || {
    printf 'error: ZEPHYR_START_DELAY_MS must be a non-negative integer\n' >&2
    exit 2
}
[[ "$sample_count" =~ ^[1-9][0-9]*$ ]] || {
    printf 'error: ZEPHYR_SAMPLE_COUNT must be a positive integer\n' >&2
    exit 2
}

mkdir -p "$out_dir"
overlay="${out_dir}/zephyr-periodic-memory.overlay"
printf '/* Generated by build-zephyr-periodic.sh. */\n&sram0 {\n\treg = <0x0 %s 0x0 %s>;\n};\n' \
    "$memory_base" "$memory_size" > "$overlay"
overlay_files=("$overlay")
if [[ -n "$extra_overlay" ]]; then
    [[ -f "$extra_overlay" ]] || {
        printf 'error: Zephyr extra overlay does not exist: %s\n' "$extra_overlay" >&2
        exit 1
    }
    overlay_files+=("$(realpath "$extra_overlay")")
fi
overlay_list="$(IFS=";"; printf "%s" "${overlay_files[*]}")"

ZEPHYR_BASE="$zephyr_base" cmake -S "$app_dir" -B "$build_dir" -G Ninja \
    -DBOARD=qemu_cortex_a53 \
    -DZEPHYR_TOOLCHAIN_VARIANT=cross-compile \
    -DCROSS_COMPILE="$cross_prefix" \
    -DRT_START_GATED="$start_gated" \
    -DRT_DUMP_GATED="$dump_gated" \
    -DRT_START_DELAY_MS="$start_delay_ms" \
    -DRT_SAMPLE_COUNT="$sample_count" \
    -DDTC_OVERLAY_FILE="$overlay_list"
cmake --build "$build_dir" --clean-first

elf="${build_dir}/zephyr/zephyr.elf"
source_bin="${build_dir}/zephyr/zephyr.bin"
staged_elf="${out_dir}/zephyr-periodic.elf"
staged_bin="${out_dir}/zephyr-periodic.bin"
manifest="${out_dir}/zephyr-periodic.manifest"
for path in "$elf" "$source_bin"; do
    [[ -f "$path" ]] || { printf 'error: Zephyr build did not produce %s\n' "$path" >&2; exit 1; }
done

cp "$elf" "$staged_elf"
cp "$source_bin" "$staged_bin"
entry_point="$("${cross_prefix}readelf" -hW "$staged_elf" | awk '/Entry point address:/ {print $4}')"
linked_base="$("${cross_prefix}readelf" -lW "$staged_elf" | awk '$1 == "LOAD" {print $3; exit}')"
[[ -n "$entry_point" && -n "$linked_base" ]] || {
    printf 'error: failed to inspect Zephyr ELF layout\n' >&2
    exit 1
}
(( linked_base == memory_base )) || {
    printf 'error: Zephyr linked base %s does not match requested %s\n' "$linked_base" "$memory_base" >&2
    exit 1
}
rg -a -F "PERIODIC LATENCY COMPLETE samples=%d" "$staged_bin" >/dev/null || {
    printf 'error: staged image does not contain the periodic completion marker\n' >&2
    exit 1
}

{
    printf 'entry_point=%s\n' "$entry_point"
    printf 'linked_base=%s\n' "$linked_base"
    printf 'zephyr_commit=%s\n' "$(git -C "$zephyr_base" rev-parse HEAD)"
    printf 'source_commit=%s\n' "$(git -C "$repo_root" rev-parse HEAD)"
    printf 'board=qemu_cortex_a53\n'
    printf 'sample_count=%s\n' "$sample_count"
    printf 'start_gated=%s\n' "$start_gated"
    printf 'dump_gated=%s\n' "$dump_gated"
    printf 'start_delay_ms=%s\n' "$start_delay_ms"
    printf 'extra_overlay=%s\n' "${extra_overlay:-none}"
    if [[ -n "$extra_overlay" ]]; then
        printf 'extra_overlay_sha256=%s\n' "$(sha256sum "$extra_overlay" | awk '{print $1}')"
    fi
    printf 'toolchain=%s\n' "$("${cross_prefix}gcc" -dumpfullversion)"
    printf 'sha256=%s\n' "$(sha256sum "$staged_bin" | awk '{print $1}')"
} > "$manifest"

printf 'zephyr_periodic=%s entry=%s sha256=%s\n' \
    "$staged_bin" "$entry_point" "$(sha256sum "$staged_bin" | awk '{print $1}')"
