#!/usr/bin/env python3
"""Derive conservative per-scenario TCG runtime scales from progress data."""

import argparse
import math
from pathlib import Path


def read_progress(path: Path) -> dict[str, float]:
    values: dict[str, float] = {}
    for line in path.read_text().splitlines():
        if "=" not in line:
            continue
        name, value = line.split("=", 1)
        try:
            values[name] = float(value)
        except ValueError:
            continue
    return values


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("scenario_progress", nargs="+", metavar="SCENARIO=PROGRESS.txt")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--safety-margin", type=float, default=1.25)
    parser.add_argument("--minimum-guest-seconds", type=float, default=108.0)
    args = parser.parse_args()

    if args.safety_margin < 1.0:
        raise SystemExit("error: safety margin must be at least 1.0")
    if args.minimum_guest_seconds <= 0:
        raise SystemExit("error: minimum guest seconds must be positive")

    output_lines = [
        "# Generated by calibrate-runtime-scale.py",
        f"# safety_margin={args.safety_margin}",
        f"# minimum_guest_seconds={args.minimum_guest_seconds}",
    ]
    seen: set[str] = set()
    for item in args.scenario_progress:
        if "=" not in item:
            raise SystemExit(f"error: invalid scenario progress argument: {item}")
        scenario, raw_path = item.split("=", 1)
        if not scenario or scenario in seen:
            raise SystemExit(f"error: duplicate or empty scenario: {scenario}")
        seen.add(scenario)
        path = Path(raw_path)
        values = read_progress(path)
        guest_elapsed = values.get("guest_elapsed_s", 0.0)
        host_elapsed = values.get("host_elapsed_s", 0.0)
        if guest_elapsed < args.minimum_guest_seconds:
            raise SystemExit(
                f"error: {scenario} calibration is too short: "
                f"{guest_elapsed:.6f} guest seconds < {args.minimum_guest_seconds:.6f}"
            )
        if host_elapsed <= 0:
            raise SystemExit(f"error: {scenario} calibration has no positive host interval")
        observed_scale = host_elapsed / guest_elapsed
        scale = max(1, math.ceil(observed_scale * args.safety_margin))
        output_lines.append(
            f"# {scenario}: host_s={host_elapsed:.6f} guest_s={guest_elapsed:.6f} "
            f"observed_scale={observed_scale:.6f}"
        )
        output_lines.append(f"{scenario}={scale}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(output_lines) + "\n")


if __name__ == "__main__":
    main()
