env = { AX_IP = "10.0.2.15", AX_GW = "10.0.2.2" }
features = [
    "ax-hal/x86-asus-nuc15crh",
    "ax-driver/virtio-blk",
    "ax-driver/plat-static",
    "ept-level-4",
    "fs",
]
log = "Info"
target = "x86_64-unknown-none"
vm_configs = ["os/axvisor/configs/vms/nimbos-x86_64-asus-nuc15crh-smp1.toml"]
