features = [
  "ax-driver/nvme",

]
log = "Info"
max_cpu_num = 1
target = "loongarch64-unknown-none-softfloat"
vm_configs = []

# Set BACKTRACE=y to retain frame pointers for richer target-side traces.
[env]
KERNEL_BUILTIN_CMDLINE = "root=/dev/nvme0n1 earlycon=uart8250,mmio,0x1fe001e0,115200"
# BACKTRACE = "y"
