include = [".config-local.toml"]

[net]
git-fetch-with-cli = true

[resolver]
incompatible-rust-versions = "allow"

[alias]
arceos = "run -p tg-xtask -- arceos"
axvisor = "run -p tg-xtask -- axvisor"
starry = "run -p tg-xtask -- starry"
xtask = "run -p tg-xtask --"
board = "run -p tg-xtask -- board"
