#!/usr/bin/env bash
set -euo pipefail

# Build the three frozen Task-3 controller variants used by the quantitative
# comparison.  Each variant gets an independent Cargo target/output directory;
# the runner then selects only the resulting initramfs by mode.

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
out_root="${OUT_ROOT:-$repo_root/tmp/task3-quant}"
runtime_dir="${RUNTIME_DIR:-$repo_root/tmp/net-dual-guest/linux-task2}"
base_initramfs="${BASE_INITRAMFS:-/home/huhu/tgoskits-realtime/tmp/initramfs-custom}"

if [[ ! -f "$base_initramfs" ]]; then
    echo "error: BASE_INITRAMFS is missing: $base_initramfs" >&2
    exit 1
fi
mkdir -p "$out_root" "$runtime_dir"

for mode in baseline cnn yolo; do
    variant_dir="$out_root/$mode"
    mkdir -p "$variant_dir"
    build_log="$variant_dir/build-linux-task2.log"
    init_log="$variant_dir/build-linux-initramfs.log"

    if [[ "$mode" == yolo ]]; then
        TASK3_MODEL_PATH=embedded:fixture-replay \
        TASK3_YOLO_MIN_CONFIDENCE_MILLI=600 \
        TASK3_YOLO_MIN_AREA_MILLI=10 \
        TASK3_YOLO_MAX_TARGET_STEP=100 \
        TASK3_CONTROL_LOOP=1 TASK3_MODEL="$mode" OUT_DIR="$variant_dir/linux" \
            bash "$repo_root/scripts/test/net-dual-guest/build-linux-task2.sh" \
            >"$build_log" 2>&1
    else
        TASK3_CONTROL_LOOP=1 TASK3_MODEL="$mode" OUT_DIR="$variant_dir/linux" \
            bash "$repo_root/scripts/test/net-dual-guest/build-linux-task2.sh" \
            >"$build_log" 2>&1
    fi

    TASK2_BINARY="$variant_dir/linux/controller/task2-net" \
    BASE_INITRAMFS="$base_initramfs" OUT_DIR="$variant_dir/initramfs" \
        bash "$repo_root/scripts/test/net-dual-guest/build-linux-initramfs.sh" \
        >"$init_log" 2>&1

    artifact="$variant_dir/initramfs/task2-linux-initramfs.cpio.gz"
    if [[ ! -s "$artifact" ]]; then
        echo "error: variant artifact is missing or empty: $artifact" >&2
        exit 1
    fi
    cp "$artifact" "$runtime_dir/task2-linux-initramfs-$mode.cpio.gz"
    sha256sum "$runtime_dir/task2-linux-initramfs-$mode.cpio.gz" \
        > "$runtime_dir/task2-linux-initramfs-$mode.cpio.gz.sha256"
done

manifest="$out_root/manifest.toml"
{
    printf '# Generated by scripts/task3/build-quant-variants.sh\n'
    printf 'git_head = "%s"\n' "$(git -C "$repo_root" rev-parse HEAD)"
    printf 'base_initramfs = "%s"\n' "$base_initramfs"
    for mode in baseline cnn yolo; do
        artifact="$runtime_dir/task2-linux-initramfs-$mode.cpio.gz"
        printf '\n[%s]\n' "$mode"
        printf 'artifact = "%s"\n' "$artifact"
        printf 'sha256 = "%s"\n' "$(sha256sum "$artifact" | awk '{print $1}')"
    done
} > "$manifest"
echo "wrote $manifest"
cat "$manifest"
