#!/usr/bin/env python3
"""Train a tiny MLP for Task 3 slow-loop PID tuning and emit a C weight header."""

from __future__ import annotations

import math
import random
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "task2" / "task3-mlp-weights.h"

IN_DIM = 4
HIDDEN = 8
OUT_DIM = 3


def relu(x: float) -> float:
    return x if x > 0.0 else 0.0


def rule_deltas(err: float, kp: float, ki: float) -> tuple[float, float, float]:
    abs_err = abs(err)
    dkp = 0.0
    dki = 0.0
    dkd = 0.0
    if abs_err > 20.0:
        dkp = 0.15
        dki = 0.02
    elif abs_err > 5.0:
        dkp = 0.08
    if kp + dkp > 8.0:
        dkp = max(0.0, 8.0 - kp)
    if ki + dki > 0.5:
        dki = max(0.0, 0.5 - ki)
    return dkp, dki, dkd


def sample() -> tuple[list[float], list[float]]:
    err = random.uniform(-80.0, 80.0)
    kp = random.uniform(0.3, 7.5)
    ki = random.uniform(0.02, 0.45)
    x = [err / 80.0, abs(err) / 80.0, kp / 8.0, ki / 0.5]
    y = list(rule_deltas(err, kp, ki))
    return x, y


def matvec(w: list[list[float]], b: list[float], x: list[float], act_relu: bool) -> list[float]:
    out = [sum(w[i][j] * x[j] for j in range(len(x))) + b[i] for i in range(len(w))]
    if act_relu:
        out = [relu(v) for v in out]
    return out


def train() -> tuple[list[list[float]], list[float], list[list[float]], list[float]]:
    rng = random.Random(42)
    w1 = [[rng.uniform(-0.8, 0.8) for _ in range(IN_DIM)] for _ in range(HIDDEN)]
    b1 = [0.0] * HIDDEN
    w2 = [[rng.uniform(-0.8, 0.8) for _ in range(HIDDEN)] for _ in range(OUT_DIM)]
    b2 = [0.0] * OUT_DIM

    lr = 0.05
    for _ in range(4000):
        x, target = sample()
        h_pre = [sum(w1[i][j] * x[j] for j in range(IN_DIM)) + b1[i] for i in range(HIDDEN)]
        h = [relu(v) for v in h_pre]
        y = [sum(w2[i][j] * h[j] for j in range(HIDDEN)) + b2[i] for i in range(OUT_DIM)]
        err = [y[i] - target[i] for i in range(OUT_DIM)]
        for i in range(OUT_DIM):
            for j in range(HIDDEN):
                grad = err[i] if h_pre[j] > 0.0 else 0.0
                w2[i][j] -= lr * grad * h[j]
            b2[i] -= lr * err[i]
        for j in range(HIDDEN):
            if h_pre[j] <= 0.0:
                continue
            delta = sum(err[i] * w2[i][j] for i in range(OUT_DIM))
            for k in range(IN_DIM):
                w1[j][k] -= lr * delta * x[k]
            b1[j] -= lr * delta

    return w1, b1, w2, b2


def fmt(name: str, rows: list[list[float]] | list[float]) -> str:
    if rows and isinstance(rows[0], list):
        lines = [f"static const double {name}[][{len(rows[0])}] = {{"]
        for row in rows:
            lines.append("    {" + ", ".join(f"{v:.17g}" for v in row) + "},")
        lines.append("};")
        return "\n".join(lines)
    assert isinstance(rows, list)
    body = ", ".join(f"{v:.17g}" for v in rows)
    return f"static const double {name}[{len(rows)}] = {{ {body} }};"


def main() -> None:
    w1, b1, w2, b2 = train()

    # Sanity: compare against a few rule samples.
    worst = 0.0
    for err in (-60.0, -10.0, -3.0, 0.0, 4.0, 15.0, 40.0):
        kp, ki = 0.5, 0.08
        x = [err / 80.0, abs(err) / 80.0, kp / 8.0, ki / 0.5]
        h = matvec(w1, b1, x, True)
        y = matvec(w2, b2, h, False)
        ref = rule_deltas(err, kp, ki)
        worst = max(worst, max(abs(y[i] - ref[i]) for i in range(3)))
    if worst > 0.05:
        raise SystemExit(f"MLP fit error too large: {worst:.4f}")

    header = f"""/* Auto-generated by scripts/task3/export_mlp_weights.py — do not edit. */
#pragma once

#define TASK3_MLP_IN_DIM {IN_DIM}
#define TASK3_MLP_HIDDEN {HIDDEN}
#define TASK3_MLP_OUT_DIM {OUT_DIM}

{fmt("task3_mlp_w1", w1)}
{fmt("task3_mlp_b1", b1)}
{fmt("task3_mlp_w2", w2)}
{fmt("task3_mlp_b2", b2)}
"""
    OUT.write_text(header, encoding="utf-8")
    print(f"wrote {OUT} (max rule error {worst:.4f})")


if __name__ == "__main__":
    main()
