#!/usr/bin/env python3
"""Regenerate the Rust golden-vector test from the final exported weights.

The golden inputs are three fixed, hand-specified windows (zero, constant,
and ramp patterns) so the test is fully reproducible and independent of the
dataset; the reference outputs come from the torch float64 model built from
the exact `weights.bin` blob the Rust guest embeds.
"""

import json
import struct
import subprocess
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

REPO_ROOT = Path(__file__).resolve().parents[2]
MODEL_DIR = REPO_ROOT / "components" / "task3-model" / "model"
FEATURES = 4
WINDOW = 64


class PlantCnn(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv1d(FEATURES, 32, kernel_size=5, padding=2, dtype=torch.float64)
        self.conv2 = nn.Conv1d(32, 64, kernel_size=5, padding=2, dtype=torch.float64)
        self.fc1 = nn.Linear(64, 32, dtype=torch.float64)
        self.fc2 = nn.Linear(32, 1, dtype=torch.float64)
        self.activation = nn.ReLU()

    def forward(self, x):
        x = self.activation(self.conv1(x))
        x = self.activation(self.conv2(x))
        x = x.mean(dim=2)
        x = self.activation(self.fc1(x))
        return self.fc2(x).squeeze(-1)


def load_model() -> PlantCnn:
    blob = (MODEL_DIR / "weights.bin").read_bytes()
    counts = {
        "conv1.weight": 640,
        "conv1.bias": 32,
        "conv2.weight": 10240,
        "conv2.bias": 64,
        "fc1.weight": 2048,
        "fc1.bias": 32,
        "fc2.weight": 32,
        "fc2.bias": 1,
    }
    shapes = {
        "conv1.weight": (32, 4, 5),
        "conv1.bias": (32,),
        "conv2.weight": (64, 32, 5),
        "conv2.bias": (64,),
        "fc1.weight": (32, 64),
        "fc1.bias": (32,),
        "fc2.weight": (1, 32),
        "fc2.bias": (1,),
    }
    model = PlantCnn()
    state = {}
    offset = 0
    for name in sorted(counts):
        n = counts[name]
        values = np.frombuffer(blob[offset : offset + n * 8], dtype=np.float64)
        offset += n * 8
        state[name] = torch.from_numpy(np.array(values.reshape(shapes[name]), copy=True))
    model.load_state_dict(state)
    model.eval()
    return model


def fixed_inputs():
    """Three deterministic windows: zero, constant, and a linear ramp."""
    zero = np.zeros((WINDOW, FEATURES), dtype=np.float64)
    constant = np.full((WINDOW, FEATURES), 0.5, dtype=np.float64)
    ramp = np.zeros((WINDOW, FEATURES), dtype=np.float64)
    for t in range(WINDOW):
        ramp[t, 0] = 0.1 + 0.01 * t  # state rising
        ramp[t, 1] = 0.8  # target
        ramp[t, 2] = 0.8 - ramp[t, 0]  # error
        ramp[t, 3] = 0.9  # previous output
    return [zero, constant, ramp]


def window_cases():
    """Golden cases for build_features: empty history, short history and a
    full history longer than the window."""
    cases = [
        {
            "state_history": [],
            "output_history": [],
            "target": 500,
            "fallback_state": 300,
            "fallback_output": 0,
        },
        {
            "state_history": [100, 200, 300],
            "output_history": [50, 60, 70],
            "target": 500,
            "fallback_state": 300,
            "fallback_output": 0,
        },
        {
            "state_history": [int(100 + t * 10) for t in range(70)],
            "output_history": [int(200 + t * 5) for t in range(70)],
            "target": 800,
            "fallback_state": 300,
            "fallback_output": 0,
        },
    ]
    return cases


def rust_f64(value: float) -> str:
    value = float(value)
    text = f"{value!r}"
    if "e" not in text and "." not in text:
        text += ".0"
    return text


def main():
    from features import build_window

    model = load_model()
    inputs = fixed_inputs()
    outputs = []
    with torch.no_grad():
        for window in inputs:
            x = torch.from_numpy(window.T[np.newaxis, ...]).double()
            outputs.append(float(model(x).numpy()[0]))

    lines = [
        "// Generated by scripts/task3/export_golden.py; do not edit.",
        "// Golden vectors: fixed inputs with the torch float64 reference",
        "// outputs computed from the exact weights.bin blob.",
        "use crate::{forward, FEATURES, WINDOW};",
        "",
        "const GOLDEN_CASES: usize = 3;",
        "",
        "fn golden_input(index: usize) -> [[f64; FEATURES]; WINDOW] {",
        "    match index {",
    ]
    for case_index, window in enumerate(inputs):
        body = []
        for t in range(WINDOW):
            values = ", ".join(rust_f64(v) for v in window[t])
            body.append(f"            [{values}],")
        lines.append(f"        {case_index} => [")
        lines.extend(body)
        lines.append("        ],")
    lines.append("        _ => unreachable!(),")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("fn golden_output(index: usize) -> f64 {")
    lines.append("    match index {")
    for case_index, value in enumerate(outputs):
        lines.append(f"        {case_index} => {rust_f64(value)},")
    lines.append("        _ => unreachable!(),")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("#[test]")
    lines.append("fn golden_vectors_match_reference() {")
    lines.append("    for index in 0..GOLDEN_CASES {")
    lines.append("        let output = forward(&golden_input(index));")
    lines.append("        let expected = golden_output(index);")
    lines.append(
        '        assert!((output - expected).abs() < 1e-9, "case {index}: output={output} expected={expected}");'
    )
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # Window-construction golden cases pin build_features to the Python
    # features.build_window contract.
    window_cases_list = window_cases()
    lines.append("const WINDOW_CASES: usize = 3;")
    lines.append("")
    lines.append(
        "fn window_input(index: usize) -> (&'static [i32], &'static [i32], i32, i32, i32) {"
    )
    lines.append("    match index {")
    for case_index, case in enumerate(window_cases_list):
        states_text = ", ".join(str(v) for v in case["state_history"])
        outputs_text = ", ".join(str(v) for v in case["output_history"])
        lines.append(
            f"        {case_index} => (&[{states_text}], &[{outputs_text}], "
            f"{case['target']}, {case['fallback_state']}, {case['fallback_output']}),"
        )
    lines.append("        _ => unreachable!(),")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("fn window_expected(index: usize) -> [[f64; FEATURES]; WINDOW] {")
    lines.append("    match index {")
    for case_index, case in enumerate(window_cases_list):
        expected = build_window(
            case["state_history"],
            case["output_history"],
            case["target"],
            case["fallback_state"],
            case["fallback_output"],
        )
        body = []
        for t in range(WINDOW):
            values = ", ".join(rust_f64(v) for v in expected[t])
            body.append(f"            [{values}],")
        lines.append(f"        {case_index} => [")
        lines.extend(body)
        lines.append("        ],")
    lines.append("        _ => unreachable!(),")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("#[test]")
    lines.append("fn window_build_matches_reference() {")
    lines.append("    for index in 0..WINDOW_CASES {")
    lines.append("        let (states, outputs, target, fallback_state, fallback_output) = window_input(index);")
    lines.append("        let built = crate::build_features(states, outputs, target, fallback_state, fallback_output);")
    lines.append("        let expected = window_expected(index);")
    lines.append("        for t in 0..WINDOW {")
    lines.append("            for ch in 0..FEATURES {")
    lines.append('                assert!((built[t][ch] - expected[t][ch]).abs() < 1e-12, "case {index} t={t} ch={ch}: built={} expected={}", built[t][ch], expected[t][ch]);')
    lines.append("            }")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    (MODEL_DIR / "golden_vectors.rs").write_text("\n".join(lines) + "\n")
    _format_rust(MODEL_DIR / "golden_vectors.rs")
    (REPO_ROOT / "tmp" / "task3-data" / "golden.json").write_text(
        json.dumps(
            {
                "inputs": [w.tolist() for w in inputs],
                "outputs": outputs,
            },
            indent=2,
        )
        + "\n"
    )
    print("outputs:", [round(v, 12) for v in outputs])
    print(f"wrote {MODEL_DIR / 'golden_vectors.rs'}")


def _format_rust(path: Path) -> None:
    """Best-effort rustfmt pass so regenerated files stay CI-clean."""
    try:
        subprocess.run(
            ["rustfmt", "--edition", "2024", str(path)],
            check=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError) as error:
        print(f"warning: rustfmt on {path} failed: {error}")


if __name__ == "__main__":
    main()
