#!/usr/bin/env bash
# Task 3: fixed PID vs MLP slow-loop comparison + latency report.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPORT_DIR="${ROOT}/plans/task3-reports"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
LOG="${REPORT_DIR}/task3-compare-${STAMP}.log"
REPORT_MD="${REPORT_DIR}/task3-compare-${STAMP}.md"

info() { echo "[task3] $*"; }

field() {
  local log_file="$1"
  local key="$2"
  grep -E "^TASK3_COMPARE " "${log_file}" | tail -1 | sed -n "s/.*${key}=\\([^ ]*\\).*/\\1/p"
}

mkdir -p "${REPORT_DIR}"

info "=== Task 3 fixed vs AI compare (${STAMP}) ==="
"${ROOT}/scripts/task2/setup-peer-initramfs.sh"
"${ROOT}/scripts/task3/setup-ai-loop.sh"

(
  cd "${ROOT}"
  CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-${ROOT}/target}" \
    cargo xtask axvisor test qemu --arch aarch64 -c task3-pid-compare
) 2>&1 | tee "${LOG}"

if ! grep -q 'task3-compare pass' "${LOG}"; then
  echo "task3-compare test failed; see ${LOG}" >&2
  exit 1
fi

{
  echo "# Task 3 Fixed PID vs AI Slow-Loop (${STAMP})"
  echo
  echo "Generated by \`scripts/task3/run-task3-compare.sh\`."
  echo
  echo "## End-to-end latency (method 1: one-way ≈ RTT/2, T1 in icpc header)"
  echo
  echo "| mode | p99 oneway (us) |"
  echo "|---|---:|"
  echo "| fixed | $(field "${LOG}" fixed_p99_oneway_us) |"
  echo "| AI | $(field "${LOG}" ai_p99_oneway_us) |"
  echo
  echo "## Control effect"
  echo
  echo "| metric | fixed | AI | better |"
  echo "|---|---:|---:|---|"
  echo "| RMSE | $(field "${LOG}" fixed_rmse) | $(field "${LOG}" ai_rmse) | lower |"
  echo "| settle loops | $(field "${LOG}" fixed_settle) | $(field "${LOG}" ai_settle) | lower |"
  echo "| final err | $(field "${LOG}" fixed_final_err) | $(field "${LOG}" ai_final_err) | lower |"
  echo
  echo "## Raw log"
  echo
  echo "- [\`$(basename "${LOG}")\`](./$(basename "${LOG}"))"
} > "${REPORT_MD}"

info "Wrote ${REPORT_MD}"

# Regression
CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-${ROOT}/target}" \
  cargo xtask axvisor test qemu --arch aarch64 -c task3-pid-loop

info "=== Task 3 compare complete ==="
