#!/usr/bin/env python3
"""Train the Task-3 1D temporal CNN and export fixed weights for the Rust guest.

Architecture (frozen in M0, book/design/task3-ai-control-todo.md):

    input:  64 samples x 4 features (state, target, error, prev_output)
    Conv1D  4 -> 32, kernel 5, same padding, ReLU
    Conv1D 32 -> 64, kernel 5, same padding, ReLU
    Global average pooling
    Dense 64 -> 32, ReLU
    Dense 32 -> 1 (linear, output = control value 0..1000)

Training is imitation learning: the label is the perfect one-step inverse
controller output (plant.teacher_output).  The model never sees the
disturbance; it must recover it from the history window.

Exports:
  components/task3-model/model/weights.bin   little-endian f64 tensor blob
  components/task3-model/model/model.json    structure + hashes + metrics
  tmp/task3-data/golden.json                 golden vectors for the Rust tests
"""

import argparse
import hashlib
import json
import struct
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from plant import OUTPUT_MAX, OUTPUT_MIN  # noqa: E402

WINDOW = 64
FEATURES = 4


class PlantCnn(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv1d(FEATURES, 32, kernel_size=5, padding=2)
        self.conv2 = nn.Conv1d(32, 64, kernel_size=5, padding=2)
        self.fc1 = nn.Linear(64, 32)
        self.fc2 = nn.Linear(32, 1)
        self.activation = nn.ReLU()

    def forward(self, x):
        x = self.activation(self.conv1(x))
        x = self.activation(self.conv2(x))
        x = x.mean(dim=2)
        x = self.activation(self.fc1(x))
        return self.fc2(x).squeeze(-1)


def parameter_count(model):
    return sum(p.numel() for p in model.parameters())


def macs_estimate(model, window=WINDOW):
    conv1 = 32 * window * 4 * 5
    conv2 = 64 * window * 32 * 5
    fc1 = 64 * 32
    fc2 = 32 * 1
    return conv1 + conv2 + fc1 + fc2


def freeze(model):
    return {name: tensor.detach().cpu().numpy() for name, tensor in model.state_dict().items()}


def export_blob(state_dict, out_path):
    blob = b""
    offsets = {}
    cursor = 0
    for name in sorted(state_dict):
        values = np.ascontiguousarray(state_dict[name], dtype=np.float64).reshape(-1)
        offsets[name] = (cursor, int(values.shape[0]))
        blob += struct.pack(f"<{len(values)}d", *values.tolist())
        cursor += len(values) * 8
    out_path.write_bytes(blob)
    return blob, offsets


def export_rust_forward_tests(model_path, out_path, inputs, outputs):
    """Generate a Rust test file with the golden vectors for the inference crate."""
    lines = [
        "// Generated by scripts/task3/train_model.py; do not edit.",
        "// Golden vectors produced by the Python (torch) reference forward pass.",
        "use crate::forward;",
        "",
        "const GOLDEN_CASES: usize = {n};".format(n=len(inputs)),
        "",
        "fn golden_input(index: usize) -> [[f64; {f}]; {w}] {{".format(f=FEATURES, w=WINDOW),
        "    match index {",
    ]
    for case_index, (input, _) in enumerate(zip(inputs, outputs)):
        rows = []
        for row in input.T:  # transpose (4, 64) -> rows of features? keep (64,4)
            pass
        body = []
        for t in range(WINDOW):
            values = ", ".join(f"{v:.17g}" for v in input[t])
            body.append(f"            [{values}],")
        lines.append(f"        {case_index} => [")
        lines.extend(body)
        lines.append("        ],")
    lines.append("        _ => unreachable!(),")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append(
        "fn golden_output(index: usize) -> f64 { match index {"
        + " ".join(f"{i} => {o:.17g}," for i, (_, o) in enumerate(zip(inputs, outputs)))
        + " _ => unreachable!(), } }"
    )
    lines.append("")
    lines.append("#[test]")
    lines.append("fn golden_vectors_match_reference() {")
    lines.append("    for index in 0..GOLDEN_CASES {")
    lines.append("        let output = forward(&golden_input(index), index);")
    lines.append("        let expected = golden_output(index);")
    lines.append("        assert!((output - expected).abs() < 1e-9, \"case {index}: output={output} expected={expected}\");")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    out_path.write_text("\n".join(lines) + "\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=Path, default=Path("tmp/task3-data"))
    parser.add_argument("--epochs", type=int, default=40)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--seed", type=int, default=20260811)
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    train = np.load(args.data_dir / "train.npz")
    val = np.load(args.data_dir / "val.npz")
    train_x = torch.from_numpy(train["features"]).float().transpose(1, 2)  # (N, 4, 64)
    train_y = torch.from_numpy(train["labels"]).float() / 1000.0
    val_x = torch.from_numpy(val["features"]).float().transpose(1, 2)
    val_y = torch.from_numpy(val["labels"]).float() / 1000.0

    model = PlantCnn()
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr)
    criterion = nn.MSELoss()

    best_val = float("inf")
    best_state = None
    for epoch in range(args.epochs):
        model.train()
        permutation = torch.randperm(train_x.shape[0])
        total_loss = 0.0
        steps = 0
        for start in range(0, train_x.shape[0], args.batch_size):
            indices = permutation[start : start + args.batch_size]
            x, y = train_x[indices], train_y[indices]
            optimizer.zero_grad()
            loss = criterion(model(x), y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            steps += 1
        model.eval()
        with torch.no_grad():
            val_loss = criterion(model(val_x), val_y).item()
        if val_loss < best_val:
            best_val = val_loss
            best_state = freeze(model)
        if (epoch + 1) % 10 == 0 or epoch == 0:
            print(f"epoch {epoch + 1}/{args.epochs} train_mse={total_loss / steps:.6f} val_mse={val_loss:.6f}")

    model_dir = args.repo_root / "components" / "task3-model" / "model"
    model_dir.mkdir(parents=True, exist_ok=True)
    weights_path = model_dir / "weights.bin"
    blob, offsets = export_blob(best_state, weights_path)
    weight_sha256 = hashlib.sha256(blob).hexdigest()
    source_sha256 = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()

    model.load_state_dict({k: torch.from_numpy(v) for k, v in best_state.items()})
    model.eval()
    with torch.no_grad():
        preds = model(val_x).numpy() * 1000.0
        label_mae = float(np.mean(np.abs(preds - val["labels"])))

    manifest = {
        "architecture": {
            "input": [WINDOW, FEATURES],
            "conv1": {"in": 4, "out": 32, "kernel": 5, "padding": "same"},
            "conv2": {"in": 32, "out": 64, "kernel": 5, "padding": "same"},
            "pool": "global average",
            "fc1": [64, 32],
            "fc2": [32, 1],
            "activation": "relu",
        },
        "params": parameter_count(model),
        "macs_estimate": macs_estimate(model),
        "weights_file": "weights.bin",
        "weights_sha256": weight_sha256,
        "weights_bytes": len(blob),
        "trainer_sha256": source_sha256,
        "best_val_mse": best_val,
        "val_label_mae": label_mae,
        "normalization": {
            "state_scale": 1000.0,
            "target_scale": 1000.0,
            "error_scale": 1000.0,
            "output_scale": 1000.0,
            "label_scale": 1000.0,
        },
        "seed": args.seed,
        "epochs": args.epochs,
        "trainer": str(Path(__file__).name),
    }
    (model_dir / "model.json").write_text(json.dumps(manifest, indent=2) + "\n")

    # Golden vectors: three validation windows (fixed by seed) plus the
    # reference forward outputs, exported to the Rust test file.
    rng = np.random.default_rng(20260811)
    indices = rng.choice(val_x.shape[0], size=3, replace=False)
    with torch.no_grad():
        gold = model(val_x[indices]).numpy().reshape(-1) * 1000.0
    golden_inputs = val["features"][indices]
    golden_outputs = gold.tolist()
    export_rust_forward_tests(model_dir, model_dir / "golden_vectors.rs", golden_inputs, golden_outputs)
    (args.data_dir / "golden.json").write_text(
        json.dumps(
            {
                "inputs": [g.astype(np.float64).tolist() for g in golden_inputs],
                "outputs": golden_outputs,
            },
            indent=2,
        )
        + "\n"
    )

    print(json.dumps(manifest, indent=2))
    print(f"wrote {weights_path} ({len(blob)} bytes)")


if __name__ == "__main__":
    main()
