# Task 1 RT guest — OrangePi-5-Plus baseline (emulated timer, no vCPU priority)
#
[base]
id = 2
name = "arceos-rt-orangepi-baseline"
vm_type = 1
cpu_num = 1
phys_cpu_ids = [0x700]

[kernel]
entry_point = 0x4008_0000
image_location = "fs"
kernel_path = "/guest/arceos/orangepi-5-plus-rt-latency"
kernel_load_addr = 0x4008_0000
dtb_load_addr = 0x4000_0000

memory_regions = [
  [0x4000_0000, 0x0800_0000, 0x7, 1],
]

[devices]
interrupt_mode = "passthrough"
passthrough_timer = false

passthrough_devices = [
    ["/"],
]

passthrough_addresses = []

excluded_devices = []

emu_devices = []
