cmake_minimum_required(VERSION 3.20)
project(test-devpts-newinstance C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
add_executable(test-devpts-newinstance src/main.c)
target_compile_options(test-devpts-newinstance PRIVATE -Wall -Wextra -Werror)
install(TARGETS test-devpts-newinstance RUNTIME DESTINATION usr/bin/starry-test-suit)
