args = [
  "-no-user-config",
  "-display",
  "none",
  "-serial",
  "stdio",
  "-monitor",
  "none",
  "-cpu",
  "host,-la57,+vmx-ept,+vmx-unrestricted-guest,+vmx-flexpriority",
  "-machine",
  "q35,smbus=off,usb=off,graphics=off",
  "-smp",
  "1",
  "-accel",
  "kvm",
  "-device",
  "nvme,drive=disk0,serial=tgoskits,max_ioqpairs=64,msix_qsize=65,addr=03.0",
  "-drive",
  "id=disk0,if=none,format=raw,file=${workspace}/tmp/axbuild/rootfs/rootfs-x86_64-alpine.img",
  "-m",
  "512M",
  "-net",
  "none",
  "-vga",
  "none",
]
timeout = 600
fail_regex = [
  "(?i)\\bpanic(?:ked)?\\b",
  "(?i)kernel panic",
  "(?i)login incorrect",
  "(?i)permission denied",
  "failed to mask forwarded IOAPIC GSI .*: Busy",
]
success_regex = [
  "(?m)^AXVISOR_X86_NVME_GUEST_BOOT_PASSED\\s*$",
]
shell_prefix = "~ #"
shell_init_cmd = "\u001b[1;1Rpwd && echo AXVISOR_X86_NVME_GUEST_BOOT_PASSED"
to_bin = true
uefi = true
