# AxVM machine policy.
[machine]
mode = "passthrough"
firmware = "auto"
interrupts_passthrough = true

[base]
id = 2
name = "linux"
cpu_num = 1
phys_cpu_ids = [0x0]

[kernel]
entry_point = 0x80080000
image_location = "fs"
kernel_load_addr = 0x80080000
kernel_path = "/userdata/rootfs_overlay/guest/linux/roc-rk3568-pc"
dtb_load_addr = 0x80000000

[[memory.regions]]
guest_base = 0
size = 0x60000000
permissions = "rwx"
backing = { kind = "identity-allocate" }

[devices]
disable_defaults = []
deny = []
