//! OS-independent task scheduling core.
//!
//! `bare-task` owns the task state, wake, wait, timer, and virtual IRQ test
//! protocols. Operating systems provide hardware and context-switch services
//! through the [`BareTaskOs`] trait generated by `trait-ffi`.

#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;

use trait_ffi::*;

pub mod core;
pub mod local;
pub mod os;
pub mod runtime;
pub mod scheduler;
pub mod sync;
pub mod timer;
pub mod wait_queue;
pub mod wake;

#[cfg(feature = "host-test")]
pub mod host;

pub use core::{CpuId, CpuMask, TaskCore, TaskId, TaskRef, TaskState};

pub use local::{LocalExecutorCore, LocalSpawnerCore, SpawnLocalError};
pub use runtime::{BlockOnWakeState, RuntimeEventCore, RuntimeEventSeq, RuntimeEventValue};
pub use scheduler::{FifoScheduler, RoundRobinScheduler, Scheduler, TaskOps, make_ready};
pub use timer::{TimerKey, TimerRuntimeCore};
pub use wait_queue::WaitQueueCore;
pub use wake::{HardIrqWaker, IrqWakeQueueCore, TaskWaker, WakeBits, WakeResult, WakeSeq};

/// Host/OS services required by the bare task core.
///
/// Implementations are provided by the OS adapter crate. The core deliberately
/// keeps this ABI narrow and uses only plain values or local newtypes.
#[def_extern_trait]
pub trait BareTaskOs {
    /// Returns the number of online CPUs.
    fn cpu_num() -> usize;

    /// Returns the current CPU id.
    fn this_cpu_id() -> CpuId;

    /// Returns the raw current-task pointer stored by the OS.
    fn current_task_ptr() -> *const ();

    /// Stores the raw current-task pointer for the current CPU.
    ///
    /// # Safety
    ///
    /// `ptr` must be null or point to a task object that stays valid while it
    /// is installed as the current task.
    unsafe fn set_current_task_ptr(ptr: *const ());

    /// Disables local IRQs and returns an opaque previous IRQ state.
    fn irq_save_and_disable() -> usize;

    /// Restores a previous local IRQ state.
    ///
    /// # Safety
    ///
    /// `state` must have been returned by [`BareTaskOs::irq_save_and_disable`]
    /// in the same execution context.
    unsafe fn irq_restore(state: usize);

    /// Returns whether local IRQs are currently enabled.
    fn irqs_enabled() -> bool;

    /// Returns whether execution is currently inside hard IRQ context.
    fn in_irq_context() -> bool;

    /// Waits until an interrupt is observed.
    fn wait_for_irqs();

    /// Returns monotonic time in nanoseconds.
    fn monotonic_time_nanos() -> u64;

    /// Programs a one-shot timer deadline in monotonic nanoseconds.
    fn set_oneshot_timer(deadline_nanos: u64);

    /// Requests that `cpu` re-evaluate scheduling.
    fn request_reschedule(cpu: CpuId);

    /// Requests that `cpu` drain its hard-IRQ wake queue.
    fn request_irq_wake(cpu: CpuId);

    /// Returns whether `cpu` is ready to receive cross-CPU requests.
    fn wait_until_cpu_ready(cpu: CpuId) -> bool;

    /// Notifies the host that a context switch happened.
    fn on_sched_switch(prev: usize, next: usize, next_state: u8);
}
