features = [
  "sdmmc",
  "rockchip-dwmmc",
  "rockchip-soc",
  "fs",
  "rt-trace",
]
log = "Info"
target = "aarch64-unknown-none-softfloat"
vm_configs = [
  "scripts/benchmark/axvisor-rt/config/starry-orangepi-5-plus-smp2-shared.toml",
]
max_cpu_num = 4
