cmake_minimum_required(VERSION 3.20)
project(bug-setns-requires-cap-sys-admin C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS ON)
add_executable(bug-setns-requires-cap-sys-admin src/main.c)
target_compile_options(bug-setns-requires-cap-sys-admin PRIVATE -Wall -Wextra -Werror)
install(TARGETS bug-setns-requires-cap-sys-admin RUNTIME DESTINATION usr/bin/starry-test-suit)
