#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
zephyr_base="${ZEPHYR_BASE:-/tmp/zephyrproject/zephyr}"
zephyr_sdk="${ZEPHYR_SDK_INSTALL_DIR:-/tmp/zephyr-sdk}"
west_bin="${WEST_BIN:-/home/huhu/.local/bin/west}"
out_dir="${OUT_DIR:-$repo_root/tmp/net-dual-guest/zephyr-task2}"
build_dir="$out_dir/cargo-target"
source_dir="$repo_root/scripts/test/net-dual-guest/zephyr-task2"
memory_base="${TASK2_ZEPHYR_MEMORY_BASE:-0xA0000000}"
memory_size="${TASK2_ZEPHYR_MEMORY_SIZE:-0x08000000}"

case "$memory_base" in
    0x*) ;;
    *) printf 'error: TASK2_ZEPHYR_MEMORY_BASE must be hexadecimal\n' >&2; exit 1 ;;
esac
case "$memory_size" in
    0x*) ;;
    *) printf 'error: TASK2_ZEPHYR_MEMORY_SIZE must be hexadecimal\n' >&2; exit 1 ;;
esac
memory_base_value=$((memory_base))
memory_size_value=$((memory_size))
memory_base="$(printf '0x%08x' "$memory_base_value")"
memory_size="$(printf '0x%08x' "$memory_size_value")"

for executable in "$west_bin"; do
    if [[ ! -x "$executable" ]]; then
        printf 'error: west is not executable: %s\n' "$executable" >&2
        exit 1
    fi
done
if [[ ! -d "$zephyr_base" || ! -d "$zephyr_sdk" ]]; then
    printf 'error: Zephyr source or SDK is missing (%s, %s)\n' "$zephyr_base" "$zephyr_sdk" >&2
    exit 1
fi

mkdir -p "$out_dir"
memory_overlay="$out_dir/memory.overlay"
printf '/* Generated; keep Zephyr physical, virtual and DMA addresses identical. */\n&sram0 {\n\treg = <0x0 %s 0x0 %s>;\n};\n' \
    "$memory_base" "$memory_size" > "$memory_overlay"
ZEPHYR_BASE="$zephyr_base" \
ZEPHYR_SDK_INSTALL_DIR="$zephyr_sdk" \
"$west_bin" build \
    -b qemu_cortex_a53 \
    "$source_dir" \
    -d "$build_dir" \
    -- \
    -DDTC_OVERLAY_FILE="$source_dir/app.overlay;$memory_overlay" \
    -DEXTRA_CFLAGS=-DCONFIG_MAX_IRQ_LINES=64

elf="$out_dir/zephyr-task2.elf"
binary="$out_dir/zephyr-task2.bin"
cp "$build_dir/zephyr/zephyr.elf" "$elf"
objcopy_bin="${OBJCOPY:-$zephyr_sdk/gnu/aarch64-zephyr-elf/bin/aarch64-zephyr-elf-objcopy}"
if [[ ! -x "$objcopy_bin" ]]; then
    printf 'error: objcopy is not executable: %s\n' "$objcopy_bin" >&2
    exit 1
fi
"$objcopy_bin" -O binary "$elf" "$binary"
chmod 0755 "$elf" "$binary"
entry_point="$(readelf -hW "$elf" | awk '/Entry point address:/ {print $4}')"
linked_base="$(readelf -lW "$elf" | awk '$1 == "LOAD" {print $3; exit}')"
if [[ -z "$entry_point" || -z "$linked_base" ]]; then
    printf 'error: failed to extract Zephyr ELF entry/link base\n' >&2
    exit 1
fi
linked_base_value=$((linked_base))
if (( linked_base_value != memory_base_value )); then
    printf 'error: Zephyr linked base %s does not match requested %s\n' "$linked_base" "$memory_base" >&2
    exit 1
fi
linked_base="$(printf '0x%08x' "$linked_base_value")"
sha256="$(sha256sum "$binary" | awk '{print $1}')"
elf_sha256="$(sha256sum "$elf" | awk '{print $1}')"
git_sha="$(git -C "$repo_root" rev-parse HEAD)"
zephyr_version="$(git -C "$zephyr_base" rev-parse HEAD 2>/dev/null || printf 'unversioned')"
manifest="$out_dir/manifest.toml"
{
    printf '# Generated by scripts/test/net-dual-guest/build-zephyr-task2.sh\n'
    printf 'git_head = "%s"\n' "$git_sha"
    printf 'zephyr_base = "%s"\n' "$zephyr_base"
    printf 'zephyr_commit = "%s"\n' "$zephyr_version"
    printf 'board = "qemu_cortex_a53"\n'
    printf 'image_format = "raw"\n'
    printf 'memory_base = "%s"\n' "$memory_base"
    printf 'memory_size = "%s"\n' "$memory_size"
    printf 'elf_entry = "%s"\n' "$entry_point"
    printf 'linked_base = "%s"\n' "$linked_base"
    printf 'fdt_path = "/virtio_mmio@a003c00"\n'
    printf 'host_hwirq = 46\n'
    printf 'sha256 = "%s"\n' "$sha256"
    printf 'elf_sha256 = "%s"\n' "$elf_sha256"
    printf 'elf_path = "%s"\n' "$elf"
    printf 'path = "%s"\n' "$binary"
} > "$manifest"

printf 'elf=%s entry=%s linked_base=%s\n' "$elf" "$entry_point" "$linked_base"
printf 'binary=%s sha256=%s\n' "$binary" "$sha256"
printf 'manifest=%s\n' "$manifest"
