#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
source_dir="$repo_root/scripts/test/net-dual-guest/rtthread-task2"
# shellcheck source=scripts/test/net-dual-guest/rtthread-guest-config.sh
source "$repo_root/scripts/test/net-dual-guest/rtthread-guest-config.sh"
out_dir="${OUT_DIR:-$repo_root/tmp/net-dual-guest/rtthread-task2}"
rtthread_commit="6ea682795bdbac59d3700b21e159ccaa3f7632cb"
rtthread_cache="${RTTHREAD_BASE:-$repo_root/tmp/net-dual-guest/rt-thread-upstream}"
toolchain_dir="${RTT_EXEC_PATH:-/tmp/rtthread-toolchain/bin}"
fault_mode="${TASK2_FAULT_MODE:-none}"
task1_quiet="${TASK1_QUIET:-0}"

case "$fault_mode" in
    none)            fault_define=0 ;;
    drop-ack-once)   fault_define=1 ;;
    drop-ack-always) fault_define=2 ;;
    *)
        printf 'error: TASK2_FAULT_MODE must be none, drop-ack-once, or drop-ack-always\n' >&2
        exit 2
        ;;
esac
case "$task1_quiet" in
    0|1) ;;
    *) printf 'error: TASK1_QUIET must be 0 or 1\n' >&2; exit 2 ;;
esac

gcc="$toolchain_dir/aarch64-none-elf-gcc"
readelf="$toolchain_dir/aarch64-none-elf-readelf"
for executable in git python3 "$gcc" "$readelf"; do
    if ! command -v "$executable" >/dev/null 2>&1 && [[ ! -x "$executable" ]]; then
        printf 'error: required executable is unavailable: %s\n' "$executable" >&2
        exit 1
    fi
done
if ! "$gcc" -dumpfullversion | grep -qx '10.2.1'; then
    printf 'error: expected aarch64-none-elf-gcc 10.2.1 at %s\n' "$gcc" >&2
    exit 1
fi

if [[ ! -d "$rtthread_cache/.git" ]]; then
    if [[ -e "$rtthread_cache" ]]; then
        printf 'error: RTTHREAD_BASE is not an RT-Thread git checkout: %s\n' "$rtthread_cache" >&2
        exit 1
    fi
    mkdir -p "$(dirname "$rtthread_cache")"
    git clone https://github.com/RT-Thread/rt-thread.git "$rtthread_cache"
fi
ensure_rtthread_commit_is_materialized "$rtthread_cache" "$rtthread_commit"

mkdir -p "$out_dir"
build_source="$(mktemp -d "$out_dir/rt-thread-build.XXXXXX")"
cleanup() {
    rm -rf -- "$build_source"
}
trap cleanup EXIT

git clone --quiet --shared --no-checkout "$rtthread_cache" "$build_source"
git -C "$build_source" checkout --quiet --detach "$rtthread_commit"
git -C "$build_source" apply "$source_dir/rtthread.config.patch"
assert_guest_config_has_no_gicv3_its \
    "$build_source/bsp/qemu-virt64-aarch64/.config"
cp "$source_dir/main.c" \
    "$build_source/bsp/qemu-virt64-aarch64/applications/main.c"
if [[ "$task1_quiet" == 1 ]]; then
    perl -pi -e \
        's/^#define TASK2_FAULT_DROP_ACK_MODE/#define TASK1_QUIET 1\n#define TASK2_FAULT_DROP_ACK_MODE/' \
        "$build_source/bsp/qemu-virt64-aarch64/applications/main.c"
fi
perl -pi -e \
    "s/#define TASK2_FAULT_DROP_ACK_MODE 0/#define TASK2_FAULT_DROP_ACK_MODE $fault_define/" \
    "$build_source/bsp/qemu-virt64-aarch64/applications/main.c"

if [[ -n "${SCONS_PYTHONPATH:-}" ]]; then
    scons_env=(env "PYTHONPATH=$SCONS_PYTHONPATH")
elif [[ -d /tmp/rtthread-scons ]]; then
    scons_env=(env "PYTHONPATH=/tmp/rtthread-scons")
else
    scons_env=(env)
fi
if ! "${scons_env[@]}" python3 -c 'import SCons' 2>/dev/null; then
    printf 'error: Python SCons is unavailable; set SCONS_PYTHONPATH\n' >&2
    exit 1
fi

bsp_dir="$build_source/bsp/qemu-virt64-aarch64"
(
    cd "$bsp_dir"
    "${scons_env[@]}" RTT_EXEC_PATH="$toolchain_dir" \
        python3 -m SCons --useconfig=.config
    "${scons_env[@]}" RTT_EXEC_PATH="$toolchain_dir" \
        python3 -m SCons -j"${JOBS:-2}"
)

elf="$out_dir/rtthread-task2.elf"
binary="$out_dir/rtthread-task2.bin"
cp "$bsp_dir/rtthread.elf" "$elf"
cp "$bsp_dir/rtthread.bin" "$binary"

entry_point="$(LC_ALL=C "$readelf" -hW "$elf" | awk '/Entry point address:/ {print $4}')"
if [[ "${entry_point,,}" != "0xa0080000" ]]; then
    printf 'error: unexpected RT-Thread entry point: %s\n' "$entry_point" >&2
    exit 1
fi

binary_sha256="$(sha256sum "$binary" | awk '{print $1}')"
elf_sha256="$(sha256sum "$elf" | awk '{print $1}')"
source_sha256="$(sha256sum "$source_dir/main.c" | awk '{print $1}')"
toolchain_sha256="$(sha256sum "$gcc" | awk '{print $1}')"
manifest="$out_dir/manifest.toml"
{
    printf '# Generated by scripts/test/net-dual-guest/build-rtthread-task2.sh\n'
    printf 'git_head = "%s"\n' "$(git -C "$repo_root" rev-parse HEAD)"
    printf 'rtthread_commit = "%s"\n' "$rtthread_commit"
    printf 'bsp = "qemu-virt64-aarch64"\n'
    printf 'image_format = "raw"\n'
    printf 'memory_base = "0xA0000000"\n'
    printf 'memory_size = "0x20000000"\n'
    printf 'elf_entry = "%s"\n' "$entry_point"
    printf 'fault_mode = "%s"\n' "$fault_mode"
    printf 'task1_quiet = "%s"\n' "$task1_quiet"
    printf 'source_sha256 = "%s"\n' "$source_sha256"
    printf 'toolchain_sha256 = "%s"\n' "$toolchain_sha256"
    printf 'sha256 = "%s"\n' "$binary_sha256"
    printf 'elf_sha256 = "%s"\n' "$elf_sha256"
    printf 'elf_path = "%s"\n' "$elf"
    printf 'path = "%s"\n' "$binary"
} > "$manifest"

printf 'elf=%s entry=%s\n' "$elf" "$entry_point"
printf 'binary=%s sha256=%s\n' "$binary" "$binary_sha256"
printf 'manifest=%s\n' "$manifest"
