#!/usr/bin/env bash
set -euo pipefail

# Build the host-side Linux T2N1 endpoint twice with independent Cargo target
# directories.  Cargo build output is mutable, so each role is copied before
# the next build starts; the final hash check prevents accidentally booting two
# copies of the same compile-time configuration.

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
source "$repo_root/scripts/lib/task123-tools.sh"
out_dir="${OUT_DIR:-$repo_root/tmp/net-dual-guest/linux-task2}"
cross_cc="$(resolve_task123_tool CROSS_CC aarch64-linux-musl-gcc)"
cross_cxx="$(resolve_task123_tool CROSS_CXX aarch64-linux-musl-g++)"
cross_ar="$(resolve_task123_tool CROSS_AR aarch64-linux-musl-ar)"
ncnn_prefix="${NCNN_PREFIX:-$repo_root/tmp/task3-yolo/ncnn-aarch64/install}"
target_triple="aarch64-unknown-linux-musl"
expected_ncnn_revision="946fe3fb14a8dff8c06df763f67be522167b2f00"

command -v sha256sum >/dev/null || {
    printf 'error: sha256sum is required\n' >&2
    exit 1
}
if ! grep -Fqx "ncnn_git_revision = \"$expected_ncnn_revision\"" \
    "$ncnn_prefix/../manifest.toml"; then
    printf 'error: NCNN_PREFIX does not contain pinned ncnn revision %s: %s\n' \
        "$expected_ncnn_revision" "$ncnn_prefix" >&2
    exit 1
fi

mkdir -p "$out_dir"

build_role() {
    local role="$1"
    local local_ip="$2"
    local peer_ip="$3"
    local role_dir="$out_dir/$role"
    local target_dir="$role_dir/cargo-target"
    local binary="$role_dir/task2-net"

    mkdir -p "$role_dir"
    env \
        TASK2_ROLE="$role" \
        TASK2_LOCAL_IP="$local_ip" \
        TASK2_PEER_IP="$peer_ip" \
        ${TASK3_CONTROL_LOOP:+TASK3_CONTROL_LOOP="$TASK3_CONTROL_LOOP"} \
        ${TASK3_AI:+TASK3_AI="$TASK3_AI"} \
        ${TASK3_MODEL:+TASK3_MODEL="$TASK3_MODEL"} \
        ${TASK3_MODEL_PATH:+TASK3_MODEL_PATH="$TASK3_MODEL_PATH"} \
        ${TASK3_YOLO_MIN_CONFIDENCE_MILLI:+TASK3_YOLO_MIN_CONFIDENCE_MILLI="$TASK3_YOLO_MIN_CONFIDENCE_MILLI"} \
        ${TASK3_YOLO_MIN_AREA_MILLI:+TASK3_YOLO_MIN_AREA_MILLI="$TASK3_YOLO_MIN_AREA_MILLI"} \
        ${TASK3_YOLO_MAX_TARGET_STEP:+TASK3_YOLO_MAX_TARGET_STEP="$TASK3_YOLO_MAX_TARGET_STEP"} \
        NCNN_PREFIX="$ncnn_prefix" \
        CXX_aarch64_unknown_linux_musl="$cross_cxx" \
        AR_aarch64_unknown_linux_musl="$cross_ar" \
        CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER="$cross_cc" \
        cargo build \
        --package arceos-task2-net \
        --no-default-features \
        --target "$target_triple" \
        --release \
        --target-dir "$target_dir"

    # Copy immediately: the next role deliberately uses another target tree.
    cp "$target_dir/$target_triple/release/arceos-task2-net" "$binary"
    chmod 0755 "$binary"
    sha256sum "$binary" | awk '{print $1}' > "$role_dir/task2-net.sha256"
    printf '%s\n' "$binary"
}

controller_binary="$(build_role controller 10.0.42.15 10.0.42.2 | tail -n 1)"
managed_binary="$(build_role managed 10.0.42.2 10.0.42.15 | tail -n 1)"
controller_sha="$(cat "$out_dir/controller/task2-net.sha256")"
managed_sha="$(cat "$out_dir/managed/task2-net.sha256")"

if [[ "$controller_sha" == "$managed_sha" ]]; then
    printf 'error: controller and managed binaries have identical hashes (%s)\n' "$controller_sha" >&2
    exit 1
fi

git_sha="$(git -C "$repo_root" rev-parse HEAD)"
rustc_version="$(rustc -Vv | sed -n '1p')"
cross_version="$("$cross_cc" --version | sed -n '1p')"
manifest="$out_dir/manifest.toml"
{
    printf '# Generated by scripts/test/net-dual-guest/build-linux-task2.sh\n'
    printf 'git_head = "%s"\n' "$git_sha"
    printf 'rustc = "%s"\n' "$rustc_version"
    printf 'cross_cc = "%s"\n' "$cross_cc"
    printf 'cross_cc_version = "%s"\n' "$cross_version"
    printf 'target = "%s"\n\n' "$target_triple"
    printf '[controller]\npath = "%s"\nsha256 = "%s"\nlocal_ip = "%s"\npeer_ip = "%s"\n\n' \
        "$controller_binary" "$controller_sha" "10.0.42.15" "10.0.42.2"
    printf '[managed]\npath = "%s"\nsha256 = "%s"\nlocal_ip = "%s"\npeer_ip = "%s"\n' \
        "$managed_binary" "$managed_sha" "10.0.42.2" "10.0.42.15"
} > "$manifest"

printf 'controller=%s sha256=%s\n' "$controller_binary" "$controller_sha"
printf 'managed=%s sha256=%s\n' "$managed_binary" "$managed_sha"
printf 'manifest=%s\n' "$manifest"
