env = {}
features = [
  "ax-hal/plat-dyn",
  "ax-drivers/virtio-blk",
  "ax-drivers/virtio-net",
  "starry-kernel/input",
  "starry-kernel/plat-dyn",
  "starry-kernel/vsock",
  "ax-drivers/intel-net",
  "ax-drivers/xhci-pci",
]
log = "Warn"
plat_dyn = true
target = "aarch64-unknown-none-softfloat"
