schema_version = 1
phase = "test"
group = "Workspace"

[[check]]
id = "run-clippy"
name = "Incremental Clippy"
runs_on = ["self-hosted", "linux", "qcs"]
environment = "host"
self_hosted_owner = "rcore-os"
fallback_environment = "base"
fetch_depth = "full"
download_xtask_bin_artifact = true
command = '''
cargo xtask clippy --since "$SINCE_REF"
'''

[[check]]
id = "test-with-std"
name = "std tests"
runs_on = ["self-hosted", "linux", "qcs"]
environment = "host"
self_hosted_owner = "rcore-os"
fallback_environment = "base"
command = '''
cargo xtask test
'''
