features = [
  "ax-driver/rk3588-cpufreq",
  "ax-driver/rockchip-dwmmc",
  "ax-driver/rockchip-sdhci",
]
log = "Error"
target = "aarch64-unknown-none-softfloat"
vm_configs = [
  "benchmarks/axvisor/board-orangepi-5-plus/ivc-benchmark/starry-axivc-benchmark.toml",
  "benchmarks/axvisor/board-orangepi-5-plus/ivc-benchmark/zephyr-axivc-benchmark.toml",
]
