// minimal GL 4.3 compute entry-point loader via OSMesaGetProcAddress (no GLEW dependency)
#ifndef GL_LOADER_H
#define GL_LOADER_H
#include <GL/osmesa.h>
#include <GL/glcorearb.h>
#define GLPROCS(X) \
  X(PFNGLCREATESHADERPROC,glCreateShader) X(PFNGLSHADERSOURCEPROC,glShaderSource) \
  X(PFNGLCOMPILESHADERPROC,glCompileShader) X(PFNGLGETSHADERIVPROC,glGetShaderiv) \
  X(PFNGLGETSHADERINFOLOGPROC,glGetShaderInfoLog) X(PFNGLCREATEPROGRAMPROC,glCreateProgram) \
  X(PFNGLATTACHSHADERPROC,glAttachShader) X(PFNGLLINKPROGRAMPROC,glLinkProgram) \
  X(PFNGLGETPROGRAMIVPROC,glGetProgramiv) X(PFNGLUSEPROGRAMPROC,glUseProgram) \
  X(PFNGLDELETESHADERPROC,glDeleteShader) X(PFNGLDELETEPROGRAMPROC,glDeleteProgram) \
  X(PFNGLGENBUFFERSPROC,glGenBuffers) X(PFNGLBINDBUFFERPROC,glBindBuffer) \
  X(PFNGLBUFFERDATAPROC,glBufferData) X(PFNGLBUFFERSUBDATAPROC,glBufferSubData) \
  X(PFNGLBINDBUFFERBASEPROC,glBindBufferBase) X(PFNGLMAPBUFFERRANGEPROC,glMapBufferRange) \
  X(PFNGLUNMAPBUFFERPROC,glUnmapBuffer) X(PFNGLGETBUFFERSUBDATAPROC,glGetBufferSubData) \
  X(PFNGLDELETEBUFFERSPROC,glDeleteBuffers) X(PFNGLDISPATCHCOMPUTEPROC,glDispatchCompute) \
  X(PFNGLMEMORYBARRIERPROC,glMemoryBarrier) X(PFNGLGETUNIFORMLOCATIONPROC,glGetUniformLocation) \
  X(PFNGLUNIFORM1FPROC,glUniform1f) X(PFNGLUNIFORM1UIPROC,glUniform1ui) \
  X(PFNGLGETINTEGERI_VPROC,glGetIntegeri_v) X(PFNGLBINDBUFFERRANGEPROC,glBindBufferRange) \
  X(PFNGLCOPYBUFFERSUBDATAPROC,glCopyBufferSubData) X(PFNGLCLEARBUFFERDATAPROC,glClearBufferData) \
  X(PFNGLGETBUFFERPARAMETERIVPROC,glGetBufferParameteriv) X(PFNGLSHADERSTORAGEBLOCKBINDINGPROC,glShaderStorageBlockBinding) \
  X(PFNGLGETPROGRAMRESOURCEINDEXPROC,glGetProgramResourceIndex) X(PFNGLGETPROGRAMINTERFACEIVPROC,glGetProgramInterfaceiv) \
  X(PFNGLGETPROGRAMRESOURCEIVPROC,glGetProgramResourceiv) X(PFNGLFENCESYNCPROC,glFenceSync) \
  X(PFNGLCLIENTWAITSYNCPROC,glClientWaitSync) X(PFNGLDELETESYNCPROC,glDeleteSync) \
  X(PFNGLDISPATCHCOMPUTEINDIRECTPROC,glDispatchComputeIndirect) X(PFNGLFLUSHMAPPEDBUFFERRANGEPROC,glFlushMappedBufferRange) \
  X(PFNGLGETPROGRAMINFOLOGPROC,glGetProgramInfoLog)
#define DECL(t,n) static t n;
GLPROCS(DECL)
static int gl_load(void){ int ok=1;
#define LOAD(t,n) n=(t)OSMesaGetProcAddress(#n); if(!n) ok=0;
  GLPROCS(LOAD)
  return ok; }
#endif
