[package]
name = "ax-net"
version = "0.12.10"
repository = "https://github.com/rcore-os/tgoskits"
edition.workspace = true
authors = ["Mivik <mivikq@gmail.com>"]
description = "Unified network stack for TGOSKits (ArceOS, StarryOS, Axvisor)"
license.workspace = true

[features]
host-test = [
    "ax-hal/host-test",
    "axpoll/host-test",
    "ax-sync/host-test",
    "ax-task/host-test",
]
vsock = ["dep:rdif-vsock"]

[dependencies]
async-channel = { version = "2.5", default-features = false }
async-trait = "0.1"
ax-hal = { workspace = true }
ax-io = { workspace = true }
ax-lazyinit.workspace = true
axpoll = { workspace = true }
ax-sync = { workspace = true, features = ["sleep"] }
ax-task.workspace = true
bitflags = "2.9"
cfg-if = { workspace = true }
enum_dispatch = "0.3"
event-listener = { version = "5.4", default-features = false }
hashbrown = "0.16"
irq-framework = { workspace = true }
log = { workspace = true }
rd-net = { workspace = true }
rand_chacha.workspace = true
rand_core.workspace = true
rdif-vsock = { workspace = true, optional = true }
ringbuf = { version = "0.4", default-features = false, features = ["alloc"] }
syscalls.workspace = true
thiserror.workspace = true

[dependencies.smoltcp]
workspace = true
features = [
  "alloc",
  "log",             # no std
  "async",
  "medium-ethernet",
  "medium-ip",
  "proto-ipv4",
  "proto-ipv6",
  "auto-icmp-echo-reply",
  "packetmeta-id",
  "socket-raw",
  "socket-icmp",
  "socket-udp",
  "socket-tcp",
  "socket-dhcpv4",
  "socket-dns",
  "iface-max-addr-count-8",
  # "fragmentation-buffer-size-65536", "proto-ipv4-fragmentation",
  # "reassembly-buffer-size-65536", "reassembly-buffer-count-32",
  # "assembler-max-segment-count-32",
]

[dev-dependencies]
ax-hal = { path = "../../os/arceos/modules/axhal", features = ["host-test"] }
ax-sync = { path = "../../os/arceos/modules/axsync", features = ["host-test"] }
ax-task = { path = "../../os/arceos/modules/axtask", features = ["host-test"] }

[[test]]
name = "std"
path = "tests/std.rs"
required-features = ["host-test"]
