args = [
  "-nographic",
  "-cpu", "cortex-a72",
  "-machine", "virt,virtualization=on,gic-version=3",
  "-smp", "4",
  "-m", "4g",
]
fail_regex = ["(?i)panic"]
success_regex = ["(LINUX_ZEPHYR_VIRTIO_NET_PASS|ZEPHYR_LINUX_VIRTIO_NET_PASS)"]
timeout = 180
to_bin = true
uefi = false
