args = [
  "-nographic",
  "-cpu", "cortex-a72",
  "-machine", "virt,virtualization=on,gic-version=3",
  "-smp", "4",
  "-m", "4g",
]
fail_regex = ["(?i)panic", "GIPC_RTOS_ERROR", "GIPC_LINUX_TIMEOUT"]
success_regex = [
  "(?s)GIPC_RTOS_READY.*GIPC_LINUX_STATUS.*GIPC_LINUX_METRIC",
]
timeout = 180
to_bin = true
uefi = false
