args = [
  "-nographic",
  "-cpu", "cortex-a72",
  "-machine", "virt,virtualization=on,gic-version=3",
  "-smp", "4",
  "-m", "4g",
]
fail_regex = ["VM1_VIRTIO_NET_FAIL", "VM2_VIRTIO_NET_FAIL", "(?i)panic"]
timeout = 180
to_bin = true
uefi = false

[[shell_check_steps]]
shell_prefix = "axvisor:$"
shell_cmd = "vm console 2"
success_regex = ["VM2_VIRTIO_NET_PASS"]

[[shell_check_steps]]
shell_prefix = "axvisor:$"
shell_cmd = "vm console 1"
success_regex = ["VM1_VIRTIO_NET_PASS"]
