args = [
  "-nographic",
  "-cpu", "cortex-a72",
  "-machine", "virt,virtualization=on,gic-version=3",
  "-smp", "4",
  "-m", "4g",
]
fail_regex = ["ARCEOS_VIRTIO_BLK_FAIL", "(?i)panic"]
timeout = 120
to_bin = true
uefi = false

[[shell_check_steps]]
shell_prefix = "axvisor:$"
shell_cmd = "vm console 1"
success_regex = ["ARCEOS_VIRTIO_BLK_PASS"]
