[package]
name = "netmon-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
netmon-common = { path = "../netmon-common" }
aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "netmon"
path = "src/main.rs"
