features = [
  "sdmmc",
  "rockchip-dwmmc",
  "rockchip-soc",
  "fs",
]
log = "Info"
target = "aarch64-unknown-none-softfloat"
vm_configs = [
  "competition/ivc/config/orangepi-5-plus-starry-smp2-ort-smoke.toml",
]
max_cpu_num = 4
board_type = "OrangePi-5-Plus"
shell_prefix = "AXVISOR_SHELL_READY"
shell_init_cmd = "ss 1 0 /home/orangepi/ort-result.img"
success_regex = [
  "(?m)^AXVISOR_HOST_FILESYSTEM_SYNCED\\r?$",
]
fail_regex = [
  "(?m)^.*THERMAL_ORT_STARRY_FAIL.*$",
  "(?m)^.*IVC_ORT_ERROR.*$",
  "(?m)^.*AXVISOR_HOST_FILESYSTEM_SYNC_FAILED:.*$",
  "(?m)^.*AXVISOR_VM_BLOCK_SNAPSHOT_FAILED:.*$",
  "(?m)^.*Failed to initialize guest VM.*$",
  "(?m)^.*Unhandled synchronous exception from current EL:.*$",
  "(?mi)^.*panicked at.*$",
]
timeout = 300
