board_type = "OrangePi-5-Plus"
shell_prefix = "root@starry:/root #"
success_regex = ['(?m)^uvc-fps: frames=[0-9]+ fps=[0-9]+(\.[0-9]+)? bytes=[0-9]+ throughput_mib_s=[0-9]+(\.[0-9]+)?']
fail_regex = [
  '(?i)\bpanic(?:ked)?\b',
  '(?m)^uvc-fps: error:',
]
timeout = 300
