[package]
authors.workspace = true
categories = ["embedded", "hardware-support", "no-std"]
description = "Portable Intel High Definition Audio controller core"
edition.workspace = true
keywords = ["intel", "hda", "audio", "no-std"]
license = "Apache-2.0"
name = "intel-hda"
repository.workspace = true
version = "0.1.0"

[dependencies]
dma-api.workspace = true
mmio-api.workspace = true
thiserror.workspace = true
rdif-audio = { workspace = true, optional = true }

[package.metadata.clippy]
configurations = [{ name = "x86_64-none", target = "x86_64-unknown-none" }]

[features]
rdif = ["dep:rdif-audio"]
