features = ["ax-driver/rk3588-cpufreq", "ax-driver/rockchip-sdhci", "fs"]
log = "Info"
target = "aarch64-unknown-none-softfloat"
vm_configs = [
    "apps/axvisor/triple-vm-test/configs/linux.toml",
    "apps/axvisor/triple-vm-test/configs/arceos.toml",
    "apps/axvisor/triple-vm-test/configs/zephyr.toml",
]
