[package]
name = "cv181x-clock"
version = "0.1.0"
description = "CV181x BSP PWM clock resource support"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mmio-api.workspace = true
rdif-clk.workspace = true
tock-registers.workspace = true
