[package]
name = "ax-api"
version = "0.7.9"
repository = "https://github.com/rcore-os/tgoskits"
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Public APIs and types for ArceOS modules"
license.workspace = true

[features]
default = []

host-test = [
  "ax-hal/host-test",
  "ax-ipi?/host-test",
  "ax-runtime/host-test",
  "ax-task/host-test",
]
ipi = ["dep:ax-ipi"]
alloc = ["dep:ax-alloc"]
paging = ["dep:ax-mm"]
fs = ["dep:ax-fs-ng"]
net = ["dep:ax-net"]
display = ["dep:ax-display"]


# Use stub functions if the feature is not enabled.
dummy-if-not-enabled = []

[dependencies]
ax-alloc = { workspace = true, optional = true }
ax-display = { workspace = true, optional = true }
ax-fs-ng = { workspace = true, optional = true }
ax-hal.workspace = true
ax-io.workspace = true
ax-ipi = { workspace = true, optional = true }
ax-lazyinit.workspace = true
ax-log.workspace = true
ax-mm = { workspace = true, optional = true }
ax-net = { workspace = true, optional = true }
axpoll.workspace = true
ax-runtime.workspace = true
ax-task.workspace = true
axklib.workspace = true
dma-api.workspace = true
thiserror.workspace = true
