# AxVM machine policy.
[machine]
mode = "passthrough"
firmware = "auto"
interrupts_passthrough = true

[base]
id = 1
name = "linux-asus-nuc15crh"
cpu_num = 1
phys_cpu_sets = [0x1]

[kernel]
entry_point = 0x8000
image_location = "memory"
kernel_path = "../../../../../tmp/qemu-x86_64/linux/linux-qemu"
kernel_load_addr = 0x200000
enable_bios = false
ramdisk_path = "../../../../../tmp/initramfs-x86_64-busybox.cpio"
ramdisk_load_addr = 0x6000000
cmdline = "console=ttyS0,115200n8 earlycon=uart8250,io,0x3f8,115200 ignore_loglevel loglevel=8 rdinit=/init devtmpfs.mount=1 acpi=off pci=off nox2apic tsc=unstable no_timer_check initcall_blacklist=ahci_pci_driver_init,i8042_init"

[[memory.regions]]
guest_base = 0x0
size = 0x8000000
permissions = "rwx"
backing = { kind = "allocate" }

[devices]
disable_defaults = []
deny = []

[[devices.virtual]]
id = "x86-com1"
model = "x86-com1"
source = { kind = "auto" }
backend = { kind = "host-console", rx = "exclusive", tx = "shared" }
