// tap-carpet - StarryOS TAP (/dev/net/tun, IFF_TAP) datapath and lifecycle carpet.
//
// Covers:
//   Phase 1 - SIOCGIFHWADDR: read the kernel-assigned MAC address of the TAP device.
//   Phase 2 - ARP handshake: write an ARP request (broadcast, IFF_NO_PI Ethernet frame)
//             and read the ARP reply generated by the kernel's smoltcp Ethernet stack.
//   Phase 3 - close/recreate: non-persistent TAP device disappears on last-fd-close,
//             and the same name can immediately be re-allocated.
//   Phase 4 - TUNSETPERSIST: persistent device survives last-fd-close; a second fd
//             can re-attach; clearing persist makes the device go away on close.
//   Phase 5 - second-fd EBUSY: attaching a second fd to a non-multi-queue TAP returns EBUSY.
//   Phase 6 - unsupported-flags EINVAL: IFF_TAP | <unknown flag> rejects with EINVAL.
//
// Ethernet frames in IFF_TAP | IFF_NO_PI mode have no packet-info prefix;
// each write/read is one raw Ethernet frame starting with dst_mac[6].

#define _GNU_SOURCE
#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <net/if.h>
#include <netinet/in.h>
#include <poll.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <unistd.h>

#define IFF_TUN          0x0001
#define IFF_TAP          0x0002
#define IFF_NO_PI        0x1000
#define TUNSETIFF        _IOW('T', 202, int)
#define TUNGETIFF        _IOR('T', 210, unsigned int)
#define TUNSETPERSIST    _IOW('T', 203, int)
#define TUNGETFEATURES   _IOR('T', 207, unsigned int)

#define TAP_PATH "/dev/net/tun"

static int failures;

static void check(const char *label, int ok) {
    printf("%-42s %s\n", label, ok ? "PASS" : "FAIL");
    if (!ok) failures++;
}

static int open_tap(void) {
    return open(TAP_PATH, O_RDWR);
}

static int setiff_tap(int fd, const char *name, short flags) {
    struct ifreq ifr;
    memset(&ifr, 0, sizeof(ifr));
    if (name && *name)
        strncpy(ifr.ifr_name, name, IFNAMSIZ - 1);
    ifr.ifr_flags = flags;
    return ioctl(fd, TUNSETIFF, &ifr);
}

static int configure_tap(const char *ifname) {
    int s = socket(AF_INET, SOCK_DGRAM, 0);
    if (s < 0) return -1;

    struct ifreq ifr;
    memset(&ifr, 0, sizeof(ifr));
    strncpy(ifr.ifr_name, ifname, IFNAMSIZ - 1);

    struct sockaddr_in *sin = (struct sockaddr_in *)&ifr.ifr_addr;
    memset(sin, 0, sizeof(*sin));
    sin->sin_family = AF_INET;
    sin->sin_addr.s_addr = inet_addr("10.8.2.1");
    if (ioctl(s, SIOCSIFADDR, &ifr) < 0) { close(s); return -2; }

    memset(sin, 0, sizeof(*sin));
    sin->sin_family = AF_INET;
    sin->sin_addr.s_addr = inet_addr("255.255.255.0");
    if (ioctl(s, SIOCSIFNETMASK, &ifr) < 0) { close(s); return -3; }

    memset(&ifr.ifr_flags, 0, sizeof(ifr.ifr_flags));
    ifr.ifr_flags = IFF_UP | IFF_RUNNING;
    if (ioctl(s, SIOCSIFFLAGS, &ifr) < 0) { close(s); return -4; }

    close(s);
    return 0;
}

static ssize_t read_frame(int fd, uint8_t *buf, size_t cap, int timeout_ms) {
    struct pollfd pfd = {.fd = fd, .events = POLLIN};
    int r = poll(&pfd, 1, timeout_ms);
    if (r <= 0) return -1;
    return read(fd, buf, cap);
}

// --- Phase 1: SIOCGIFHWADDR ---
static void phase_hwaddr(uint8_t mac_out[6]) {
    int s = socket(AF_INET, SOCK_DGRAM, 0);
    check("SIOCGIFHWADDR: open control socket", s >= 0);
    if (s < 0) return;
    struct ifreq ifr;
    memset(&ifr, 0, sizeof(ifr));
    strncpy(ifr.ifr_name, "tcarp0", IFNAMSIZ - 1);
    int r = ioctl(s, SIOCGIFHWADDR, &ifr);
    close(s);
    check("SIOCGIFHWADDR returns success", r == 0);
    if (r == 0) {
        memcpy(mac_out, ifr.ifr_hwaddr.sa_data, 6);
        // A valid unicast MAC has the multicast bit (LSB of first byte) clear.
        check("SIOCGIFHWADDR MAC multicast-bit clear",
              (mac_out[0] & 0x01) == 0);
        // Locally-administered bit (second-LSB of first byte) is set for tap MACs.
        check("SIOCGIFHWADDR MAC locally-administered-bit set",
              (mac_out[0] & 0x02) != 0);
        // MAC must not be all-zero.
        int nonzero = 0;
        for (int i = 0; i < 6; i++) nonzero |= mac_out[i];
        check("SIOCGIFHWADDR MAC non-zero", nonzero != 0);
    }
}

// --- Phase 2: ARP handshake over raw Ethernet (IFF_TAP | IFF_NO_PI) ---
//
// We craft an ARP-request Ethernet broadcast frame and inject it via the TAP fd.
// The smoltcp EthernetInterface receives the L2 frame, parses the ARP request,
// and generates an ARP reply which reappears on the fd.
static void phase_arp(int fd, const uint8_t tap_mac[6]) {
    // Our pseudo-MAC (locally administered, unicast).
    static const uint8_t our_mac[6] = {0x02, 0xaa, 0xbb, 0xcc, 0xdd, 0xee};
    static const uint8_t broadcast[6] = {0xff, 0xff, 0xff, 0xff, 0xff, 0xff};
    const uint32_t tap_ip = htonl(inet_addr("10.8.2.1"));   // little-endian on write
    const uint32_t our_ip = htonl(inet_addr("10.8.2.2"));

    // ARP request Ethernet frame (42 bytes total, no FCS in IFF_NO_PI mode).
    uint8_t frame[42];
    memset(frame, 0, sizeof(frame));
    // Ethernet header (14 bytes).
    memcpy(frame + 0, broadcast, 6);    // dst: broadcast
    memcpy(frame + 6, our_mac, 6);      // src: our MAC
    frame[12] = 0x08; frame[13] = 0x06; // EtherType: ARP

    // ARP payload (28 bytes) at offset 14.
    uint8_t *arp = frame + 14;
    arp[0] = 0x00; arp[1] = 0x01; // hw type: Ethernet
    arp[2] = 0x08; arp[3] = 0x00; // proto type: IPv4
    arp[4] = 6;                    // hw addr len
    arp[5] = 4;                    // proto addr len
    arp[6] = 0x00; arp[7] = 0x01; // operation: request
    memcpy(arp + 8, our_mac, 6);           // sender hw: our MAC
    memcpy(arp + 14, &our_ip, 4);          // sender ip: 10.8.2.2 (network order)
    memset(arp + 18, 0, 6);                // target hw: unknown
    memcpy(arp + 24, &tap_ip, 4);          // target ip: 10.8.2.1

    ssize_t w = write(fd, frame, sizeof(frame));
    check("write ARP request frame", w == (ssize_t)sizeof(frame));

    // Read ARP reply from smoltcp (may take several poll rounds).
    int got_reply = 0;
    uint8_t in[128];
    for (int attempt = 0; attempt < 8 && !got_reply; attempt++) {
        ssize_t n = read_frame(fd, in, sizeof(in), 2000);
        if (n < 42) continue;
        // EtherType must be ARP.
        if (in[12] != 0x08 || in[13] != 0x06) continue;
        uint8_t *ra = in + 14;
        // ARP operation must be reply (0x0002).
        if (ra[6] != 0x00 || ra[7] != 0x02) continue;

        // sender hw == tap_mac, sender ip == 10.8.2.1
        int sender_mac_ok = (memcmp(ra + 8, tap_mac, 6) == 0);
        uint32_t sender_ip;
        memcpy(&sender_ip, ra + 14, 4);
        int sender_ip_ok = (sender_ip == tap_ip);

        // target hw == our_mac, target ip == 10.8.2.2
        int target_mac_ok = (memcmp(ra + 18, our_mac, 6) == 0);
        uint32_t target_ip;
        memcpy(&target_ip, ra + 24, 4);
        int target_ip_ok = (target_ip == our_ip);

        // Ethernet dst == our_mac, src == tap_mac
        int eth_dst_ok = (memcmp(in + 0, our_mac, 6) == 0);
        int eth_src_ok = (memcmp(in + 6, tap_mac, 6) == 0);

        check("ARP reply Ethernet dst == our MAC", eth_dst_ok);
        check("ARP reply Ethernet src == tap MAC", eth_src_ok);
        check("ARP reply sender hw == tap MAC", sender_mac_ok);
        check("ARP reply sender ip == 10.8.2.1", sender_ip_ok);
        check("ARP reply target hw == our MAC", target_mac_ok);
        check("ARP reply target ip == 10.8.2.2", target_ip_ok);
        got_reply = 1;
    }
    check("kernel produced ARP reply", got_reply);
}

// --- Phase 3: close/recreate ---
static void phase_close_recreate(void) {
    int fd1 = open_tap();
    check("close/recreate: open fd1", fd1 >= 0);
    if (fd1 < 0) return;
    check("close/recreate: TUNSETIFF tap1",
          setiff_tap(fd1, "tcrec0", IFF_TAP | IFF_NO_PI) == 0);
    // Close without persist → device should be destroyed.
    close(fd1);

    // Re-open and re-attach same name immediately.
    int fd2 = open_tap();
    check("close/recreate: reopen fd", fd2 >= 0);
    if (fd2 < 0) return;
    int r2 = setiff_tap(fd2, "tcrec0", IFF_TAP | IFF_NO_PI);
    check("close/recreate: reattach same name succeeds", r2 == 0);
    close(fd2);
}

// --- Phase 4: TUNSETPERSIST ---
static void phase_persist(void) {
    int fd1 = open_tap();
    check("persist: open fd1", fd1 >= 0);
    if (fd1 < 0) return;
    check("persist: TUNSETIFF persisted tap",
          setiff_tap(fd1, "tpersist0", IFF_TAP | IFF_NO_PI) == 0);
    check("persist: TUNSETPERSIST 1",
          ioctl(fd1, TUNSETPERSIST, 1L) == 0);
    close(fd1);

    // Device must survive; second fd must re-attach.
    int fd2 = open_tap();
    check("persist: reopen after close", fd2 >= 0);
    if (fd2 < 0) return;
    check("persist: re-attach to persistent device succeeds",
          setiff_tap(fd2, "tpersist0", IFF_TAP | IFF_NO_PI) == 0);

    // Disable persist so the device is cleaned up on fd2 close.
    check("persist: TUNSETPERSIST 0",
          ioctl(fd2, TUNSETPERSIST, 0L) == 0);
    close(fd2);
}

// --- Phase 5: second-fd EBUSY ---
static void phase_ebusy(void) {
    int fd1 = open_tap();
    int fd2 = open_tap();
    check("ebusy: open fd1 and fd2", fd1 >= 0 && fd2 >= 0);
    if (fd1 < 0 || fd2 < 0) { close(fd1); close(fd2); return; }

    check("ebusy: first fd binds tebusy0",
          setiff_tap(fd1, "tebusy0", IFF_TAP | IFF_NO_PI) == 0);
    int r = setiff_tap(fd2, "tebusy0", IFF_TAP | IFF_NO_PI);
    check("ebusy: second fd → EBUSY",
          r == -1 && errno == EBUSY);

    close(fd1);
    close(fd2);
}

// --- Phase 6: unsupported flags EINVAL ---
static void phase_bad_flags(void) {
    int fd = open_tap();
    check("bad-flags: open fd", fd >= 0);
    if (fd < 0) return;

    // IFF_VNET_HDR (0x4000) is not in TUN_SUPPORTED_FLAGS → EINVAL.
    int r = setiff_tap(fd, "tbad0", IFF_TAP | 0x4000);
    check("bad-flags: IFF_TAP | unsupported bit → EINVAL",
          r == -1 && errno == EINVAL);
    close(fd);
}

// --- Phase 7: TUNGETIFF on TAP ---
static void phase_getiff(int fd) {
    struct ifreq ifr;
    memset(&ifr, 0, sizeof(ifr));
    int r = ioctl(fd, TUNGETIFF, &ifr);
    check("TUNGETIFF on TAP fd succeeds", r == 0);
    check("TUNGETIFF name == tcarp0",
          strcmp(ifr.ifr_name, "tcarp0") == 0);
    check("TUNGETIFF flags include IFF_TAP",
          (ifr.ifr_flags & IFF_TAP) != 0);
    check("TUNGETIFF flags include IFF_NO_PI",
          (ifr.ifr_flags & IFF_NO_PI) != 0);
}

int main(void) {
    printf("== tap-carpet ==\n");

    // Open main TAP device for phases 1, 2, 7.
    int fd = open_tap();
    check("open /dev/net/tun", fd >= 0);
    if (fd < 0) {
        printf("ALL CHECKS FAILED\n");
        return 1;
    }

    check("TUNSETIFF tcarp0 (IFF_TAP|IFF_NO_PI)",
          setiff_tap(fd, "tcarp0", IFF_TAP | IFF_NO_PI) == 0);

    phase_getiff(fd);

    uint8_t tap_mac[6] = {0};
    phase_hwaddr(tap_mac);

    check("configure tcarp0 IP", configure_tap("tcarp0") == 0);

    phase_arp(fd, tap_mac);

    close(fd);

    phase_close_recreate();
    phase_persist();
    phase_ebusy();
    phase_bad_flags();

    printf("\n");
    if (failures == 0) {
        printf("ALL TAP CHECKS PASSED\n");
        return 0;
    }
    printf("ALL TAP CHECKS FAILED (%d)\n", failures);
    return 1;
}
