//! Web management dashboard bundle extraction and serving (`web-ui` feature).
//!
//! The React/Vite app under `web-ui/` is built by `build.rs` (which runs
//! `npm ci && npm run build`) and packed into a deterministic gzip tarball
//! embedded at compile time via `include_bytes!` (see `web_ui_bundle.rs`,
//! generated by the build script). At startup [`init`] stream-extracts that
//! bundle into `/web/axvisor-ui/.staging` and atomically swaps it into
//! `/web/axvisor-ui/current`, then the axum router serves `current/` with
//! `tower-http::ServeDir` under a strict `Content-Security-Policy`.
//!
//! `web-ui` implies `http-axum` and `fs`, so the host rootfs is mounted and
//! writable before [`init`] runs. The management API (`/api/*`) is assembled in
//! `server.rs` and is independent of the UI: if the bundle cannot be extracted
//! the UI routes return `503` while `/api/*` keeps serving.
//!
//! The dashboard talks to the API from the same origin. The operator's bearer
//! token is entered in the dashboard and held only in memory (never persisted
//! to `localStorage`/`sessionStorage`), and is sent on the mutating
//! `start`/`stop`/`pause`/`resume` requests.

use std::io::Read;
use std::path::{Component, Path};

use axum::{
    Router,
    http::{StatusCode, header},
};
use tower_http::services::ServeDir;
use tower_http::set_header::SetResponseHeaderLayer;

// Generated by `build.rs` into `OUT_DIR`. `WEB_UI_BUNDLE_GZ` is the embedded,
// normalized gzip tarball of `dist/`.
include!(concat!(env!("OUT_DIR"), "/web_ui_bundle.rs"));

use super::WebUiStatus;

/// Directory on the mounted rootfs holding the extracted UI.
const UI_DIR: &str = "/web/axvisor-ui";
/// Staging location used during extraction, then atomically renamed.
const STAGING: &str = "/web/axvisor-ui/.staging";
/// Final, served location of the UI.
const CURRENT: &str = "/web/axvisor-ui/current";

/// Strict CSP: only same-origin scripts/styles, no external origins, no framing.
const CSP: &str = "default-src 'self'; \
    script-src 'self'; \
    style-src 'self' 'unsafe-inline'; \
    img-src 'self' data:; \
    font-src 'self'; \
    connect-src 'self'; \
    base-uri 'self'; \
    form-action 'self'; \
    frame-ancestors 'none'";

/// Extract the embedded bundle into `current/` and report readiness.
///
/// Called once from `http::serve()` before the tokio runtime is built. These
/// are blocking filesystem writes and must not contend with the IO driver's
/// event loop. On any failure the UI is marked [`WebUiStatus::Unavailable`]
/// rather than partially served.
pub fn init() -> WebUiStatus {
    match extract_bundle() {
        Ok(count) => {
            info!(
                "web-ui: extracted {count} files (bundle: {} files, {} bytes uncompressed) to {CURRENT}",
                WEB_UI_FILE_COUNT, WEB_UI_UNCOMPRESSED_BYTES
            );
            WebUiStatus::Ready
        }
        Err(e) => {
            error!("web-ui: extraction failed: {e}; UI endpoints will return 503");
            WebUiStatus::Unavailable {
                reason: "bundle extraction failed",
            }
        }
    }
}

/// Error type for bundle extraction failures.
#[derive(Debug)]
pub struct ExtractError(String);

impl std::fmt::Display for ExtractError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for ExtractError {}

fn extract_err(msg: impl Into<String>) -> ExtractError {
    ExtractError(msg.into())
}

/// Stream-extract [`WEB_UI_BUNDLE_GZ`] into `current/`.
///
/// Every tar entry is guarded against path traversal and symlinks; the staging
/// directory is written fully before an atomic rename to `current/`.
fn extract_bundle() -> Result<usize, ExtractError> {
    // Start from a clean staging area.
    if Path::new(STAGING).exists() {
        std::fs::remove_dir_all(STAGING).map_err(|e| extract_err(e.to_string()))?;
    }
    std::fs::create_dir_all(UI_DIR).map_err(|e| extract_err(e.to_string()))?;
    std::fs::create_dir_all(STAGING).map_err(|e| extract_err(e.to_string()))?;

    let reader = flate2::read::GzDecoder::new(std::io::Cursor::new(WEB_UI_BUNDLE_GZ));
    let mut archive = tar::Archive::new(reader);

    let mut count = 0usize;
    for entry in archive
        .entries()
        .map_err(|e| extract_err(format!("reading tar: {e}")))?
    {
        let mut entry = entry.map_err(|e| extract_err(format!("tar entry: {e}")))?;
        let name = entry
            .path()
            .map_err(|e| extract_err(format!("entry path: {e}")))?
            .into_owned();
        guard_entry_name(&name)?;

        let is_dir = entry.header().entry_type().is_dir();
        let target = Path::new(STAGING).join(&name);

        // Re-check after joining: resolve symlinks are rejected below, but a
        // non-canonical relative name must still stay under `STAGING`.
        if !target.starts_with(STAGING) {
            return Err(extract_err(format!(
                "entry {name:?} escapes staging directory"
            )));
        }

        if entry.header().entry_type().is_symlink() {
            return Err(extract_err(format!(
                "symlink entries are not allowed: {name:?}"
            )));
        }

        if is_dir {
            std::fs::create_dir_all(&target).map_err(|e| extract_err(e.to_string()))?;
            continue;
        }

        let mut data = Vec::new();
        entry
            .read_to_end(&mut data)
            .map_err(|e| extract_err(format!("reading {name:?}: {e}")))?;
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent).map_err(|e| extract_err(e.to_string()))?;
        }
        std::fs::write(&target, &data).map_err(|e| extract_err(e.to_string()))?;
        count += 1;
    }

    // Atomic swap: remove any previous `current/`, then rename staging in.
    if Path::new(CURRENT).exists() {
        std::fs::remove_dir_all(CURRENT).map_err(|e| extract_err(e.to_string()))?;
    }
    std::fs::rename(STAGING, CURRENT).map_err(|e| extract_err(e.to_string()))?;
    // Defensive cleanup if a stale staging dir remains.
    if Path::new(STAGING).exists() {
        let _ = std::fs::remove_dir_all(STAGING);
    }

    Ok(count)
}

/// Reject absolute paths, parent-dir (`..`) components, and empty names.
fn guard_entry_name(name: &Path) -> Result<(), ExtractError> {
    if name.as_os_str().is_empty() {
        return Err(extract_err("empty entry name in bundle"));
    }
    for component in name.components() {
        match component {
            Component::ParentDir => {
                return Err(extract_err(format!(
                    "path traversal in bundle entry: {name:?}"
                )));
            }
            Component::RootDir => {
                return Err(extract_err(format!(
                    "absolute path in bundle entry: {name:?}"
                )));
            }
            _ => {}
        }
    }
    Ok(())
}

/// Apply the security headers shared by every UI response.
fn security_layers(router: Router) -> Router {
    router
        .layer(SetResponseHeaderLayer::overriding(
            header::CONTENT_SECURITY_POLICY,
            header::HeaderValue::from_static(CSP),
        ))
        .layer(SetResponseHeaderLayer::overriding(
            header::X_CONTENT_TYPE_OPTIONS,
            header::HeaderValue::from_static("nosniff"),
        ))
        .layer(SetResponseHeaderLayer::overriding(
            header::REFERRER_POLICY,
            header::HeaderValue::from_static("no-referrer"),
        ))
}

/// Routes for the web dashboard assets.
///
/// When the UI is [`WebUiStatus::Ready`], a `ServeDir` over `current/` serves
/// `/` as `index.html` and the hashed `/assets/*` files. Missing paths return
/// `404` (no SPA fallback), so stale asset names from the old hand-written UI
/// (`/dashboard.js`, `/style.css`) correctly 404. When the UI is
/// [`WebUiStatus::Unavailable`], every UI path returns `503` while `/api/*`
/// (assembled in `server.rs`) continues to serve.
pub fn ui_routes(status: WebUiStatus) -> Router {
    let router = Router::new();
    let router = if status.is_ready() {
        router.fallback_service(ServeDir::new(CURRENT).append_index_html_on_directories(true))
    } else {
        // `reason` is `Copy`, so the closure stays `Fn` across repeated requests.
        let reason = match status {
            WebUiStatus::Unavailable { reason } => reason,
            WebUiStatus::Ready => "",
        };
        router.fallback(move || async move {
            (
                StatusCode::SERVICE_UNAVAILABLE,
                [(
                    header::CONTENT_TYPE,
                    header::HeaderValue::from_static("text/plain; charset=utf-8"),
                )],
                format!("Web UI is unavailable: {reason}"),
            )
        })
    };

    security_layers(router)
}
