[package]
name = "axpoll-set"
version = "0.1.0"
edition.workspace = true
description = "Shared and exclusive readiness queue implementation."
documentation = "https://docs.rs/axpoll-set"
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
host-test = ["ax-sync/host-test"]

[dependencies]
ax-lazyinit.workspace = true
ax-sync.workspace = true
axpoll.workspace = true

[dev-dependencies]
ax-sync = { path = "../../os/arceos/modules/axsync", features = ["host-test"] }
futures = "0.3"
tokio = { version = "1.37", features = [
    "rt-multi-thread",
    "macros",
    "time",
    "sync",
] }

[[test]]
name = "std"
path = "tests/std.rs"
required-features = ["host-test"]
