cmake_minimum_required(VERSION 3.20)
project(test-e1000-napi-runtime C)
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)
add_executable(test-e1000-napi-runtime src/main.c)
target_compile_options(test-e1000-napi-runtime PRIVATE -Wall -Wextra -Werror)
install(TARGETS test-e1000-napi-runtime RUNTIME DESTINATION usr/bin/starry-test-suit)
